### ISSUE TITLE
Vm service initialization attempting to show error after a successful connection.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1369] opened 2019-11-20 20:13 UTC
Causing this bug: https://github.com/flutter/devtools/issues/1315

We should fix the root issue instead of relying on the workaround in https://github.com/flutter/devtools/pull/1368.

**Comment by jacob314** [comment] 2020-01-07 22:00
@DaveShuckerow I think you were looking at another dupe of this bug.

**Closed** 2020-01-23 19:56 UTC
Labels: hummingbird
