### ISSUE TITLE
have a way to show when a thread is de-scheduled

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#778] opened 2019-07-09 16:30 UTC
One thing that the Observatory's timeline page can show is when a thread is de-scheduled by the CPU. I think it does this by showing the thread - or events? - in a less saturated color?

In any case, the info would likely be useful for users to know what's going on in their frames.

**Comment by kenzieschmoll** [comment] 2022-03-08 19:10
closing as dupe of https://github.com/flutter/devtools/issues/3454

**Closed** 2022-03-08 19:10 UTC
Labels: timeline page
