### ISSUE TITLE
Timeline assert w/o every touching timeline tab.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#1983] opened 2020-05-18 19:51 UTC
```
Launching lib/main.dart on Linux in debug mode...
GLFW error 65544: X11: RandR gamma ramp support seems broken
flutter: DevTools version 0.2.5.
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:devtools_app/src/utils.dart': Failed assertion: line 420 pos 14: '_start == null': is not true.
#0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
#2      TimeRange.start=
#3      TimelineProcessor.processTimeline
<asynchronous suspension>
#4      TimelineController.processTraceEvents
#5      TimelineController.refreshData
<asynchronous suspension>
#6      TimelineScreenBodyState.didChangeDependencies
#7      StatefulElement._firstBuild
#8      ComponentElement.mount
#9      Element.inflateWidget
#10     Element.updateChild
#11     ComponentElement.performRebuild
#12     Element.rebuild
#13     ComponentElement._firstBuild
#14     ComponentElement.mount
#15     Element.inflateWidget
#16     MultiChildRenderObjectElement.mount
#17     Element.inflateWidget
#18     Element.updateChild
#19     ComponentElement.performRebuild
#20     Element.rebuild
#21     ComponentElement._firstBuild
#22     ComponentElement.mount
#23     Element.inflateWidget
#24     Element.updateChild
#25     ComponentElement.performRebuild
#26     Element.rebuild
#27     ComponentElement._firstBuild
#28     ComponentElement.mount
#29     Element.inflateWidget
#30     Element.updateChild
#31     SingleChildRenderObjectElement.mount
#32     Element.inflateWidget
#33     Element.updateChild
#34     ComponentElement.performRebuild
#35     StatefulElement.performRebuild
#36     Element.rebuild
#37     ComponentElement._firstBuild
#38     StatefulElement._firstBuild
#39     ComponentElement.mount
#40     Element.inflateWidget
#41     Element.updateChild
#42     SingleChildRenderObjectElement.mount
#43     Element.inflateWidget
#44     Element.updateChild
#45     SingleChildRenderObjectElement.mount
#46     Element.inflateWidget
#47     Element.updateChild
#48     ComponentElement.performRebuild
#49     Element.rebuild
#50     ComponentElement._firstBuild
#51     ComponentElement.mount
#52     Element.inflateWidget
#53     Element.updateChild
#54     ComponentElement.performRebuild
#55     Element.rebuild
#56     ComponentElement._firstBuild
#57     ComponentElement.mount
#58     Element.inflateWidget
#59     Element.updateChild
#60     SingleChildRenderObjectElement.mount
#61     Element.inflateWidget
#62     Element.updateChild
#63     SingleChildRenderObjectElement.mount
#64     Element.inflateWidget
#65     Element.updateChild
#66     ComponentElement.performRebuild
#67     Element.rebuild
#68     ComponentElement._firstBuild
#69     ComponentElement.mount
#70     Element.inflateWidget
#71     Element.updateChild
#72     ComponentElement.performRebuild
#73     Element.rebuild
#74     ComponentElement._firstBuild
#75     ComponentElement.mount
#76     Element.inflateWidget
#77     Element.updateChild
#78     ComponentElement.performRebuild
#79     StatefulElement.performRebuild
#80     Element.rebuild
#81     ComponentElement._firstBuild
#82     StatefulElement._firstBuild
#83     ComponentElement.mount
#84     Element.inflateWidget
#85     Element.updateChild
#86     ComponentElement.performRebuild
#87     Element.rebuild
#88     ComponentElement._firstBuild
#89     ComponentElement.mount
#90     Element.inflateWidget
#91     Element.updateChild
#92     SliverMultiBoxAdaptorElement.updateChild
#93     SliverMultiBoxAdaptorElement.performRebuild.processElement
#94     Iterable.forEach  (dart:core/iterable.dart:279:30)
#95     SliverMultiBoxAdaptorElement.performRebuild
#96     SliverMultiBoxAdaptorElement.update
#97     Element.updateChild
#98     SingleChildRenderObjectElement.update
#99     Element.updateChild
#100    ComponentElement.performRebuild
#101    Element.rebuild
#102    StatelessElement.update
#103    Element.updateChild
#104    RenderObjectElement.updateChildren
#105    MultiChildRenderObjectElement.update
#106    _ViewportElement.update
#107    Element.updateChild
#108    SingleChildRenderObjectElement.update
#109    Element.updateChild
#110    SingleChildRenderObjectElement.update
#111    Element.updateChild
#112    SingleChildRenderObjectElement.update
#113    Element.updateChild
#114    ComponentElement.performRebuild
#115    Element.rebuild
#116    StatelessElement.update
#117    Element.updateChild
#118    SingleChildRenderObjectElement.update
#119    Element.updateChild
#120    ComponentElement.performRebuild
#121    StatefulElement.performRebuild
#122    Element.rebuild
#123    StatefulElement.update
#124    Element.updateChild
#125    SingleChildRenderObjectElement.update
#126    Element.updateChild
#127    ComponentElement.performRebuild
#128    Element.rebuild
#129    StatelessElement.update
#130    Element.updateChild
#131    ComponentElement.performRebuild
#132    Element.rebuild
#133    ProxyElement.update
#134    Element.updateChild
#135    SingleChildRenderObjectElement.update
#136    Element.updateChild
#137    SingleChildRenderObjectElement.update
#138    Element.updateChild
#139    SingleChildRenderObjectElement.update
#140    Element.updateChild
#141    SingleChildRenderObjectElement.update
#142    Element.updateChild
#143    ComponentElement.performRebuild
#144    Element.rebuild
#145    StatelessElement.update
#146    Element.updateChild
#147    ComponentElement.performRebuild
#148    StatefulElement.performRebuild
#149    Element.rebuild
#150    StatefulElement.update
#151    Element.updateChild
#152    ComponentElement.performRebuild
#153    StatefulElement.performRebuild
#154    Element.rebuild
#155    StatefulElement.update
#156    Element.updateChild
#157    ComponentElement.performRebuild
#158    Element.rebuild
#159    StatelessElement.update
#160    Element.updateChild
#161    ComponentElement.performRebuild
#162    StatefulElement.performRebuild
#163    Element.rebuild
#164    StatefulElement.update
#165    Element.updateChild
#166    ComponentElement.performRebuild
#167    Element.rebuild
#168    StatelessElement.update
#169    Element.updateChild
#170    ComponentElement.performRebuild
#171    StatefulElement.performRebuild
#172    Element.rebuild
#173    BuildOwner.buildScope
#174    WidgetsBinding.drawFrame
#175    RendererBinding._handlePersistentFrameCallback
#176    SchedulerBinding._invokeFrameCallback
#177    SchedulerBinding.handleDrawFrame
#178    SchedulerBinding._handleDrawFrame
#179    _rootRun  (dart:async/zone.dart:1184:13)
#180    _CustomZone.run  (dart:async/zone.dart:1077:19)
#181    _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
#182    _invoke  (dart:ui/hooks.dart:277:10)
#183    _drawFrame  (dart:ui/hooks.dart:235:3)

```

**Comment by kenzieschmoll** [comment] 2020-05-18 20:22
Do you have the latest DevTools? This looks like a dupe of https://github.com/flutter/devtools/issues/1960, which was fixed by https://github.com/flutter/devtools/pull/1962?

**Closed** 2024-10-03 21:30 UTC
