### ISSUE TITLE
Reporting error: Error collecting raster stats: _flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame was rendered

### ISSUE THREAD

**Issue by akssay-kamath** [flutter/devtools#7937] opened 2024-06-17 12:00 UTC
Stack trace:
Error
    at Object.qb (http://127.0.0.1:9101/main.dart.js:6162:18)
    at http://127.0.0.1:9101/main.dart.js:160252:5
    at bDe.a (http://127.0.0.1:9101/main.dart.js:4771:62)
    at bDe.$2 (http://127.0.0.1:9101/main.dart.js:56662:14)
    at Object.m (http://127.0.0.1:9101/main.dart.js:4757:10)
    at za.aD0 (http://127.0.0.1:9101/main.dart.js:160266:10)
    at za.cb (http://127.0.0.1:9101/main.dart.js:160245:25)
    at za.jD (http://127.0.0.1:9101/main.dart.js:160230:13)
    at il.jD (http://127.0.0.1:9101/main.dart.js:88612:44)
    at http://127.0.0.1:9101/main.dart.js:100353:14
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.4
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.2.3
Flutter Version: 3.16.5 / stable
Framework / Engine: 78666c8dc5 / 3f3e560236

**Comment by kenzieschmoll** [comment] 2024-06-25 19:18
closing as a duplicate of https://github.com/flutter/devtools/issues/6992

**Closed by kenzieschmoll** 2024-06-25 19:18 UTC
