### ISSUE TITLE
Support filters for logging

### ISSUE THREAD

**Issue by Alby-o** [flutter/devtools#427] opened 2019-03-14 04:02 UTC
Having a filter on the logging page would be really nice to help isolate logs relevant to what I'm debugging!

**Comment by kenzieschmoll** [comment] 2019-07-23 18:37
Duplicate of https://github.com/flutter/devtools/issues/785

**Closed by kenzieschmoll** 2019-07-23 18:37 UTC
Labels: logging page

**Comment by GitHubMurt** [comment] 2019-12-28 11:58
Can't stand that logging spam, Even If I add some logs `developer.log` dartdev tool refresh log list so quickly that i can't find my logs since it allso scroll down automatically to the bottom Its horrible
