### ISSUE TITLE
Make Devtools a desktop app, i.e. compile to linux/windows/macos?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/devtools#5944] opened 2023-06-23 06:16 UTC
It is super slow to use Devtools, especially when the UI is complex, CPU profiler samples are large, etc. From my past experience, an app works smoothly natively while janky on Web. Therefore, is it possible we make it a desktop app? It should not be very hard since we do not need to change Flutter code (mostly).

**Comment by CoderDake** [comment] 2023-06-23 13:10
@fzyzcjy for the most part I think DevTools works on desktop already.
- clone the repo
- change directory to: `packages/devtools_app`
 - you can run `flutter run` for your desktop.

I know I run it on macros all the time, but I've never run it on Windows.
Let me know if that ends up working for you :)

**Comment by fzyzcjy** [comment] 2023-06-23 23:22
@CoderDake Thanks! I will try that later. I am saying whether it can be (one of) default choice, e.g. when I tap "open devtools" it is opened.

**Comment by kenzieschmoll** [comment] 2023-06-26 16:00
Closing as a duplicate of https://github.com/flutter/devtools/issues/2133. @fzyzcjy please feel free to upvote that issue. We use upvotes as a metric for prioritizing the most impactful issues.

**Closed by kenzieschmoll** 2023-06-26 16:00 UTC
