### ISSUE TITLE
Need a tool to detect memory leaks in a flutter app

### ISSUE THREAD

**Issue by a-siva** [flutter/devtools#1437] opened 2019-12-05 00:22 UTC
Here is the original text from @Aaron009 transferred from https://github.com/dart-lang/sdk/issues/39645

========================================================================
I wrote a memory leak code.

import 'package:flutter/material.dart';

```
void main() {
  runApp(MainApp());
}

class MainApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TextMemoryLeak(),
    );
  }
}

class TextMemoryLeak extends StatefulWidget {
  @override
  _TextMemoryLeakState createState() => _TextMemoryLeakState();
}

class _TextMemoryLeakState extends State<TextMemoryLeak> {
  List memoryList = [];

  @override
  Widget build(BuildContext context) {
    Scaffold scaffold = Scaffold(
      appBar: AppBar(
        title: Text('test memory leaks'),
      ),
      body: Center(
        child: Text('${memoryList.length + 1}'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.map),
        onPressed: () {
          setState(() {

          });
        },
      ),
    );

    for (var i = 0; i < 100; ++i) {
      memoryList.add(scaffold); // A memory leak has occurred
      memoryList.add('A' * 1000);
    }
    return scaffold;
  }
}
```
This is a very simple code.

Every time you click on the floatingButton, it will be continuously added to the memoryList without being removed. This is an obvious memory leak.

I once read an article about Flutter checking for memory leaks.
The principle is that the larger the memory size requested by a function, the greater the possibility of a memory leak. (I forgot where I saw it. If anyone knows, please tell me the address of this article.)
I don't like this method because the memory requested by a function is very small, but it is a memory leak and it is difficult to check.

Another way is to use weakly referenced.

The principle is this.

```
var memoryList = [];
memoryList.add('111111');

var weakMap = new WeakMap()
weakMap.set(memoryList, true);

forceGC();
```
// According to the principle, after executing gc, 
// if the memoryList key does not exist in the 
// `WeakMap`, 
// it means that the memoryList has recovered memory normally.
This troubleshooting method is very enjoyable. When I create an object, I make a weak reference to it to store it. When I destroy and force the use of GC, we can check the memory leaked objects through WeakMap.

There are several issues:
**Dart does not have a weak reference. May I ask if there is a launch plan?
Does dart have a similar method to know if the object has been properly recycled?
In addition to the above two methods, is there a better way for Flutter to check for memory leaks?**
I used to develop a game in which a colleague wrote a piece of code with a memory leak and then left. It was too painful when I investigated later.

**Comment by jacob314** [comment] 2019-12-05 00:30
Fyi @terrylucas

**Comment by Aaron009** [comment] 2019-12-05 02:44
@jacob314 @a-siva @terrylucas 
I don't want to do tool checking because I haven't used very effective tools to check for memory leaks so far. I am a developer and have used many analysis tools, but it didn't help much.

I hope to have such a function.

In debug mode, an object is instantiated and then marked as recyclable by code. After GC was enforced, it was found that the object could not be recycled at this time, and an error or prompt was given.

**Comment by sgehrman** [comment] 2020-06-04 10:01
I'm seeing huge memory leaks with websockets.  I can't find any tools that help figure out what's leaking.

**Comment by britannio** [comment] 2020-07-02 20:37
Is something similar to https://github.com/square/leakcanary possible in Dart/Flutter?

**Comment by yuexunshi** [comment] 2020-10-21 11:39
> Is something similar to https://github.com/square/leakcanary possible in Dart/Flutter?

https://flutter.cn/community/tutorials/memory-leak-monitoring-on-flutter

**Comment by yuexunshi** [comment] 2020-10-21 11:41
> Is something similar to https://github.com/square/leakcanary possible in Dart/Flutter?

This is the realization idea, it is not open source, if you have any ideas, please let me know

**Comment by kenzieschmoll** [comment] 2020-12-30 23:49
Once we have functionality to detect a memory leak, we should badge the memory tab with an error when a leak is detected.

**Comment by jacob314** [comment] 2021-01-07 22:07
We can support this using the VM Service. Without the VM Service in the loop Dart's lack of weak reference support would get in the way.

**Comment by polina-c** [comment] 2022-05-21 01:05
Duplicate of https://github.com/flutter/devtools/issues/3951

**Closed** 2022-05-21 01:05 UTC
Labels: enhancement, memory page
