### ISSUE TITLE
Flutter app crashes when DevTools is opened with app in profile mode

### ISSUE THREAD

**Issue by frankvollebregt** [flutter/devtools#2981] opened 2021-05-05 08:58 UTC
When I start my app in profile mode and try to attach DevTools, the Flutter app crashes (causing DevTools to detach). I've ensured my Android Studio plugins are up to date, and recently also updated my Dart SDK.

## Steps to reproduce:
- Create a new Flutter project (Android Studio)
- Build a profile version of the app
- Open the DevTools from the run section
- The crash occurs

## Output
An unimplemented code error occurs when the DevTools open (I do see the UI, but it immediately disconnects due to the crash).

The output in the (verbose) console is as follows:
<details>
<summary>Full console output</summary>

```
[+15306 ms] E/Dart    ( 7921): ../../third_party/dart/runtime/vm/service.cc: 932: error: unimplemented code
[   +1 ms] E/DartVM  ( 7921): version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "android_arm64"
[        ] E/DartVM  ( 7921): pid=7921, thread=7949, isolate_group=main(0x70688fb300), isolate=main(0x70689f4800)
[        ] E/DartVM  ( 7921): isolate_instructions=7007117000, vm_instructions=7007109000
[        ] E/DartVM  ( 7921):   pc 0x000000700c56bc00 fp 0x000000700a8b3920 /data/app/PACKAGE_NAME-2iFlU2wt-WXk4QpR3sPqqQ==/lib/arm64/libflutter.so+0xba9c00
[        ] E/DartVM  ( 7921): -- End of DumpStackTrace
[        ] F/libc    ( 7921): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 7949 (1.ui), pid 7921 (lms.flutter_app)
[ +134 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[   +1 ms] Build fingerprint: 'xiaomi/jasmine/jasmine_sprout:10/QKQ1.190910.002/V11.0.23.0.QDIMIXM:user/release-keys'
[        ] Revision: '0'
[        ] ABI: 'arm64'
[        ] Timestamp: 2021-05-05 10:37:03+0200
[        ] pid: 7921, tid: 7949, name: 1.ui  >>> PACKAGE_NAME <<<
[        ] uid: 10257
[        ] signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
[        ]     x0  0000000000000000  x1  0000000000001f0d  x2  0000000000000006  x3  000000700a8b3890
[        ]     x4  5400000000000000  x5  5400000000000000  x6  5400000000000000  x7  0000000000008054
[        ]     x8  00000000000000f0  x9  627b049ef730b119  x10 0000000000000001  x11 0000000000000000
[        ]     x12 fffffff0fffffbdf  x13 0000000000000002  x14 0000000000000001  x15 5400000000000000
[        ]     x16 00000070f73ce8c0  x17 00000070f73aa900  x18 00000070098ea000  x19 0000000000001ef1
[        ]     x20 0000000000001f0d  x21 00000000ffffffff  x22 00000070689f4800  x23 0000006ff9859c60
[        ]     x24 0000006ff9859c70  x25 0000000000000004  x26 0000006ff98599d0  x27 000000700c5eafd0
[        ]     x28 000000000000002a  x29 000000700a8b3930
[        ]     sp  000000700a8b3870  lr  00000070f735c0c4  pc  00000070f735c0f0
[        ] backtrace:
[        ]       #00 pc 00000000000830f0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: cf739dbc84bcc78f7a1500721bfb3758)
[        ]       #01 pc 00000000009b82a4  /data/app/PACKAGE_NAME-2iFlU2wt-WXk4QpR3sPqqQ==/lib/arm64/libflutter.so (BuildId: a384fc3d2d70db98b7b9656b3ed08f04a9dca581)
[ +653 ms] Service protocol connection closed.
[   +8 ms] Lost connection to device.
[   +6 ms] executing: C:\Users\fvollebregt\AppData\Local\Android\sdk\platform-tools\adb.exe -s 251eca7b forward --list
[  +20 ms] Exit code 0 from: C:\Users\fvollebregt\AppData\Local\Android\sdk\platform-tools\adb.exe -s 251eca7b forward --list
[        ] 251eca7b tcp:64012 tcp:42838
[   +1 ms] executing: C:\Users\fvollebregt\AppData\Local\Android\sdk\platform-tools\adb.exe -s 251eca7b forward --remove tcp:64012
[  +25 ms] "flutter run" took 41.593ms.
[ +160 ms] ensureAnalyticsSent: 154ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0
```
</details>

## Flutter doctor
<details>
<summary>Flutter doctor -v output</summary>

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.928], locale nl-NL)
    • Flutter version 2.0.1 at C:\Users\fvollebregt\flutter
    • Framework revision c5a4b4029c (9 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\fvollebregt\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Mi A2 (mobile) • 251eca7b • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)     • edge     • web-javascript • Microsoft Edge 89.0.774.76

• No issues found!
```
</details>

**Comment by kenzieschmoll** [comment] 2021-05-05 20:32
What version of flutter are you on? @bkonyi just fixed this issue (https://github.com/dart-lang/sdk/commit/60d149d835254cb6e74bb44f35d44186e0dacb5d). Closing this issue as a duplicate of https://github.com/flutter/devtools/issues/2955. Please try upgrading your flutter and let us know if you can still reproduce this issue.

**Closed by kenzieschmoll** 2021-05-05 20:32 UTC

**Comment by Domzak** [comment] 2021-05-05 21:19
having the same issue, any fix?

**Comment by kenzieschmoll** [comment] 2021-05-05 23:24
@bkonyi do you know what the broken versions of flutter are from when this started happening up until your fix? It could be worth including your sdk commit as a cherry pick into flutter stable. We don't want users to be forced into using flutter master just to use devtools.

**Comment by bkonyi** [comment] 2021-05-05 23:28
No idea when it started happening unfortunately. The culprit for the crash described in #2955 had been present for a couple of years, so I'm not sure why we never hit it before. Can we try with some older DevTools versions to see if we can find a version that doesn't crash? We might be able to work around the issue in DevTools if that's the case.

**Comment by bkonyi** [comment] 2021-05-06 17:57
Workaround up for review in https://github.com/flutter/devtools/pull/2986. Looks like this may have been surfaced by https://github.com/flutter/devtools/pull/2931 from a couple of weeks ago.
