### ISSUE TITLE
`DiagnosticableTreeNode` seems opaque in devtools

### ISSUE THREAD

**Issue by llaenowyd** [flutter/devtools#2479] opened 2020-11-01 16:18 UTC
If I click entries in the Logging view I see some additional structured data in the lower half of the screen.

Except these with `kind` `flutter.error` and message `Instance of 'DiagnosticableTreeNode'`

These are all my errors so I'm interested in seeing more detail. I'm looking in devtools since the run output in the IDE has only 
```
════════ Exception caught by widgets library ═════════════
Incorrect use of ParentDataWidget.
═══════════════════════════════════════
════════ Exception caught by rendering library ═════════════
RenderStack object was given an infinite size during layout.
═══════════════════════════════════════
```
i.e. no stack trace at point of the error

Perhaps the problem is my build setting, but I think it's in debug mode and nothing special.

It looks more to me like the `flutter.error` type isn't compatible with the Logging view rendering or some layer in between them.

**Comment by kenzieschmoll** [comment] 2020-11-03 19:23
This seems like a dupe of https://github.com/flutter/devtools/issues/1370. FYI @jacob314

**Closed by kenzieschmoll** 2020-11-03 19:23 UTC
