### ISSUE TITLE
Network Monitor: where do the `InternetAddress(ip-address)` entries come from and why are they repeated so often

### ISSUE THREAD

**Issue by escamoteur** [flutter/devtools#7806] opened 2024-05-23 09:47 UTC
As you can see here
![grafik](https://github.com/flutter/devtools/assets/16635729/d38c0761-f152-4360-9c84-0005b8ec87d5)
There are a lot of these `InternetAddress` requests and many to the same IP address repeatedly. 
I don't know if they were always shown or if that is due to a change in the devtools recently. 
I would like to know which part of the code is responsible for them, why they are repeated, and if that can be avoided.

**Comment by stan-at-work** [comment] 2024-07-05 07:37
Yea, this is spaming the view and useless

**Comment by kenzieschmoll** [comment] 2024-07-09 21:57
@escamoteur can you please provide a minimal code sample that we can reproduce this issue with? This will make it easier for us to repro the behavior you are seeing and work on a fix. Thanks.

**Comment by escamoteur** [comment] 2024-07-11 11:14
actually this is the same problem as https://github.com/flutter/devtools/issues/3033

**Comment by kenzieschmoll** [comment] 2024-07-12 20:31
closing as a duplicate of https://github.com/flutter/devtools/issues/3033

**Closed by kenzieschmoll** 2024-07-12 20:31 UTC
Labels: bug, network page, P1
