### ISSUE TITLE
DEvTools is not letting me copy and paste from the network console

### ISSUE THREAD

**Issue by Isveth** [flutter/devtools#5276] opened 2023-02-20 23:41 UTC
I can't copy text from the network console, not even using de 3 dots in the right corner of the first panel, and selecting 'copy as curl, is not working :(
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.18.6
Flutter Version: 3.3.10 / stable
![image](https://user-images.githubusercontent.com/88938082/220213597-bc3cbaac-3dca-4c37-b9c4-fd132ee39ee8.png)

Framework / Engine: 135454af32 / 3316dd8728
Connected app type: Flutter native (debug build)

**Comment by julemand101** [comment] 2023-02-21 09:49
Sounds like a duplicate of: https://github.com/flutter/devtools/issues/5031

And related to: https://github.com/flutter/devtools/issues/5130

**Comment by kenzieschmoll** [comment] 2023-02-21 17:48
@CoderDake

**Comment by CoderDake** [comment] 2023-02-24 01:54
@Isveth I haven't been able to reproduce the issue with copying url and curl.
I've tried copying urls on requests that respond with 200, 404, and 500.

Is this something that is happening on all requests for you? Or is this perhaps something that only happens on certain requests?

**Comment by B-sirius** [comment] 2023-02-28 02:23
Same problem here, happening to all requests, even in different projects.

**Comment by CoderDake** [comment] 2023-02-28 17:03
I've been noticing some odd behaviour with other copy buttons when using VScode, I'll take a look into this.

**Comment by kenzieschmoll** [comment] 2023-05-26 22:23
Closing as a duplicate of https://github.com/flutter/devtools/issues/5775

**Closed by kenzieschmoll** 2023-05-26 22:23 UTC
Labels: network page
