### ISSUE TITLE
DevTools problem:  an infinite loop problem freezes the app

### ISSUE THREAD

**Issue by benedicte69** [flutter/devtools#2876] opened 2021-04-08 19:19 UTC
![devtoollllllllllllllllll](https://user-images.githubusercontent.com/19499129/114082760-6cade800-98ae-11eb-9057-cf7a2f8e4de5.PNG)

DevTools does no longer work, it freeze the app at that step when trying to connect:

{"event":"app.started","params":{"appId":"7cce3816-01c7-414d-88d2-b4c66aa9e919"}}]
[{"id":0,"result":{"value":"android","type":"_extensionType","method":"ext.flutter.platformOverride"}}]
[{"id":1,"result":{"timeDilation":"1.0","type":"_extensionType","method":"ext.flutter.timeDilation"}}]
[{"id":2,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaint"}}]
[{"id":3,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaintBaselinesEnabled"}}]
[{"id":4,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.repaintRainbow"}}]
[{"id":5,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.showPerformanceOverlay"}}]
[{"id":6,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.debugAllowBanner"}}]
[{"id":7,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":8,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.show"}}]
[{"id":9,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":10,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
[{"id":11,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":12,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":13,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]

It does not open the link!

An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:61814/UNYPG_eq9Qg=/
The Flutter DevTools debugger and profiler on sdk gphone x86 is available at:
http://127.0.0.1:9108?uri=http%3A%2F%2F127.0.0.1%3A61814%2FUNYPG_eq9Qg%3D%2F

It does not open the link!

the loading goes on and on

Could you help?

**Comment by kenzieschmoll** [comment] 2021-04-08 19:28
If you open up Chrome DevTools, do you see any errors in the console?

**Comment by benedicte69** [comment] 2021-04-08 19:39
@kenvandine 
![chrome](https://user-images.githubusercontent.com/19499129/114086179-9c5eef00-98b2-11eb-9f4d-afc47a6691cb.PNG)

Microsoft Windows [version 10.0.19042.906]
(c) Microsoft Corporation. Tous droits réservés.

C:\xxxxxxx>flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             17,9s
This app is linked to the debug service: ws://127.0.0.1:61257/nEx2mkloWfg=/ws
Debug service listening on ws://127.0.0.1:61257/nEx2mkloWfg=/ws

 Running with sound null safety 

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

**Comment by benedicte69** [comment] 2021-04-08 19:41
There is no error message

**Comment by benedicte69** [comment] 2021-04-08 19:49
But in verbose (in Chrome) there is a story of violation? What is that?
![verbose](https://user-images.githubusercontent.com/19499129/114087567-573bbc80-98b4-11eb-9b2d-9d7999ca8378.PNG)

**Comment by benedicte69** [comment] 2021-04-08 19:51
@kenzieschmoll 

Do you need anything else?

**Comment by benedicte69** [comment] 2021-04-08 19:56
because it is not an error
![nn](https://user-images.githubusercontent.com/19499129/114088463-55bec400-98b5-11eb-918a-e0600559dec1.PNG)

**Comment by kenzieschmoll** [comment] 2021-04-08 20:07
Can you open Chrome DevTools on the DevTools app and see if there are errors there?

**Comment by benedicte69** [comment] 2021-04-08 20:25
I do not understand your request

Do you want me to run the following
flutter pub global activate devtools
flutter pub global run devtools

or do I simply click on:
![aba](https://user-images.githubusercontent.com/19499129/114091738-535e6900-98b9-11eb-80ff-a30d2df7121e.PNG)

**Comment by benedicte69** [comment] 2021-04-08 20:41
meanwhile, Edge is indicating those 'warmings', I do not know if it does matter:
![edge](https://user-images.githubusercontent.com/19499129/114093509-7d188f80-98bb-11eb-84ec-6e3f8f29e0d6.PNG)

**Comment by benedicte69** [comment] 2021-04-08 20:49
So let's come back to Chrome and or simulator,

Do I run  in Android Studio terminal/or in Windows cmd (cd the app of course)   flutter pub global run devtools?
Or do I simply click the DevTool button ?
But be aware that the result will freezes the app as said at the beginning of this post

Please give me a clear instruction while I am still online if it can help but really I do not have control over this infinite loop, it must be somewhere in your code not in mine :)

**Comment by bkonyi** [comment] 2021-04-08 20:52
I believe @kenzieschmoll is asking for the console output from the DevTools application, not the console for your web application.

Also, would you mind sharing your `flutter version` output?

**Comment by benedicte69** [comment] 2021-04-08 21:12
C:\WINDOWS\system32>flutter --version
Flutter 2.1.0-13.0.pre.464 • channel master • https://github.com/flutter/flutter.git
Framework • revision aa902101bf (3 days ago) • 2021-04-05 18:49:01 -0400
Engine • revision 95913801a5
Tools • Dart 2.13.0 (build 2.13.0-203.0.dev)

C:\Windows\System32>

N.B: as far as channels are concerned I tested in the stable, it was doing the same

**Comment by benedicte69** [comment] 2021-04-08 21:31
@bkonyi  @kenzieschmoll 

I hope that among those few pieces of information you will find something. me I understand nothing except the fact that an infinite loop is blocking DevTools. If you need anything else, tell me. I will have a look at your request **tomorrow**. Thanks

**Comment by kenzieschmoll** [comment] 2021-04-08 23:17
I am asking from this point:
![image](https://user-images.githubusercontent.com/43759233/114107356-b0402c00-9885-11eb-98e1-d60200d5cc5e.png)
that you right click on the black screen -> inspect (to open Chrome DevTools) -> then navigate to the Console tab in Chrome DevTools

This will allow us to see if the DevTools web application itself is outputting any errors or exceptions

**Comment by benedicte69** [comment] 2021-04-09 11:41
![kkkkk](https://user-images.githubusercontent.com/19499129/114174720-497c4a80-9939-11eb-8d9a-78836c293955.PNG)

**Comment by benedicte69** [comment] 2021-04-09 11:44
![palette ](https://user-images.githubusercontent.com/19499129/114174933-a4ae3d00-9939-11eb-9e3a-bf576fe1b307.PNG)

**Comment by benedicte69** [comment] 2021-04-09 11:44
![palette ](https://user-images.githubusercontent.com/19499129/114174945-a972f100-9939-11eb-8996-552a481c7aff.PNG)

**Comment by benedicte69** [comment] 2021-04-09 11:44
![errrr](https://user-images.githubusercontent.com/19499129/114174969-b263c280-9939-11eb-9593-c9aae0fb03a7.PNG)

**Comment by benedicte69** [comment] 2021-04-09 11:55
@kenzieschmoll  
I have at least understood your request, anything else? I am a bit out this afternoon (french time) so do not worry if I do not answer immediately.
I hope you will find a solution

**Comment by jacob314** [comment] 2021-04-09 15:27
@benedicte69 does the problem reproduce if you create a new Flutter project or is it only for a specific Flutter application?
To double check, are you only seeing the issue when you run your application with Flutter web or are you seeing it when you run Flutter on all platforms?

Thanks,
Jacob

**Comment by benedicte69** [comment] 2021-04-09 18:13
@jacob314 

in any circumstance whatever is the app

**Comment by jacob314** [comment] 2021-04-09 18:18
I believe this is a dupe of https://github.com/flutter/flutter/issues/79498
Please try syncing to the very latest Flutter and let us know if the issue still occurs.

**Comment by benedicte69** [comment] 2021-04-09 18:45
@jacob314 

**WOUAHOU  97 commits in 3 days, what a great job!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

Flutter 2.1.0-13.0.pre.561 • channel master • https://github.com/flutter/flutter.git
Framework • revision e2dc794199 (28 minutes ago) • 2021-04-09 14:04:02 -0400
Engine • revision a9f4883dc8
Tools • Dart 2.13.0 (build 2.13.0-219.0.dev)

Here we are 👍 


![96update](https://user-images.githubusercontent.com/19499129/114226749-4783ad00-9974-11eb-8ba0-603b2296f66d.PNG)

thank you so much!

**Comment by jacob314** [comment] 2021-04-09 18:47
Thanks! Glad it is working now.

**Closed by jacob314** 2021-04-09 18:47 UTC
Labels: waiting for customer response
