### ISSUE TITLE
Scrolling not working in alpha version of dart dev tools

### ISSUE THREAD

**Issue by saurabhguptarock** [flutter/devtools#1955] opened 2020-05-13 06:45 UTC
While scrolling with scroll wheel in the flutter inspector tab.
It does not scroll down correctly instead it flickers between horizontal scrolling and vertical scrolling

**Comment by kenzieschmoll** [comment] 2020-05-13 15:34
Thanks for the report. Duplicate of https://github.com/flutter/devtools/issues/1709.

**Closed by kenzieschmoll** 2020-05-13 15:34 UTC
