### ISSUE TITLE
P2: [devtools_app] Make the "Import File" button works.

### ISSUE THREAD

**Issue by tugorez** [flutter/devtools#2505] opened 2020-11-16 23:34 UTC
![image](https://user-images.githubusercontent.com/7821057/99320677-c8110800-2831-11eb-9a7e-8322e47dec84.png)

**Comment by tugorez** [comment] 2020-11-16 23:35
I will start writing the PR once https://github.com/flutter/plugins/pull/3140 is merged.

**Comment by kenzieschmoll** [comment] 2020-12-09 20:52
closing as a dupe of https://github.com/flutter/devtools/issues/2149

**Closed by kenzieschmoll** 2020-12-09 20:52 UTC
