### ISSUE TITLE
Unable to use dev-tools (No tabs available for this application)

### ISSUE THREAD

**Issue by Airfant** [flutter/devtools#3314] opened 2021-08-30 10:21 UTC
Hi, I followed the dev-tools user guide step by step to the end, I got the URL and ran my flutter program, but the website showed: No tabs available for this application. I guess this is a problem with the symbol table, but I checked it and there is a symbol table. Does anyone know the reason for this?
![img_b4a7c99b-bb6f-4fe8-a383-8bfe0bf27bcl](https://user-images.githubusercontent.com/89775814/131325023-96facd27-8954-485d-b702-01593b5a288b.png)

**Comment by Airfant** [comment] 2021-08-31 02:17
> Sorry to hear this. Can you provide more details on which guide you were following and what kind of Flutter application you were running? Your version of the Flutter SDK would also be helpful.
> Thanks,
> Jacob

Hi, Jacob! Thank you for your reply. I am following the guide on this website: https://flutter.dev/docs/development/tools/devtools/cli

According to the guide, after running the dev-tools, I got the URL something like http://127.0.0.1:9100. Then after running the Flutter application (I am sorry, our project is confidential, so I can't give you more details  about our flutter application), I got the URL something like http://127.0.0.1:50976/Swm0bjIe0ks=/ ,and I enter this URL on the website http://127.0.0.1:9100 then click "connect". The website shows that the connection is successful, but an error is reported: No tabs available for this application

BTY, The version information is like this:
![Screenshot from 2021-08-31 09-54-58](https://user-images.githubusercontent.com/89775814/131430630-aefb16ee-d740-44a7-a7f7-5f92ce5a96d4.png)

I am looking forward to your reply, thanks!

**Comment by makesimple** [comment] 2021-08-31 06:04
I had the same issues too,some months ago ,it works correctly,I don't upgrade the flutter framework,but now i had the same issues as Airfnt,I don't why.here is the information generated by 'flutter --version' for me:
Building flutter tool...
Flutter 2.0.3 • channel unknown • unknown source
Framework • revision 4d7946a68d (6 months ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

**Comment by makesimple** [comment] 2021-08-31 06:11
> Sorry to hear this. Can you provide more details on which guide you were following and what kind of Flutter application you were running? Your version of the Flutter SDK would also be helpful.
> Thanks,
> Jacob

I had the same issues too,some months ago ,it works correctly,I don't upgrade the flutter framework,but now i had the same issues as Airfnt,I don't know why.here is the information generated by 'flutter --version' for me:
Flutter 2.0.3 • channel unknown • unknown source
Framework • revision 4d7946a68d (6 months ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

xxx$: dart pub global activate devtools
Resolving dependencies... (2.0s)

args 2.2.0
async 2.8.2
browser_launcher 1.0.0
charcode 1.3.1
clock 1.1.0
collection 1.15.0
convert 3.0.1
devtools 2.5.0
devtools_server 2.5.0
devtools_shared 2.5.0
http 0.13.3
http_multi_server 3.0.1
http_parser 4.0.0
intl 0.17.0
logging 1.0.1
meta 1.7.0
mime 1.0.0
path 1.8.0
pedantic 1.11.1
pool 1.5.0
shelf 1.2.0
shelf_proxy 1.0.0
shelf_static 1.1.0
source_span 1.8.1
sse 4.1.0
stack_trace 1.10.0
stream_channel 2.1.0
string_scanner 1.1.0
term_glyph 1.2.0
typed_data 1.3.0
usage 4.0.2
vm_service 7.2.0
webkit_inspection_protocol 1.0.0
Precompiling executables... (1.8s)
Precompiled devtools:devtools.
Installed executable devtools.
Activated devtools 2.5.0.
Is the higher version of the devtools cause the problem?
if it is,how to downgrade the version of the devtools?

**Comment by makesimple** [comment] 2021-08-31 11:09
> > Sorry to hear this. Can you provide more details on which guide you were following and what kind of Flutter application you were running? Your version of the Flutter SDK would also be helpful.
> > Thanks,
> > Jacob
> 
> Hi, Jacob! Thank you for your reply. I am following the guide on this website: https://flutter.dev/docs/development/tools/devtools/cli
> 
> According to the guide, after running the dev-tools, I got the URL something like http://127.0.0.1:9100. Then after running the Flutter application (I am sorry, our project is confidential, so I can't give you more details about our flutter application), I got the URL something like http://127.0.0.1:50976/Swm0bjIe0ks=/ ,and I enter this URL on the website http://127.0.0.1:9100 then click "connect". The website shows that the connection is successful, but an error is reported: No tabs available for this application
> 
> BTY, The version information is like this:
> Flutter 2.0.4-0.0.pre.1
> 
> I am looking forward to your reply, thanks!

Maybe I had found the root cause,it's your version doesn't match flutter engine, you can try this downgrade devtools's version:
flutter pub global activate devtools xxx.yyy.zzz
the xxx.yyy.zzz available version can be found:
https://pub.dev/packages/devtools/changelog

**Comment by Airfant** [comment] 2021-09-01 02:29
> > > Sorry to hear this. Can you provide more details on which guide you were following and what kind of Flutter application you were running? Your version of the Flutter SDK would also be helpful.
> > > Thanks,
> > > Jacob
> > 
> > 
> > Hi, Jacob! Thank you for your reply. I am following the guide on this website: https://flutter.dev/docs/development/tools/devtools/cli
> > According to the guide, after running the dev-tools, I got the URL something like http://127.0.0.1:9100. Then after running the Flutter application (I am sorry, our project is confidential, so I can't give you more details about our flutter application), I got the URL something like http://127.0.0.1:50976/Swm0bjIe0ks=/ ,and I enter this URL on the website http://127.0.0.1:9100 then click "connect". The website shows that the connection is successful, but an error is reported: No tabs available for this application
> > BTY, The version information is like this:
> > Flutter 2.0.4-0.0.pre.1
> > I am looking forward to your reply, thanks!
> 
> Maybe I had found the root cause that had worked for me,it's your version doesn't match flutter engine, you can try this downgrade devtools's version:
> flutter pub global activate devtools xxx.yyy.zzz
> the xxx.yyy.zzz available version can be found:
> https://pub.dev/packages/devtools/changelog

thanks a lot makesimple, so which devtools's version works for you?

**Comment by makesimple** [comment] 2021-09-01 02:36
> > > > Sorry to hear this. Can you provide more details on which guide you were following and what kind of Flutter application you were running? Your version of the Flutter SDK would also be helpful.
> > > > Thanks,
> > > > Jacob
> > > 
> > > 
> > > Hi, Jacob! Thank you for your reply. I am following the guide on this website: https://flutter.dev/docs/development/tools/devtools/cli
> > > According to the guide, after running the dev-tools, I got the URL something like http://127.0.0.1:9100. Then after running the Flutter application (I am sorry, our project is confidential, so I can't give you more details about our flutter application), I got the URL something like http://127.0.0.1:50976/Swm0bjIe0ks=/ ,and I enter this URL on the website http://127.0.0.1:9100 then click "connect". The website shows that the connection is successful, but an error is reported: No tabs available for this application
> > > BTY, The version information is like this:
> > > Flutter 2.0.4-0.0.pre.1
> > > I am looking forward to your reply, thanks!
> > 
> > 
> > Maybe I had found the root cause that had worked for me,it's your version doesn't match flutter engine, you can try this downgrade devtools's version:
> > flutter pub global activate devtools xxx.yyy.zzz
> > the xxx.yyy.zzz available version can be found:
> > https://pub.dev/packages/devtools/changelog
> 
> thanks a lot makesimple, so which devtools's version works for you?
I just test three versions,all are ok
2.4.0
2.3.3
2.3.2

**Closed** 2023-05-31 00:38 UTC
Labels: waiting for customer response
