### ISSUE TITLE
Give us the ability to keep devtools open even after the app disconnected

### ISSUE THREAD

**Issue by feinstein** [flutter/devtools#6960] opened 2023-12-13 23:53 UTC
I am debugging a dart CLI app, and I send an HTTP request as the last step my CLI takes. I can't check the networking traffic data in devools, because it closes as soon as my CLI closes.

It would be better if devtools let me know the app disconnected (as it does), but also provides me the option to stay disconnected so I can check all the data that has been gathered so far for that old session.

**Comment by kenzieschmoll** [comment] 2024-07-17 21:31
Closing as a duplicate of https://github.com/flutter/devtools/issues/4470, which is the meta tracking issue for supporting offline support for more DevTools screens

**Closed** 2024-07-17 21:31 UTC
Labels: offline, network page
