### ISSUE TITLE
How to open it on chrome/firefox?

### ISSUE THREAD

**Issue by dmvvilela** [flutter/devtools#2488] opened 2020-11-04 11:21 UTC
I used it on chrome when it started out. But now it is opening on VS Code..

There is no room to use it on VS Code!! I need this opened on my browser but i can't find how to do it..

How can i do it? (and possibly make it default)

Thanks.

**Comment by kenzieschmoll** [comment] 2020-11-04 17:06
CC @DanTup 

You can select "Open DevTools in web browser" to accomplish this:
<img width="194" alt="Screen Shot 2020-11-04 at 9 03 49 AM" src="https://user-images.githubusercontent.com/43759233/98142576-d3048980-1e7c-11eb-9a30-67939a2b416f.png">
<img width="330" alt="Screen Shot 2020-11-04 at 9 04 16 AM" src="https://user-images.githubusercontent.com/43759233/98142589-d4ce4d00-1e7c-11eb-90dc-010d6eabd0de.png">

Note: there is a known issue (one that will be resolved in the next release) where the embedded devtools (the one opened inside VsCode) needs to be closed in order for the "Open DevTools in web browser" option to work as intended.

**Closed by kenzieschmoll** 2020-11-04 17:06 UTC

**Comment by DanTup** [comment] 2020-11-04 17:10
You can also change this VS Code setting if you want to always launch in the browser:

<img width="704" alt="Screenshot 2020-11-04 at 17 09 39" src="https://user-images.githubusercontent.com/1078012/98143076-9064a080-1ec0-11eb-9b70-c649cc28ec4b.png">

And if you want to change from Chrome to your default browser, this setting:

<img width="828" alt="Screenshot 2020-11-04 at 17 10 15" src="https://user-images.githubusercontent.com/1078012/98143134-a07c8000-1ec0-11eb-8749-68e09bee0444.png">
