### ISSUE TITLE
[Feature] DevTools should be 3rd party extensible, with custom tools and data

### ISSUE THREAD

**Issue by chipweinberger** [flutter/devtools#5698] opened 2023-04-22 18:53 UTC
![image](https://user-images.githubusercontent.com/1863934/233801738-7d19a79f-b018-4615-8828-ab1017faa74b.jpeg)

DevTools should support custom data and logic. For example:

- inspect state of my internal app database
- run custom debug commands in my app, and see their results
- show a command line interface for my app 

Of course, this code would be highly custom to my app, and can only be achieved if DevTools is extensible by 3rd parties

**Motivation (Versus In-App Debug Panel)**:
- dev tools offers lots of screen realestate
- dev tools has already solved the problem of getting custom data off the phone over the lightning cable

**Comment by kenzieschmoll** [comment] 2023-05-26 21:16
Closing as a duplicate of https://github.com/flutter/devtools/issues/1632. You can follow along there for updates to the DevTools plugin framework that is under design.

**Closed by kenzieschmoll** 2023-05-26 21:16 UTC

**Comment by chipweinberger** [comment] 2023-05-26 21:59
Thanks @kenzieschmoll ! =)
