### ISSUE TITLE
Set up a way to run devtools_server with debug/DDC version of devtools for local development

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#1036] opened 2019-09-11 08:53 UTC
Currently we'll only connect to the server for release builds where we know the server is serving:

https://github.com/flutter/devtools/pull/987#pullrequestreview-286518143

**Comment by kenzieschmoll** [comment] 2022-07-01 23:36
Polishing / normalizing this workflow would be a velocity improvement.

**Comment by kenzieschmoll** [comment] 2024-10-03 22:07
closing as a duplicate of https://github.com/flutter/devtools/issues/6486

**Closed by kenzieschmoll** 2024-10-03 22:07 UTC
Labels: enhancement, hurts-developer-velocity
