### ISSUE TITLE
Devtools cached overly aggressively

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1674] opened 2020-02-26 18:14 UTC
Repro steps:
```
$ pub global activate devtools 0.1.13
$ pub global run devtools -p 1234
Access http://127.0.0.1:1234/ and confirm the the UI works and "DevTools version 0.1.13." is shown in the console

$ pub global activate devtools 0.1.15
$ pub global run devtools -p 1234
Access http://127.0.0.1:1234/, observe "Loading..." label stuck on the screen. "DevTools version 0.1.13." is shown in the console.
```
Apparently main.dart.js gets cached persistently and survives version upgrades/downgrades and gets into weird states due to version mismatches between different files/ajax APIs.

Suggested fix:
adding a cache busting query parameter to main.dart.js or changing our server configuration.

**Comment by devoncarew** [comment] 2020-07-29 18:29
Bumping this to the following milestone, but do people have ideas for how to address this?

I'd made some changes to the cache control headers in our devtools server (https://github.com/flutter/devtools/pull/1993), but either those didn't take effect or it wasn't a complete solution.

**Comment by jacob314** [comment] 2020-07-30 17:48
Let me try reducing the cache time from 300s to 0s. Currently you can get caching issues for the 300s while the data is still cached. The service worker added for flutter web may also be able to help mitigate any performance impact from reducing caching from 300s to 0s.

**Comment by kenzieschmoll** [comment] 2020-09-03 22:05
Is this issue still happening?

**Comment by DanTup** [comment] 2020-10-21 09:21
I think there are still some caching issues - I was just testing a release build locally and got errors for 404s on "widget.json". I couldn't find any references in the code (was removed in https://github.com/flutter/devtools/pull/2433/files). Reloading the page made no difference, but clicking the "Clear site data" button in Chrome devtools -> Application seems to have fixed it. In hindsight I should've checked where the widgets.json reference was before fixing it, since I'm not sure exactly what may have been cached for this to occur.

**Comment by kenzieschmoll** [comment] 2020-10-21 16:02
I'm also still seeing caching issues. Sometimes a hard refresh won't even fix it. I've been opening DevTools in an incognito window to work around it.

**Comment by DanTup** [comment] 2020-10-21 16:39
Yep, that's what I saw - though this button seems to fix it:

![Screenshot 2020-10-21 at 17 37 50](https://user-images.githubusercontent.com/1078012/96750751-3e058900-13c4-11eb-946d-12b5b67d2c8c.png)

That unregisters service workers, and I noticed there's a lot of caching stuff in the Flutter service worker - though I'm not sure if that's the cause.

**Comment by DanTup** [comment] 2021-01-05 12:36
I just saw this in the VS Code embedded view. I had previously `pub global activate`'d the local version (0.9.6) for testing, then reverted to the Pub version (0.9.5+2), but VS Code always loaded 0.9.6 still.

The network page in the Chrome devtools in VS Code showed that the request to `main.dart.js` was being served by the service worker with a 200 status, but it was the cached content from 0.9.6 (it's easy to tell this as DevTools showed this version at the bottom of the page). Opening DevTools outside of VS Code was fine. I tried many things to fix it (including having VS Code include a random timestamp on the URL it loaded - that didn't work because it wasn't that page that was cached, it was the JS file that was being loaded within). In the end, unregistering the Flutter service worker within VS Code (Chrome) devtools was the only thing that worked (this is awkward for most users to do).

I'm not sure how the service worker decides how to cache, though I wonder if it's needed it for DevTools running locally - could DevTools be built without it? Or could the DevTools version number be injected into the `main.dart.js` reference on a query string to force a fresh version on each release of DevTools?

I expect with the next release, users may see the issue I saw today, which is errors like not being able to find the a page - it looks like VS Code is passing the wrong page ID, but it's actually because the version VS Code gets from `pub global list` doesn't match the JavaScript that ends up running due to the cache.

**Comment by devoncarew** [comment] 2021-01-05 16:10
Do we need the service worker for DevTools? Is it just a performance optimization for web apps? We'd always be running locally for the user - the cost of downloading the content will be negligable.

**Comment by DanTup** [comment] 2021-01-05 16:22
> Is it just a performance optimization for web apps?

I'm not certain. It seems like it's just doing caching and offline support (and therefore probably isn't required), but I'm basing that on scanning some commits and GH issues.

I'm also unsure if this is working as intended, or there is something wrong and it could cause issues for other apps too. I think this is the source that's using the cache, but I can't find where things are expired/updated:

https://github.com/flutter/flutter/blob/5f496547346b0b0e63d7a5e153bd254e8b364858/packages/flutter_tools/lib/src/build_system/targets/web.dart#L512

@jonahwilliams looks like you're worked on this, so maybe you have some ideas. What's the mechanism that should prevent the service worker serving stale items? Is it possible it was the service worker itself that was stale?

**Comment by kenzieschmoll** [comment] 2022-07-01 23:25
closing in favor of https://github.com/flutter/devtools/issues/3896

**Closed** 2022-07-01 23:25 UTC
Labels: bug, g3
