### ISSUE TITLE
devtools show "No tabs available for this application"

### ISSUE THREAD

**Issue by TangLei96** [flutter/devtools#4967] opened 2022-12-19 08:24 UTC
DevTools version: 2.12.2
Connected Device:
CPU / OS: arm64-64/linux
Dart Version: 2.16.6
Flutter Version: 3.0.5 / stable
Connected app type: Flutter native (profile build)

I have an embedded device,and i want to use devtools to analysis my application. I use adb forward to connect PC and my embedded device. it works. but the devtools display **No tabs available for this application**,i don't know why.

**Comment by kenzieschmoll** [comment] 2023-05-26 22:49
closing as duplicate of https://github.com/flutter/devtools/issues/4964

**Closed by kenzieschmoll** 2023-05-26 22:49 UTC
