### ISSUE TITLE
Line number incorrectly aligned when the first source is displayed

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#877] opened 2019-08-05 19:33 UTC
This happens every time I first launch Dart Devtools and select the debugging tab:
<img width="891" alt="Screen Shot 2019-08-05 at 12 31 48 PM" src="https://user-images.githubusercontent.com/1840773/62490028-32a54e00-b77d-11e9-8c47-8308bab6c6e9.png">
Once I navigate to another source the alignment is fixed.

**Comment by grouma** [comment] 2019-08-05 19:54
Looks like this issue is the result of having a file with less than double digit lines.

**Comment by kenzieschmoll** [comment] 2019-08-05 22:35
Dupe of https://github.com/flutter/devtools/issues/808

**Closed by kenzieschmoll** 2019-08-05 22:35 UTC
