### ISSUE TITLE
Not able to see the https requests

### ISSUE THREAD

**Issue by naninydhruva** [flutter/devtools#8376] opened 2024-09-30 09:40 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.0
Flutter Version: 3.24.0 / stable
Framework / Engine: 80c2e84975 / b8800d88be

Hi team,

I am not able to see any https request in the network just getting the web scoket requests after the latest flitter upgrade.

**Comment by elliette** [comment] 2024-10-03 21:17
Hi @naninydhruva! Do you mind sharing a small repro as well as sharing the package you are using to send the requests? Thank you!

**Comment by naninydhruva** [comment] 2024-10-04 11:15
Hi @elliette , I am using dio :^5.7.0 version for sending the requests

**Comment by Adrek** [comment] 2024-10-11 22:14
same problem with flutter 3.24.3, dart 3.5.3, devtools 2.37.3 and dio 5.7.0

**Comment by zhhal** [comment] 2024-10-12 04:17
The same issue, all GET requests have turned into SOCKET.

**Comment by LiamMarega** [comment] 2024-10-23 18:39
same issue with   dio: ^5.5.0 but only with a physical device, if I am use android emulator works well

`    • Flutter version 3.24.3 on channel stable at C:\Users\Liam\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    `

**Comment by saeedprogrammer** [comment] 2024-10-30 13:55
same issue with dio
![Screenshot 2024-10-31 at 4 54 11 AM](https://github.com/user-attachments/assets/6cc1f7ac-4b1e-40c2-8ce9-963b7a5321fb)

Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (6 days ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

**Comment by kenzieschmoll** [comment] 2024-11-19 21:37
closing as a duplicate of https://github.com/flutter/devtools/issues/8380

**Closed by kenzieschmoll** 2024-11-19 21:37 UTC
Labels: screen: network, P2
