### ISSUE TITLE
Debugger's inspectors are missing fields for most types

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/devtools#4756] opened 2022-11-15 21:38 UTC
* Lists, Maps and Sets are missing their type arguments (i.e., can only tell it's a List, not a `List<String>`)
 * Capabilities and SendPorts are missing their swiss numbers
 * Closures are missing the function, context, and type arguments
 * Function types are missing their return type, parameter types, and type arguments (i.e., only see `_FunctionType` instead of `bool (int, int)`
 * Records are missing their elements
 * Regex are missing their pattern
 * Fails to load entirely for uninitialized late fields
 * Types are missing their type class and type arguments (i.e., only see `_Type` instead of `List<String>`)
 * [unmodifiable] typed data view display neither the logical elements or the underlying buffer the view references
 * UserTags are missing their name
 * WeakProperties are missing their keys and values
 * WeakReferences and MirrorReferences are missing their target

**Comment by bkonyi** [comment] 2022-11-24 16:38
This should be mostly covered by https://github.com/flutter/devtools/pull/4760, although formatting could be refined.

**Comment by bkonyi** [comment] 2022-12-14 15:58
Duplicate of https://github.com/flutter/devtools/issues/4756, which we'll use for tracking this issue.

**Closed by bkonyi** 2022-12-14 15:58 UTC
Labels: debugger page, missing core functionality
