### ISSUE TITLE
Frames chart not showing in Timeline view

### ISSUE THREAD

**Issue by bnayagrawal** [flutter/devtools#2134] opened 2020-06-27 06:04 UTC
I launched my app in **profile mode** in **Android Studio** by clicking on the **toolbar profile icon**. In the **Flutter performance** side pane I was able to see the **frame times** and there was a **link** to open the **DevTool**. I clicked on the **DevTool** link, it launched the **DevTool** in my default **browser window**, from there I clicked on the **Timeline** tab to view **frames chart** but only the empty **timeline view** was there and **frames chart** was missing. Am I missing something here?
 
Below is the **console output**
```Launching lib\main.dart on ONEPLUS A6010 in profile mode...
Running Gradle task 'assembleProfile'...
√ Built build\app\outputs\apk\profile\app-profile.apk (16.1MB).
Debug service listening on ws://127.0.0.1:54343/m9dv97gI8Vs=/ws
```
When I run the app in **debug** mode, In the **DevTools** in **TImeline** view I was able to see the empty **frames chart** view and with an **error message** on top saying I need to run the application in **profile mode**. 

Tested on
-----------
**DevTools** version: 0.8.0
**Android Studio** version: 3.6.2

Below is the output generated by the **flutter doctor -v** command
```
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.19041.329], locale en-IN)
    • Flutter version 1.17.4 at C:\flutter
    • Framework revision 1ad9baa8b9 (9 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\BnayA\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\BnayA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • ONEPLUS A6010 • 192.168.43.144:5555 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by kenzieschmoll** [comment] 2020-08-17 17:05
Are you still seeing this issue with the latest version of DevTools? What happens when you click "refresh" in the Timeline page? Are there any errors in the Chrome dev console?

**Comment by kenzieschmoll** [comment] 2020-09-03 21:59
closing, as I am unable to reproduce and need further information. Feel free to re-open if you are still seeing this issue

**Closed by kenzieschmoll** 2020-09-03 21:59 UTC
Labels: bug, timeline page
