### ISSUE TITLE
Custom devtool extensions not available while debugging integration tests

### ISSUE THREAD

**Issue by Andrei7506238** [flutter/devtools#7841] opened 2024-05-22 17:04 UTC
### Steps to reproduce

1. In default flutter counter app add integration_test and a package providing a devtool custom extension (ex: provider)
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  provider: ^6.1.2
```

2. Add folder integration_test to the project root and create an integration test:
![image](https://github.com/flutter/flutter/assets/52383534/da6b13d3-2152-4036-82e5-7a7a02d2be95)

```dart
import 'package:area_chart_redesign/main.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const MyApp());

    // Verify that our counter starts at 0.
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    // Tap the '+' icon and trigger a frame.
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    // Verify that our counter has incremented.
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}
```

3. Debug widget_test. Put breakpoint on     await tester.pumpWidget(const MyApp());. When it hits the breakpoint open DevTools in WebBrowser

### Expected results

The devtools provided by the packages should show up in separate tabs (like in the first image provided below. The first screenshot is made when I started debug for lib/main.dart). 

### Actual results

The tabs related to the custom devtools extensions are not shown. Also the extensions can't be found in the "DevTools Extensions tab". See 2nd image below.

### Code sample

No relevant piece of code. I used the default starter flutter project (counter app). See "Steps to reproduce"

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![chrome_8KSCo6T4QV](https://github.com/flutter/flutter/assets/52383534/50255a72-4a9e-4009-96f0-411d2036e890)
![chrome_9hZR3wS0b3](https://github.com/flutter/flutter/assets/52383534/06904de8-1669-4617-9db6-237dcb13664a)

</details>

### Logs

I don't have any relevant logs. Tested on Android. 

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
    • Flutter version 3.22.0 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (13 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\apopa\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2019 16.11.27)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.33801.447
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (4 available)
    • 21081111RG (mobile) • lby9dq4donga59lf • android-arm64  • Android 14 (API 34)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 124.0.6367.208
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 125.0.2535.51

[√] Network resources
    • All expected network resources are available.```

</details>

**Comment by kenzieschmoll** [comment] 2024-05-29 20:56
I cannot reproduce on Flutter master (which contains a more recent version of DevTools). Can you reproduce on the flutter master channel? If so, how are you running your test?

**Comment by Andrei7506238** [comment] 2024-05-30 12:00
Seems to be working as expected on the master channel. Thank you!
Any idea when will the fix be available on stable channel?

```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.23.0-13.0.pre.24, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2019 16.11.27)
[√] Android Studio (version 2022.2)
[√] Connected device (4 available)
[√] Network resources```

Tested on a Windows host with the app running on Android.

**Comment by kenzieschmoll** [comment] 2024-06-26 22:02
The last Flutter stable release went out in May, and we aim to release quarterly, so this fix should hit stable in a couple of months. In the meantime, you can use the beta channel to get extensions support for integration tests. Closing this issue as fixed. Thanks!

**Closed by kenzieschmoll** 2024-06-26 22:02 UTC
Labels: d: devtools, has reproducible steps, devtools extensions
