### ISSUE TITLE
Permalinks don't work on the flutter:web version of the app

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1725] opened 2020-03-11 23:31 UTC
You should be able to refresh the page and stay on the same page in devtools.

**Comment by kenzieschmoll** [comment] 2020-05-06 22:05
@DanTup will this be fixed by the work you are doing?

**Comment by DanTup** [comment] 2020-05-07 06:22
Yep, it should do. It worked fine when I used named routes, but that caused full page transitions when changing between tabs. I believe HTML's pushState *should* work, but unexpected things are happening with the back button that I haven't figured out yet.

**Comment by DanTup** [comment] 2020-05-07 10:31
I can't get `pushState` to work here. I tried both using just pushState, and also addLocalHistoryEntry+pushState, but they both have weird behaviour when you start clicking the Back button (for example when using both, the history builds up correctly in the back button, but the first time you click it, the whole history vanishes).

I've read through [Navigator 2.0](https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit#heading=h.l6kdsrb6j9id) docs but can't see anything obvious that would help here.

**Comment by DanTup** [comment] 2020-05-18 15:12
There's an open PR in Flutter that makes changes to routing:

https://github.com/flutter/flutter/pull/55316/files

With those changes, I have a working sample that correctly updates the address bar, handles refresh/back etc. by using a custom RouterDelegate (though there's a remaining [minor issue if you press Back too many times](https://github.com/DanTup/tab_route_test/issues/1#issuecomment-630246247)) here:

https://github.com/DanTup/tab_route_test/blob/a9298fa97090039bd5bad8487c9e746ee28dc4ae/lib/main.dart#L117-L187

I'm not sure how close it is, but once that PR lands I'll have a go at trying to make it work in DevTools.

**Comment by chunhtai** [comment] 2020-05-18 17:09
The /#/ tag is a local strategy we use to avoid reloading the whole page i believe, and it is built in to our web engine. https://github.com/flutter/engine/blob/4b1a70e6a2564cd27b51b7a47d86d5fbe79a09ef/lib/web_ui/lib/src/engine/browser_location.dart#L58

I do remember we have a pr to add other strategy that might solve this issue. cc @mdebbar

**Comment by DanTup** [comment] 2020-06-02 15:12
@mdebbar do you have any thoughts on the above?

**Comment by devoncarew** [comment] 2020-07-29 18:32
@DanTup - is this planned for the current (this week release), or should we bump it to M20 (or 'on deck')?

**Comment by kenzieschmoll** [comment] 2020-09-03 22:01
Pinging this issue - moving to M21 for now

**Comment by chunhtai** [comment] 2020-09-03 22:11
This should be fixed as part of https://github.com/flutter/flutter/issues/64494 and once the devtool is migrated to use router.

**Comment by mdebbar** [comment] 2020-09-03 22:11
@DanTup @chunhtai it's not clear to me what the issue is exactly. Calling `history.pushState` by yourself is probably going to cause issues because the web engine assumes full ownership of the browser history.

If you could give me a brief explanation of the issue I might be able to suggest a workaround. Using `history.replaceState` for example could work if all you want is to update the path in the address bar. But please keep the history state object unchanged i.e. do `history.replaceState(history.state, '', '/#/' + myNewPath);`

**Comment by DanTup** [comment] 2020-09-07 13:17
@mdebbar DevTools uses a TabController/TabBarView fort he different sections, and we'd like to have the current tab included in the URL so that we can deep-link to specific tabs and also have refresh/copy+paste of URLs remain on the correct tab (and also, the back button should navigate back through the tabs you've visited).

The tabs animate (slide) and if we push a new route whenever you change tab, it would interfere with the animation (it would do a full page transition - which was different to if we did not push the route), and therefore I was looking for some way to update the URL without triggering anything in Flutter (though it does feel like there should be a better way).

I made a small sample to reproduce the issue, which I previously had working with @chunhtai's changes - however it's not currently working against current Flutter master:

https://github.com/DanTup/tab_route_test/tree/new-router

Now, the address bar doesn't update at all (see https://github.com/DanTup/tab_route_test/issues/1#issuecomment-672927631).

**Comment by chunhtai** [comment] 2020-09-08 18:50
@DanTup The URL update will be fixed in https://github.com/flutter/flutter/issues/64494.

**Comment by DanTup** [comment] 2020-09-09 10:50
@chunhtai I've subscribed to that issue and will try updating once it's done. Thanks!

**Comment by DanTup** [comment] 2020-09-14 16:56
@chunhtai seems to work great, thank you!

**Comment by DanTup** [comment] 2020-09-15 13:26
@chunhtai I've made some progress trying to update DevTools, but I'm not sure I entirely understand the interaction between the `RouterDelegate` and `Navigator`.

If I don't have a `Navigator` and just build everything in the `RouterDelegate`'s `build` method, things generally work - however DevTools has code that uses Navigator (for things like dialogs), so I think we still need one.

If I do have a Navigator then when something updates the route using the `RouterDelegate`, the `RouterDelegate` is rebuilt, but the Navigator's `onGenerateRoute` is not called again so what's displayed is not updated. I'm not sure of the correct way to handle this. I've updated my sample to match DevTools more closely (which uses `onGenerateRoute`) here:

https://github.com/DanTup/tab_route_test

It displays a landing screen with a Connect button. Clicking that correctly updates the URL in the address bar but what's visible does not change. Refreshing the page will then show the expected page (the tab view, which almost mostly works correctly including Refresh, but the Back has the same issue that it doesn't rebuild properly and again, pressing Refresh fixes it).

So I think I'm missing something in my RouterDelegate that would trigger Navigator's `onGenerateRoute` (though it's possible I've not gone about this the right way). Any suggestions?

**Comment by chunhtai** [comment] 2020-09-15 17:22
@DanTup  You will need to use Page api to update the content of the navigator, We encourage people to move away from the onGenerateRoute because the exact issue you were facing, you can not update the existing route on the route stack.

In your example you can use a MaterialPage/TransitionBuilderPage with the builder, which builds the page content based on screen and args, and pass it into the navigator. Depends if you want page transition you may or may not key the Page.

**Comment by DanTup** [comment] 2020-10-01 12:39
I updated my example project to use Navigator and Pages, and everything seems to work great:

code -> https://github.com/DanTup/tab_route_test
demo -> https://blog.dantup.com/tab_route_test/index.html

However, when trying to apply the same thing in DevTools I'm hitting an error ("Maximum call stack size exceeded") that I can't figure out (I don't know if it's related to routing at all - but I'm unsure how to debug). It occurs on Chrome when I try to go to a URL directly (which works fine in the small sample above). The line it references (in initializer.dart) is the `super()` call on the constructor (though it also says `set [_widget]` and makes it seem like that's in a loop - though I can't see how).

Code is at https://github.com/DanTup/devtools/tree/router-testing
It repro's by running the app in Chrome, connecting to a VM service and then force-refreshing.

I'm using latest Flutter master from today. Any suggestions for debugging would be greatly appreciated!

```
parsing route: /?uri=ws%3A%2F%2F127.0.0.1%3A54967%2FYT0dLZ_nNSc%3D%2Fws
setting new route path "" / {uri: ws://127.0.0.1:54967/YT0dLZ_nNSc=/ws}
RouterDelegate is building!  / {uri: ws://127.0.0.1:54967/YT0dLZ_nNSc=/ws}
Getting pages for "" / {uri: ws://127.0.0.1:54967/YT0dLZ_nNSc=/ws}
Building tabbed screen! {uri: ws://127.0.0.1:54967/YT0dLZ_nNSc=/ws}
Returning initializer!
creating state for initialier

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following JSRangeError was thrown building Builder:[39;49m
Invalid argument: Maximum call stack size exceeded

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mNavigator-[LabeledGlobalKey<NavigatorState>#f4dd4][39;49m 
 lib/src/app.dart
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244mpackages/devtools_app/src/initializer.dart 34:24                         set [_widget][39;49m
[38;5;244mpackages/devtools_app/src/initializer.dart 34:24                         set [_widget][39;49m
[38;5;244mpackages/devtools_app/src/initializer.dart 34:24                         set [_widget][39;49m
[38;5;244mpackages/devtools_app/src/initializer.dart 34:24                         set [_widget][39;49m
[38;5;244mpackages/devtools_app/src/initializer.dart 34:24                         set [_widget][39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
returning "Instance of 'DevToolsRouteConfiguration'" as current config
restoring route:  : {uri: ws://127.0.0.1:54967/YT0dLZ_nNSc=/ws}
Error: [object Event]
    at Object.createErrorWithStack (http://localhost:57803/dart_sdk.js:4347:12)
    at Object._rethrow (http://localhost:57803/dart_sdk.js:37958:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57803/dart_sdk.js:37952:13)
    at Object._microtaskLoop (http://localhost:57803/dart_sdk.js:37784:13)
    at _startMicrotaskLoop (http://localhost:57803/dart_sdk.js:37790:13)
    at http://localhost:57803/dart_sdk.js:33299:9
```

**Comment by DanTup** [comment] 2020-10-01 14:48
For reasons I cannot explain, I can no longer reproduce the issue described above. I managed to get to the point where adding/removing the AutoDisposeMixin was triggering it and thought I was getting somewhere, but after a clean I can no longer reproduce it with or without.

(However, there is a similar report at https://github.com/flutter/devtools/issues/2378 so I'm thinking it may be unrelated to the Page API changes).

**Comment by chunhtai** [comment] 2020-10-01 16:36
deep link in web is similar to hot restart, i couldn't tell what may have cause this from a glance. cc @jonahwilliams

**Comment by DanTup** [comment] 2020-10-01 17:00
I think the issue I was seeing was caused only while reloading, but not when reloading from the red error page (which is why it seemed like adding/removing the mixin was fixing/breaking it - but I was actually just alternating between reloading from the app and the error screen).

I don't think it's related to these changes now though, so I'll dig into it separately once I'm done getting the tests all passing for this work Thanks!

**Closed** 2020-10-26 18:53 UTC
Labels: good first issue, hummingbird, release-blocker
