### ISSUE TITLE
[Flutter 3.24.0] Flutter DevTools 2.37.2 not showing Http requests/response, only SOCKETs

### ISSUE THREAD

**Issue by leononly** [flutter/devtools#8173] opened 2024-08-08 06:47 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.0
Flutter Version: 3.24.0 / stable
Framework / Engine: 80c2e84975 / b8800d88be

![image](https://github.com/user-attachments/assets/ebdb446e-d585-4849-aac1-42fbddb8b5fe)

**Comment by huongrealest** [comment] 2024-08-12 02:22
As far as I know, a developer said it has been fixed but I don't know if it has been released with this release or not.

**Comment by kenzieschmoll** [comment] 2024-08-14 21:15
Closing as a duplicate of https://github.com/flutter/devtools/issues/8113. On the linked issue, there are comments that suggest running `flutter clean` fixed or rebooting your machine may help.

**Closed by kenzieschmoll** 2024-08-14 21:15 UTC
