### ISSUE TITLE
Sometimes, nested JSON Response not opening when i click on the right arrow icon

### ISSUE THREAD

**Issue by santhosh-inf** [flutter/devtools#7435] opened 2024-03-23 18:25 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.3.0
Flutter Version: 3.19.2 / stable
Framework / Engine: 7482962148 / 04817c99c9

**Comment by kenzieschmoll** [comment] 2024-03-25 18:11
@CoderDake is this a duplicate of an issue you've already resolved?

**Comment by elliette** [comment] 2024-07-19 18:00
Confirmed that this is now fixed:

![network_panel](https://github.com/user-attachments/assets/cc45b40f-2dc1-4197-b529-7d5df5c17619)

**Closed by elliette** 2024-07-19 18:00 UTC
Labels: network page, P2, reproduce to verify
