### ISSUE TITLE
info_controller_test is flaky.

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1234] opened 2019-10-21 01:38 UTC
We see a significant number of failures on the bots like:
```
00:48 +15 -1: /Users/travis/build/flutter/devtools/packages/devtools_app/test/info_controller_test.dart: info controller entering [E]                                                                  
  Expected: <0>
    Actual: <2>
  Value of expectedFlags is [[Flag name: causal_async_stacks, comment: Improved async stacks, modified: true], [Flag name: async_debugger, comment: Debugger support async functions., modified: false]]
  
  package:test_api                                         expect
  package:devtools_testing/info_controller_test.dart 80:7  runInfoControllerTests.<fn>.<fn>
```

**Comment by kenzieschmoll** [comment] 2019-11-08 18:29
Just saw this again. I restarted the build so I lost the trace... It was slightly different. Expected <0> but found <1>. Will add the trace to this issue when I see it again.

**Comment by kenzieschmoll** [comment] 2019-11-19 23:45
Closing as dupe of https://github.com/flutter/devtools/issues/1193

**Closed by kenzieschmoll** 2019-11-19 23:45 UTC
