### ISSUE TITLE
Reporting error: Failed to parse package:flutter_application_1/main.dart.

### ISSUE THREAD

**Issue by Yash-123-git** [flutter/devtools#8204] opened 2024-08-17 06:31 UTC
Stack trace:
main.dart.js 6417:18    Object.rF
main.dart.js 74390:76   <fn>
main.dart.js 4987:63    bS3.a
main.dart.js 62876:14   bS3.$2
main.dart.js 62870:21   bPL.$1
main.dart.js 5283:19    Object.bRH
main.dart.js 182573:10  apm.<fn>
main.dart.js 64110:12   a31.uq
main.dart.js 63437:11   bBr.$0
main.dart.js 5164:40    Object.PZ

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**IDE**: VSCode
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.5.0
Flutter Version: 3.24.0 / stable
Framework / Engine: 80c2e84975 / b8800d88be

**Comment by kenzieschmoll** [comment] 2024-08-21 20:39
duplicate of https://github.com/flutter/devtools/issues/7192

**Closed by kenzieschmoll** 2024-08-21 20:39 UTC
