### ISSUE TITLE
VSCode edit / restart 40% requires (restart twice)

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#2011] opened 2020-05-29 11:34 UTC
First time restart:

```
Reload already in progress, ignoring request
Reloaded 100 of 1031 libraries in 2,771ms.
```
Second time restart:

```
Restarted application in 915ms.
flutter: DevTools version 0.2.5.
```
Sometimes this maybe a timing issue.  Make an edit, hit CTRL+S with immediate hot restart.  If I pause for a second after CTRL+S seems to work.

**Comment by devoncarew** [comment] 2020-05-29 15:20
@terrylucas - this may have been a recent regression in flutter; can you update to the latest on master, and see if this reoccurs?

**Comment by elliette** [comment] 2024-10-17 20:52
Closing since this seems like it was occurring on an old version of Flutter.

**Closed by elliette** 2024-10-17 20:52 UTC
