### ISSUE TITLE
Debugger, when connected to web app, opens web_entrypoint.dart by default

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#5266] opened 2023-02-17 18:55 UTC
actually opened file: file:///Users/polinach/Downloads/apprecordtypes/web_entrypoint.dart
expected file: file:///Users/polinach/Downloads/apprecordtypes/lib/main.dart

**Comment by polina-c** [comment] 2023-02-17 18:55
@elliette

**Comment by kenzieschmoll** [comment] 2023-05-26 22:24
closing as a duplicate of https://github.com/flutter/devtools/issues/5350

**Closed by kenzieschmoll** 2023-05-26 22:24 UTC
