### ISSUE TITLE
Pause button in the DevTools debugger is broken

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#4974] opened 2022-12-20 21:27 UTC
Repro steps: open the gallery application and DevTools both run in MacOs debug mode and click the pause button in DevTools. The app becomes unresponsive but DevTools never shows it is paused on a breakpoint.

**Comment by kenzieschmoll** [comment] 2023-05-26 22:47
closing as a duplicate of https://github.com/flutter/devtools/issues/5506

**Closed by kenzieschmoll** 2023-05-26 22:47 UTC
Labels: bug, debugger page
