### ISSUE TITLE
Keyboard shortcuts for stepping in / out of code

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#5714] opened 2023-04-24 23:16 UTC
Broken out from https://github.com/flutter/devtools/issues/5703, find repro steps there

**Comment by kenzieschmoll** [comment] 2023-05-26 22:09
Transferring from another issue: https://github.com/flutter/devtools/issues/1972

##
## Key shortcuts
- [ ] Match Chrome DevTools key shortcuts where possible
- [ ] Add keyboard accelerators:
- - [ ] continue - F5
- - [ ] pause - F6
- - [ ] step over - F10
- - [ ] step into - F11
- - [ ] step out - shift-F11
- - [ ] goto line - cmd-L
- - [ ] previous file location - cmd-[
- - [ ] next file history location - cmd-]
##

**Comment by kenzieschmoll** [comment] 2023-05-30 23:12
closing as a dupe of https://github.com/flutter/devtools/issues/3867

**Closed by kenzieschmoll** 2023-05-30 23:12 UTC
Labels: enhancement, good first issue, debugger page
