### ISSUE TITLE
Reporting error: Failed to parse package:dupfiles/main.dart.

### ISSUE THREAD

**Issue by CliffGreer-creator** [flutter/devtools#7377] opened 2024-03-16 10:09 UTC
Stack trace:
main.dart.js 6212:18    Object.qn
main.dart.js 69298:76   <fn>
main.dart.js 4775:63    bFj.a
main.dart.js 58094:14   bFj.$2
main.dart.js 58088:21   bDc.$1
main.dart.js 5071:19    Object.bEY
main.dart.js 168428:68  al8.<fn>
main.dart.js 59293:12   a_M.rF
main.dart.js 58598:11   bpI.$0
main.dart.js 4940:40    Object.Nj

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**Connected Device**:
CPU / OS: x64 (64 bit) windows
Connected app type: Flutter native (profile build)
Dart Version: 3.3.1
Flutter Version: 3.19.3 / stable
Framework / Engine: ba39319843 / 2e4ba9c6fb

**Comment by kenzieschmoll** [comment] 2024-03-25 23:46
closing as duplicate of https://github.com/flutter/devtools/issues/7192

**Closed by kenzieschmoll** 2024-03-25 23:46 UTC
