### ISSUE TITLE
Stuck on "Activating Dart Devtools"  ... blank page

### ISSUE THREAD

**Issue by zhoupenglei** [flutter/devtools#2899] opened 2021-04-14 10:05 UTC
Since upgrading to the latest version of Flutter, I cannot debug my apps while connected to the internet. It simply gets stuck on "Activating Dart Devtools...". If I disconnect from the internet, and then debug, it's fine. 

Also, if I try to debug while connected to the internet, the "Activating Dart Devtools" does not go away. I have to close my IDE and terminate all dart related processes.

[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale zh-CN)
    • Flutter version 2.0.4 at D:\fluttersdk\flutter
    • Framework revision b1395592de (13 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

tasks:
Activating Dart DevTools... #

the same with   https://github.com/flutter/flutter/issues/80148

**Comment by kenzieschmoll** [comment] 2021-04-14 16:10
closing as a duplicate of https://github.com/flutter/flutter/issues/80148

**Closed by kenzieschmoll** 2021-04-14 16:10 UTC
