### ISSUE TITLE
Dart DevTools exited with code 255

### ISSUE THREAD

**Issue by Qubits-Official** [flutter/devtools#2654] opened 2021-02-01 03:20 UTC
$ flutter --version
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (9 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

$ flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale
    en-US)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (9 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)     
    • Android SDK at C:\Users\AUser\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.        
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\AUser\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28)
      (emulator)

! Doctor found issues in 1 category.

I can't open devtools after the update (in vscode). I reinstalled flutter and the vscode extensions, but the error (255) still persist.

I also tried this solution, but it still gives the same error (255).

$ flutter pub global activate devtools
Package devtools is currently active at version 0.9.7+1.
Resolving dependencies...
+ args 1.6.0
+ async 2.4.2
+ browser_launcher 0.1.8
+ charcode 1.1.3
+ collection 1.14.13
+ convert 2.1.1
+ devtools 0.9.7+1
+ devtools_server 0.9.7+1
+ devtools_shared 0.9.7+1
+ http 0.12.2
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ intl 0.16.1
+ logging 0.11.4
+ meta 1.2.4
+ mime 0.9.7
+ path 1.7.0
+ pedantic 1.9.2
+ shelf 0.7.9
+ shelf_proxy 0.1.0+7
+ shelf_static 0.2.9+2
+ source_span 1.7.0
+ sse 3.6.1
+ stack_trace 1.9.6
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ usage 3.4.2
+ vm_service 5.5.0
+ webkit_inspection_protocol 0.7.4
Precompiling executables...
Precompiled devtools:devtools.
Installed executable devtools.
Activated devtools 0.9.7+1.

$ flutter pub global run devtools
Unhandled exception:
Invalid argument(s): A directory corresponding to fileSystemPath "C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\devtools-0.9.7+1\build" could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/external_handlers.dart:40:23)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:183:21)
#3      _serveDevToolsWithArgs (package:devtools_server/src/server.dart:125:10)
#4      serveDevToolsWithArgs (package:devtools_server/src/server.dart:72:16)
#5      main (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/devtools-0.9.7+1/bin/devtools.dart:9:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)      
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)     
pub finished with exit code 255

I apologize in advance if this problem is trivial, I'm just new to flutter.

**Comment by jeiea** [comment] 2021-02-01 03:29
It seems duplicate of #2653.

**Comment by bkonyi** [comment] 2021-02-01 03:57
Closing as duplicate of #2653. Thanks for reporting!

**Closed by bkonyi** 2021-02-01 03:57 UTC
