### ISSUE TITLE
Download .har file in network tab from flutter devTool

### ISSUE THREAD

**Issue by navinkumar0118** [flutter/devtools#7245] opened 2024-02-19 10:21 UTC
- cant able to download .har file or network traffic report in flutter devTool network tab

![Uploading Screenshot 2024-02-19 at 3.46.49 PM.png…]()

___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.0.6
Flutter Version: 3.10.6 / stable
Framework / Engine: f468f3366c / cdbeda788a
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment] 2024-07-15 22:58
closing as a duplicate of https://github.com/flutter/devtools/issues/3806

**Closed by kenzieschmoll** 2024-07-15 22:58 UTC
Labels: network page
