### ISSUE TITLE
Devtools cannot access provider

### ISSUE THREAD

**Issue by neholouis** [flutter/devtools#5183] opened 2023-02-03 11:06 UTC
Hi there ! 

I LOVE FLUTTER.

That said, I have an issue that is a bit annoying to get provider values, the debug tool cannot ping to the provider api.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/97518849/216587901-873a3a01-82d9-4c68-a188-aba89abaae96.png">

My provider is at the version 6.0.5

Help me pweaaaaase !

Thanks !

**Comment by CoderDake** [comment] 2023-02-06 16:30
@rrousselGit Do you have any insights here?

**Comment by rrousselGit** [comment] 2023-02-06 16:40
Hard to say. I don't see why there would be an issue, so I'd need some form of way to reproduce the problem

**Comment by dIvYaNshhh** [comment] 2023-03-24 09:30
I am using `flutter_bloc: ^8.1.1` version and I am also getting a similar issue.

<img width="1912" alt="Screenshot 2023-03-24 at 2 59 38 PM" src="https://user-images.githubusercontent.com/6985574/227480775-8b8406c8-61ad-4a29-add4-bf47c6f6d2c7.png">

**Comment by kenzieschmoll** [comment] 2023-03-28 01:02
@rrousselGit are you able to take a look at this?

**Comment by rrousselGit** [comment] 2023-03-28 04:10
No. I'm busy with other things

**Comment by dIvYaNshhh** [comment] 2023-03-29 04:10
@rrousselGit the step to reproduce is very simple.
1. Use flutter_bloc
2. Create some bloc and use it in the app
3. Run the app on chrome

**Comment by kenzieschmoll** [comment] 2024-07-31 20:55
Closing this since the Provider tool has been re-written as a DevTools extension provided by `package:provider`. Any issues with the Provider tool should be filed on the package's issue tracker.

**Closed by kenzieschmoll** 2024-07-31 20:55 UTC
