### ISSUE TITLE
Reporting error: Error collecting raster stats: _flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame was rendered

### ISSUE THREAD

**Issue by tiwarisuraj136** [flutter/devtools#7895] opened 2024-06-07 10:17 UTC
Stack trace:
Error
    at Object.qy (http://127.0.0.1:9101/main.dart.js:6368:18)
    at bjG.$0 (http://127.0.0.1:9101/main.dart.js:169047:5)
    at iG.cE (http://127.0.0.1:9101/main.dart.js:168915:53)
    at iG.m6 (http://127.0.0.1:9101/main.dart.js:168899:13)
    at http://127.0.0.1:9101/main.dart.js:103087:14
    at bHu.a (http://127.0.0.1:9101/main.dart.js:4960:63)
    at bHu.$2 (http://127.0.0.1:9101/main.dart.js:59676:14)
    at bFf.$1 (http://127.0.0.1:9101/main.dart.js:59670:21)
    at Object.bH8 (http://127.0.0.1:9101/main.dart.js:5245:19)
    at alE.<anonymous> (http://127.0.0.1:9101/main.dart.js:172546:10)
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.34.3
**Connected Device**:
CPU / OS: arm (32 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.4.0
Flutter Version: 3.22.0 / stable
Framework / Engine: 5dcb86f68f / f6344b75dc

**Comment by kenzieschmoll** [comment] 2024-06-25 19:18
closing as a duplicate of https://github.com/flutter/devtools/issues/6992

**Closed by kenzieschmoll** 2024-06-25 19:18 UTC
