### ISSUE TITLE
Reporting error: Failed to parse package:tenh100/main.dart.

### ISSUE THREAD

**Issue by RothaSoeurn** [flutter/devtools#7521] opened 2024-04-04 08:19 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.1.0-262.3.beta
Flutter Version: 3.13.0-0.4.pre / beta
Framework / Engine: 7e07cd41cb / 73d89ca7c5
Connected app type: Flutter native (profile build)

**Comment by kenzieschmoll** [comment] 2024-04-04 14:57
closing as duplicate of https://github.com/flutter/devtools/issues/7192

**Closed by kenzieschmoll** 2024-04-04 14:57 UTC
