### ISSUE TITLE
in VSCode when i open devtools and select widget mode and select widget on screen ... don't open widget file location

### ISSUE THREAD

**Issue by MoRmdn** [flutter/devtools#6876] opened 2023-12-01 16:10 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.2
Flutter Version: 3.16.2 / stable
Framework / Engine: 9e1c857886 / cf7a9d0800

**Comment by kenzieschmoll** [comment] 2023-12-01 17:34
@DanTup This is the latest DevTools version on flutter stable. Any idea why this might be broken?

**Comment by DanTup** [comment] 2023-12-02 11:40
@MoRmdn are you running using `F5` / `Run -> Start Debugging` or `Ctrl`+`F5`/`Run -> Start Without Debugging`?

When you run _without_ debugging, we don't connect the debugger to the VM Service, so the editor won't have this kind of functionality.  You'll need to run in debug mode for this to work.

In older versions of Flutter (using the legacy debug adapters), we did _always_ connected to the VM so this might have worked in the past, but it was accidental (and different between Dart/Flutter). The new debug adapters are consistent between Dart/Flutter and will only have a connection to the VM when debugging.

This might change a little in future though, as some functionality may move to a new process (the Dart Tooling Daemon), which may allow us to communication between tools even when there's no connection between the debugger and the VM.

**Comment by heshesh2010** [comment] 2023-12-09 12:15
@DanTup I have same issue with flutter 3.16 using debug mode , 

vscode lunch file 

        {
            "name": "Flutter (hesham’s iPhone)",
            "program": "lib/main.dart",
            "deviceId": "00008120-000819A21A70201E",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug"
        }

also i'm running on debug mode 

![Screenshot 2023-12-09 at 2 12 55 PM](https://github.com/flutter/devtools/assets/16393042/31d0de1a-4017-4937-b12c-13e1758faebb)

I have the same issue + other issue when first select text widget for example it works , but when i toggle and return to toggle again it forces me to select the same previous  text widget i can't select any other widget , unless i clicked on search icon in bottom left side of screen so it works , but in android the android navigation bar is overlap this icon so it's very hard to click on it .

**Comment by DanTup** [comment] 2023-12-09 14:09
> but when i toggle and return to toggle again it forces me to select the same previous text widget i can't select any other widget , unless i clicked on search icon

@jacob314 @kenzieschmoll is this intended functionality? As long as I can remember I've had to click on the magnifying glass in the bottom left on the device after selecting a widget before I can select another. I assumed this was expected, though I'm not sure.

**Comment by DanTup** [comment] 2023-12-09 14:41
I just tested this using Flutter stable with DevTools outside of VS Code, and I see this same behaviour. Each time I select a widget I need to click the magnifying glass before I can select another:

https://github.com/flutter/devtools/assets/1078012/b438b9e6-5118-4536-821c-fc9c51d47687

I think this is different to the original issue here, which is that with the latest release in VS Code the navigation only worked in "Debug" mode. The pre-release version of the Dart extension fixes this and will be patched to the stable extension next week.

**Comment by xaakib** [comment] 2023-12-09 18:06
[DanTup](https://github.com/DanTup) it is working widget tree not code tab , we need to fix that when we select device widget then it will working on widget tree and code tab which code we selected in device .

**Comment by DanTup** [comment] 2023-12-09 18:13
@xaakib Yes, there seem to be two different issues noted above. One is that code navigation is not occurring when not using Debug mode - that is fixed in the Pre-release Dart extension (see my response at https://github.com/flutter/devtools/issues/6892#issuecomment-1848603996).

The other issue noted was that selecting widgets only works the first time - that's what my video shows, but I believed that to be by design. Hopefully Jacob or Kenzie can confirm if that's the case or not.

**Comment by xaakib** [comment] 2023-12-09 18:16
yes, thank you very much, it's now worked clearly.

**Comment by DanTup** [comment] 2023-12-11 11:46
The issue of the inspector not navigating correctly is resolved in v3.78.2 of the Dart extension. Please update and click the "Reload" button if prompted.

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/eab7282f-0bcc-435b-8e27-b2a321a2d221)

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/8149c83d-08fd-4644-b0c9-f4afc7c328cb)

**Closed by DanTup** 2023-12-11 11:46 UTC
Labels: inspector page, vs-code

**Comment by kenzieschmoll** [comment] 2023-12-12 17:22
> The other issue noted was that selecting widgets only works the first time - that's what my video shows, but I believed that to be by design. Hopefully Jacob or Kenzie can confirm if that's the case or not.

This is by design (although it is a design that we want to revisit soon to make this more intuitive). When select widget mode is enabled, you can select a widget on the device, but then to select another, you need to first click on the magnifying glass icon in the lower right corner.
