### ISSUE TITLE
Profiler is missing flow perspective

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/devtools#4754] opened 2022-11-15 21:38 UTC
I.e., one focuses on a function and sees both callers and callees of that function proportional to number of samples containing them as callers/callees. This is unlike the top-down or bottom-up tree views, which display only one or the other. Compare the profile-table view in Observatory.

**Comment by bkonyi** [comment] 2022-11-17 14:33
Duplicate of https://github.com/flutter/devtools/issues/3861.

**Closed by bkonyi** 2022-11-17 14:33 UTC
Labels: cpu profiler, missing core functionality
