### ISSUE TITLE
DevTools with CanvasKit does not work on Chrome 86

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2290] opened 2020-08-19 18:44 UTC
Seeing the following unminified error:

```
Uncaught TypeError: FinalizationRegistry: cleanup must be callable
    at new FinalizationRegistry (<anonymous>)
    at canvaskit_api.dart:1597
    at Object.holder.<computed> [as $get$skObjectFinalizationRegistry] (main.dart.js:117)
    at CkPaint.ManagedSkiaObject$0 (skia_object_cache.dart:133)
    at Object.CkPaint$ (painting.dart:13)
    at painting.dart:907
    at _wrapJsFunctionForAsync_closure.$protected (async_patch.dart:315)
    at _wrapJsFunctionForAsync_closure.call$2 (async_patch.dart:340)
    at Object._asyncStartSync (async_patch.dart:245)
    at DefaultShaderWarmUp.warmUpOnCanvas$body$DefaultShaderWarmUp (shader_warm_up.dart:129)
```

**Comment by jacob314** [comment] 2020-08-24 17:47
Has this been fixed with tip of trunk Flutter? If not then we need to file a bug there.

**Comment by grouma** [comment] 2020-08-26 19:40
It's hard to verify if this is still broken as we have another blocking issue on Chrome Canary: https://github.com/dart-lang/webdev/issues/1087

**Comment by yjbanov** [comment] 2020-09-01 20:44
I'm unable to reproduce in Chrome 86.0.4239.0. Can you please provide your chrome://version info?

**Comment by jpohhhh** [comment] 2020-09-03 02:59
fwiw I'm on 86.0.4240.11 and seeing this

**Comment by hterkelsen** [comment] 2020-09-09 23:04
I filed an issue with dart2js to fix this in the compiler: https://github.com/dart-lang/sdk/issues/43373

In the meantime I am landing a fix to the engine.

**Comment by yjbanov** [comment] 2020-09-18 22:07
I think we can close this now?

**Comment by grouma** [comment] 2020-10-09 21:34
I'm seeing this with the latest DevTools version pulled into `package:dwds` / `package:webdev`. (version `0.9.3+4`)

@hterkelsen did your fix land?

**Comment by mariamhas** [comment] 2020-12-07 22:11
This shouldn't be an issue anymore @grouma  can you confirm if you still see this issue?

**Closed** 2020-12-11 18:32 UTC
Labels: waiting for customer response
