### ISSUE TITLE
[Feature] DevTools should be 3rd party extensible with custom data and logic

### ISSUE THREAD

**Issue by chipweinberger** [flutter/devtools#5700] opened 2023-04-22 00:39 UTC
<img width="894" alt="Screenshot 2023-04-21 at 5 35 27 PM" src="https://user-images.githubusercontent.com/1863934/233752347-a6abd129-1ec6-4ffd-ac55-42644a78bb94.png">

DevTools should support custom data and logic. For example:

- inspect state of my internal app database
- run custom debug commands in my app, and see their results

Of course, this code would be highly custom to my app, and can only be achieved if DevTools is extensible by 3rd parties.

**Comment by kenzieschmoll** [comment] 2023-04-24 16:27
Closing as a duplicate of https://github.com/flutter/devtools/issues/1632

**Closed by kenzieschmoll** 2023-04-24 16:27 UTC
