### ISSUE TITLE
Rest API Calls are not Logged

### ISSUE THREAD

**Issue by Gagnar1999** [flutter/devtools#7764] opened 2024-05-16 06:34 UTC
Hello Flutterians i am facing an strange issue where i am unable to see api calls in dev tools.
___
**DevTools version**: 2.34.3
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.0
Flutter Version: 3.22.0 / stable
Framework / Engine: 5dcb86f68f / f6344b75dc

**Comment by kenzieschmoll** [comment] 2024-05-16 16:44
@CoderDake

**Comment by CoderDake** [comment] 2024-05-21 18:30
@Gagnar1999 could you please provide an example of the api calls? Some code to help reproduce this would go a long way :)

**Comment by Gagnar1999** [comment] 2024-05-22 05:27
The issue is when i call api through http/dio network library it should be visible in the network tab in dev tools section but instead of showing any api call it just show internet address calls only.
![image](https://github.com/flutter/devtools/assets/45447313/e37d75c8-2f48-49d8-a075-f87587d11fea)

**Comment by Gagnar1999** [comment] 2024-05-22 05:28
also i want one more feature request can you guys removed these internet address logs from network tab it causes issue when there are multiple api calls

**Comment by CoderDake** [comment] 2024-05-22 13:24
Progress for additional network logging support is  is being tracked here: https://github.com/flutter/devtools/issues/7764

I'll close this as a duplicate.


----
RE your additional request:
Those requests can be filtered out using the a `-type:ws` filter. That will hide those logs you don't want to see
<img width="752" alt="Screenshot 2024-05-22 at 9 19 41 AM" src="https://github.com/flutter/devtools/assets/1386322/85598090-d944-46f9-bf2d-b3342bb15234">

**Closed by CoderDake** 2024-05-22 13:24 UTC
Labels: network page

**Comment by quyenvsp** [comment] 2024-06-18 04:00
@CoderDake can you correct link where issue is being tracked, you linked and closed this issue as duplicate of itself?
This issue only happen with Android Emulator and latest Flutter 3.22, working fine on real device.

on Flutter 3.19 showing rest api and DO NOT have InternetAddress(...)
on Flutter 3.22 showing InternetAddress(...) and DO NOT have rest api
