### ISSUE TITLE
Reporting error: Error collecting raster stats: _flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame was rendered

### ISSUE THREAD

**Issue by shubhammemane1** [flutter/devtools#7636] opened 2024-04-23 07:53 UTC
Stack trace:
qn@http://127.0.0.1:9101/main.dart.js:6212:27
$0@http://127.0.0.1:9101/main.dart.js:164961:7
cA@http://127.0.0.1:9101/main.dart.js:164830:55
lU@http://127.0.0.1:9101/main.dart.js:164814:15
@http://127.0.0.1:9101/main.dart.js:101540:16
@http://127.0.0.1:9101/main.dart.js:4775:64
$2@http://127.0.0.1:9101/main.dart.js:58094:15
$1@http://127.0.0.1:9101/main.dart.js:58088:23
bEY@http://127.0.0.1:9101/main.dart.js:5071:21
@http://127.0.0.1:9101/main.dart.js:168428:71
rF@http://127.0.0.1:9101/main.dart.js:59293:14
$0@http://127.0.0.1:9101/main.dart.js:58598:13
Nj@http://127.0.0.1:9101/main.dart.js:4940:42
t4@http://127.0.0.1:9101/main.dart.js:58520:5
$0@http://127.0.0.1:9101/main.dart.js:58568:15
bEW@http://127.0.0.1:9101/main.dart.js:5068:11
@http://127.0.0.1:9101/main.dart.js:168427:69
uJ@http://127.0.0.1:9101/main.dart.js:59291:14
xM@http://127.0.0.1:9101/main.dart.js:59266:12
$0@http://127.0.0.1:9101/main.dart.js:59343:22
cnb@http://127.0.0.1:9101/main.dart.js:4972:7
cnF@http://127.0.0.1:9101/main.dart.js:4974:10
$1@http://127.0.0.1:9101/main.dart.js:58033:5
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.3.1
Flutter Version: 3.19.3 / stable
Framework / Engine: ba39319843 / 2e4ba9c6fb

**Comment by CoderDake** [comment] 2024-05-21 17:48
Duplicate of https://github.com/flutter/devtools/issues/6992

**Closed by CoderDake** 2024-05-21 17:48 UTC
