### ISSUE TITLE
Logging window is non-interactive

### ISSUE THREAD

**Issue by Hedayet** [flutter/devtools#6502] opened 2023-10-04 01:20 UTC
1. Can't copy contents from the Details or any other sections. Tried
  a. cmd+c, cmd+shift+c (on a Mac machine)
  b. cmd + drag
  c. Clicking the "Copy" icon
2. Links are also non-clickable

![Screenshot 2023-10-03 at 18 17 20](https://github.com/flutter/devtools/assets/6074651/8d3344fb-e978-437c-a8e1-1f16ff1a8c6b)

**Comment by CoderDake** [comment] 2023-10-05 20:23
The issue with not being able to copy details may be related to :
https://github.com/flutter/devtools/issues/5775

**Comment by Hedayet** [comment] 2023-10-07 05:36
wanted to share that - in-browser dev tools is a really good workaround, in case anyone else struggles with this issue.

**Comment by kenzieschmoll** [comment] 2023-10-18 20:42
closing as duplicate of https://github.com/flutter/devtools/issues/5775

**Closed by kenzieschmoll** 2023-10-18 20:42 UTC
Labels: logging page, fix it friday, P2
