### ISSUE TITLE
Flutter Inspector - Elements are greyed out and can't change values

### ISSUE THREAD

**Issue by Jshen123** [flutter/devtools#1947] opened 2020-05-09 21:48 UTC
I am currently developing on Flutter Stable and using Android Studio.

One thing I noticed is that, in Flutter Inspector (Dart Devtools), all the properties are greyed out (shown below). Does anyone have any suggestions on how to change this so I can edit the values? Thank you!

![image](https://user-images.githubusercontent.com/22240630/81485716-1e0e4e80-9204-11ea-90de-174b0893e8d2.png)

**Comment by kenzieschmoll** [comment] 2020-05-10 16:59
Thanks for the report! Properties in the inspector aren't actually editable at this time. This issue is a regression in the text color, but does not affect the functionality of the inspector. Duplicate of https://github.com/flutter/devtools/issues/1931

**Closed by kenzieschmoll** 2020-05-10 16:59 UTC
