### ISSUE TITLE
DevTools Inspector - Blank page

### ISSUE THREAD

**Issue by GeorgopoulosGiannis** [flutter/devtools#4397] opened 2022-08-20 12:33 UTC
Widget inspector is blank.  After debugging I found that it tries to load a polyfill script for inspector and fails due
to the escape character in start and end tokens.
If i remove the \n from the magic tokens it works.

![magic_tokens](https://user-images.githubusercontent.com/64830751/185746294-6c9d521c-92eb-4d1c-ac2e-11dbcde33eb6.png)

![inspector](https://user-images.githubusercontent.com/64830751/185746290-072e857f-07bc-46f4-98f6-a7223838e46b.png)
![exception](https://user-images.githubusercontent.com/64830751/185746293-209293bc-ccec-4843-94fb-f83cd7ee9c3d.png)

**Comment by kenzieschmoll** [comment] 2022-08-31 22:17
@CoderDake @jacob314

**Comment by elliette** [comment] 2024-07-31 20:45
Closing as duplicate of https://github.com/flutter/devtools/issues/4397

**Closed by elliette** 2024-07-31 20:45 UTC
Labels: inspector page, reproduce to verify
