### ISSUE TITLE
Odd behavior pausing the app with the pause botton

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#333] opened 2019-02-22 01:30 UTC
Using an IOS emulator I see the following behavior when using the Gallery application

Click the pause button

As expected the device is now frozen but I don't see a valid page of Dart source code in the debugger until I click step into.

**Comment by kenzieschmoll** [comment] 2024-10-17 20:53
closing as a duplicate of https://github.com/flutter/devtools/issues/5506

**Closed by kenzieschmoll** 2024-10-17 20:53 UTC
Labels: screen: debugger
