### ISSUE TITLE
Timeline events are not showing up on iOS

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2841] opened 2021-03-25 17:25 UTC
CPU profiling does not appear to be working when running an iOS application in profile mode on a physical device.
All other portions of the timeline page work but there are never any CPU profiling samples in either the Performance or CPU Profiler pages.

The user clicked decline on a popup dialog to allow the ios app from collecting certain data. It is possible that is related to the issue getting this data over the VM Service. We should try to reproduce on a physical iphone. The user was also running a quicktime plater to show their device on their laptop which may have also interfered.
This is most likely an issue in the VM but we should rule out that the issue is in devtools first.
The user was running the latest stable flutter build and launching DevTools from Android Studio.

**Comment by jacob314** [comment] 2021-03-25 17:26
Fyi @kenzieschmoll

**Comment by tobinharris** [comment] 2021-05-18 20:32
I'm seeing this issue, have tried with two different iOS devices (and iPhone XR and an iPad Pro later 2019). The dev tools are awesome so hoping I can get to the bottom of this.

I'm on a Mac M1, XCode 12.5.

I'm can confirm Quicktime Player is not running, and I'm running from command line with this command

`flutter run -d"iPhone" --flavor="beta" --profile -v`

Here's `flutter doctor -v`

```[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2 20D64 darwin-arm, locale en-GB)
    • Flutter version 2.0.3 at /Users/tobinharris/flutter
    • Framework revision 4d7946a68d (9 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tobinharris/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008020-000D28C101F1002E • ios            • iOS 14.0
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 90.0.4430.212```

**Comment by bkonyi** [comment] 2021-08-23 18:26
Duplicate of https://github.com/flutter/flutter/issues/88466. Closing this issue since it's not actually an issue within DevTools itself.

**Closed by bkonyi** 2021-08-23 18:26 UTC
Labels: bug, performance page, app performance
