### ISSUE TITLE
Inspect widget is not redirecting to respective code/widget on IDE.

### ISSUE THREAD

**Issue by karmokarsurjit** [flutter/devtools#6223] opened 2023-08-21 03:37 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
I am unable to goto exact code section while inspecting widget.
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.0 / stable
Framework / Engine: efbf63d9c6 / 1ac611c64e
Connected app type: Flutter native (debug build)

**Comment by DanTup** [comment] 2023-08-21 09:09
Which IDE(s) do you see this in? Maybe a dupe of https://github.com/flutter/flutter-intellij/issues/6875?

**Comment by karmokarsurjit** [comment] 2023-08-21 09:14
> Which IDE(s) do you see this in? Maybe a dupe of [flutter/flutter-intellij#6875](https://github.com/flutter/flutter-intellij/issues/6875)?

Yes, It could be but I am using Android Studio.
__________________________________________________________________
Android Studio Giraffe | 2022.3.1
Build #AI-223.8836.35.2231.10406996, built on June 29, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.2.21.2995)
    Dart (223.8950)
    com.localizely.flutter-intl (1.18.4-2022.2)
    com.tao.getx (3.3.2)
    com.spidev.pubassist (1.1)
    pl.pszklarska.pubversionchecker (1.3.5)
    com.developerphil.adbidea (1.6.12)
    io.flutter (75.1.2)

**Comment by DanTup** [comment] 2023-08-21 09:28
That repository covers both - Android Studio and IntelliJ use the same Dart/Flutter plugins (the author of that issue was also using Android Studio).

I'll close this one in favour of that. Thanks!

**Closed by DanTup** 2023-08-21 09:28 UTC
