### ISSUE TITLE
Flutter Dev Tools 2.0.0 Not displaying Response and Cookies tab inside of Network Tabs

### ISSUE THREAD

**Issue by dinurymomshad** [flutter/devtools#2757] opened 2021-03-04 09:15 UTC
![image](https://user-images.githubusercontent.com/26508767/109939398-369fa600-7cfb-11eb-8155-bcfff0b3cbaf.png)

![image](https://user-images.githubusercontent.com/26508767/109939481-4cad6680-7cfb-11eb-89ff-aef031f80595.png)

**But here it shows in the video:**
https://youtu.be/xgsjXIk3zbY?t=551

### Flutter Version Info

> Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (16 hours ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

### Flutter Doctor output:

> Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.844], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (2 available)
! Doctor found issues in 1 category.

### Android Studio Version

> Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Statistic, color.scheme.Tomorrow Dark, com.arcticicestudio.nord.jetbrains, com.intellij.marketplace, com.mallowigi.idea, com.markskelton.one-dark-theme, com.thvardhan.gradianto, net.antelle.intellij-xcode-dark-theme, Dart, io.flutter, org.tbm98.flutter-riverpod-snippets

**Comment by landonmr** [comment] 2021-03-04 15:59
Same for me using VS code

**Comment by kenzieschmoll** [comment] 2021-03-04 16:37
The Cookies and Response tabs will not show if that data is unavailable. @bkonyi - is there anything to suggest that cookies would be missing too based on the buffer related http event dropping you've been investigating?

**Comment by bkonyi** [comment] 2021-03-04 17:21
No, the cookies are returned along with the request and response headers once the request completes. If there's no cookies tab on a completed request, there weren't any cookies associated with it.

**Comment by dinurymomshad** [comment] 2021-03-04 18:44
@kenzieschmoll @bkonyi 
My HTTP requests are successful. I am getting response back. I can see them in my debug console but not in Flutter Dev Tools

**Comment by bkonyi** [comment] 2021-03-04 18:55
> @kenzieschmoll @bkonyi
> My HTTP requests are successful. I am getting response back. I can see them in my debug console but not in Flutter Dev Tools

Are you seeing cookies associated with the response in your app? If not, the lack of a cookies tab in DevTools is expected. If it's just the response tab missing and the response from your request is large, it's likely related to https://github.com/flutter/devtools/issues/2603#issuecomment-771921976.

If you do expect for there to be cookies, can you please reproduce your issue and then switch over to the Performance tab an export a timeline for us to examine along with the request/response headers you see in your application?

**Comment by dinurymomshad** [comment] 2021-03-04 19:28
I am not worried about cookies. Response is my main concern. Will save lots of print statement. My responses are really large. I think that was an issue. I will try to see if it works with simple login logout API. @bkonyi

**Comment by dinurymomshad** [comment] 2021-03-04 20:25
Okay it is not working. @bkonyi check please

### Here is my output in debug log:
> I/flutter (28050): URL: https://domain.com/api/auth/register
> I/flutter (28050): Request: {name: Jhone Doe, email: email@gmail.com, password: 12345678, password_confirmation: 12345678, agree: true, accepts_marketing: false}
> I/flutter (28050): Headers: {accept: application/json; charset=utf-8}
> I/flutter (28050): Response: 422 {"message":"The given data was invalid.","errors":{"email":["This email address already has an account. Please try something else."]}}
> I/flutter (28050): handleResponse: {message: The given data was invalid., errors: {email: [This email address already has an account. Please try something else.]}}

### Flutter Dev Tool Output:
![Http No Response](https://user-images.githubusercontent.com/26508767/110025673-e6a3fc00-7d59-11eb-9ed2-a86a6c38d10f.png)

**Comment by bkonyi** [comment] 2021-03-04 20:33
@dinurymomshad we're also going to need a copy of the exported timeline from the Performance page. Would you mind sharing that here or sending it to my email (bkonyi@google.com) if there's data you don't want public in your HTTP requests?

**Comment by dinurymomshad** [comment] 2021-03-04 20:46
@bkonyi check mail

**Comment by landonmr** [comment] 2021-03-04 20:47
FWIW, i had the same issue when trying to view  in both web browser and IDE,  however after I restarted the IDE everything worked as expected, browser and IDE

**Comment by bkonyi** [comment] 2021-03-04 20:50
> @bkonyi check mail

@dinurymomshad I haven't received anything yet. I'll give it 10 minutes or so and let you know if it came through. Otherwise, it might be easier to send to me via Discord.

**Comment by bkonyi** [comment] 2021-03-04 20:52
@dinurymomshad just received it. I'll take a look.

**Comment by dinurymomshad** [comment] 2021-03-04 20:52
> > @bkonyi check mail
> 
> @dinurymomshad I haven't received anything yet. I'll give it 10 minutes or so and let you know if it came through. Otherwise, it might be easier to send to me via Discord.

Sorry I was taking some screenshots because for some reason one of the request showed response tab. Others didn't.
But in all cases, I had response printed out in the debug console

**Comment by dinurymomshad** [comment] 2021-03-04 20:54
> FWIW, i had the same issue when trying to view  in both web browser and IDE,  however after I restarted the IDE everything worked as expected, browser and IDE

What browser are you using?
Vs Code or AS?
Response tab was visible?

**Comment by landonmr** [comment] 2021-03-04 21:05
Chrome, VS Code and yes I was seeing responses in the Response Tab

**Comment by bkonyi** [comment] 2021-03-04 21:09
@dinurymomshad it looks like the response data was in the timeline you sent me, but DevTools isn't processing it properly. I'm going to close this issue and re-open the original issue that was tracking this problem (https://github.com/flutter/devtools/issues/2398).

**Closed by bkonyi** 2021-03-04 21:09 UTC
