### ISSUE TITLE
Hot Restart test appears to be causing increased flakes

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#337] opened 2019-02-22 06:19 UTC
All tests using hot restart need to be commented out until the underlying source of the flakes can be isolated as a flaky test is a broken test.

**Comment by jacob314** [comment] 2019-02-25 03:08
The hot restart tests have been commented out for now. Need to figure out how to reduce the # of flakes after adding them back.

**Comment by kenzieschmoll** [comment] 2019-03-19 22:46
@DanTup is this resolved?

**Comment by DanTup** [comment] 2019-03-20 08:02
I don't think so. Before I got to this one, I had a flake in another test on a PR. (debug inspector controller) I ran it in a big loop for hours with logging and it never failed (!) and I didn't get back to it. I planned on looking at this one after that.

Maybe I should look at this one first though, sounds like it might be more likely to happen. I'll give have a go at running it in the background today.

**Comment by DanTup** [comment] 2019-03-20 09:12
Ok, while running these tests again, I hit a flake. It was a timeout in tearDown on this line:

```
await _service.allFuturesCompleted.future;
```

And in the logs:

```
[ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
'dart:isolate/runtime/lib/timer_impl.dart': Failed assertion: line 433: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      _Timer._cancelWakeup (dart:isolate/runtime/lib/timer_impl.dart:433:12)
#3      _Timer._notifyEventHandler (dart:isolate/runtime/lib/timer_impl.dart:299:7)
#4      _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:419:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

This is our old friend https://github.com/dart-lang/sdk/issues/33838. I think when that error occurs, some callback isn't happening which is leaving an open future.

The test does contain this:

```
      /// After the hot restart some existing calls to the vm service may
      /// timeout and that is ok.
      serviceManager.service.doNotWaitForPendingFuturesBeforeExit();
      print('HRST #6');
```

However that's right before the hot restart. My guess is that we have additional futures being registered afterwards that are failing. I'll see if it's easy to log where each future came from so we can at least tell which one isn't finishing.

In the meantime, we could try working around it with a timeout in the tearDown or something (just warn and continue) but it'd be good to get that issue fixed (@devoncarew we've discussed this before - it's turning up in Flutter and causing flakes in DC's integration tests too - it's not clear who is a good person to ping about the isolates library).

**Comment by DanTup** [comment] 2019-03-20 12:33
Here's some failures with more tracking:

```
Untracking future: callServiceExtension ext.flutter.inspector.show.159
00:50 +4 -1: test/inspector_controller_test.dart: inspector controller tests (tearDownAll) [E]
  Timed out waiting for futures to complete. 1 futures remained:
  
    callServiceExtension ext.flutter.inspector.getDetailsSubtree.160
  test/support/flutter_test_environment.dart 100:7  FlutterTestEnvironment.tearDownEnvironment.<fn>
```

```
00:48 +4 -1: test/inspector_controller_test.dart: inspector controller tests (tearDownAll) [E]
  Timed out waiting for futures to complete. 1 futures remained:
  
    callServiceExtension ext.flutter.inspector.show.160
  test/support/flutter_test_environment.dart 100:7  FlutterTestEnvironment.tearDownEnvironment.<fn>
```

```
00:40 +4 -1: test/inspector_controller_test.dart: inspector controller tests (tearDownAll) [E]
  Timed out waiting for futures to complete. 1 futures remained:
  
    callServiceExtension ext.flutter.inspector.show.160
  test/support/flutter_test_environment.dart 100:7  FlutterTestEnvironment.tearDownEnvironment.<fn>
```

All three of them have the `_Timer._cancelWakeup` error from above in their logs (two of them very close to this failure, the other one in an earlier test). I can't be sure it's related, but I haven't seen it in any runs that didn't fail yet, so my suspicion is that when it happens, something breaks and remains broken afterwards.

**Comment by DanTup** [comment] 2019-03-25 11:24
With the timer issue fixed, we still see these failures (though without those errors logged):

https://travis-ci.org/DanTup/devtools/jobs/510901770

I don't know if that makes them unrelated, but it'll need more digging!

**Comment by DanTup** [comment] 2019-03-25 16:59
@jacob314 here's an example of some failures (from the link above):

```
00:20 +4: test/inspector_controller_test.dart: inspector controller tests (tearDownAll)
00:41 +4 -1: test/inspector_controller_test.dart: inspector controller tests (tearDownAll) [E]
  Timed out waiting for futures to complete. 1 futures remained:
  
    callServiceExtension ext.flutter.inspector.getDetailsSubtree.160
  test/support/flutter_test_environment.dart 100:7  FlutterTestEnvironment.tearDownEnvironment.<fn>
  ===== asynchronous gap ===========================
  dart:async                                        Future.timeout
  test/support/flutter_test_environment.dart 98:47  FlutterTestEnvironment.tearDownEnvironment
  ===== asynchronous gap ===========================
  dart:async                                        _asyncThenWrapperHelper
  test/support/flutter_test_environment.dart        FlutterTestEnvironment.tearDownEnvironment
  test/inspector_controller_test.dart 336:17        main.<fn>.<fn>
```

I don't know much about `getDetailsSubtree`, but maybe you can think of a reason it wouldn't complete?

**Comment by jonahwilliams** [comment] 2019-03-25 17:02
I can reliably trigger dart-lang/sdk#33838 if you're still looking for root causes

**Comment by jonahwilliams** [comment] 2019-03-25 17:04
Run flutter gallery with all assets commented out. Uncomment all assets and hot reload, you'll hit it 100% of the time. This causes us to try and upload all 40 something MB of assets to the device.

**Comment by DanTup** [comment] 2019-03-25 17:05
@jonahwilliams that issue should be fixed in latest Flutter master - are you still seeing it? (for us, that error is gone, though our tests are still flaking - we're unsure of the cause yet)

**Comment by kenzieschmoll** [comment] 2024-10-17 20:54
closing as obsolete.

**Closed by kenzieschmoll** 2024-10-17 20:54 UTC
Labels: testing
