### ISSUE TITLE
[web]The method 'toFilePath' was called on null

### ISSUE THREAD

**Issue by nttd-jieyangxu** [flutter/devtools#1752] opened 2020-03-20 03:57 UTC
I have try the beta lastest version(1.15.17) for flutter web.but An error occurred! the chrome doesn't open.
```
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath() 
```
i try two dev versions for flutter web,that still happen! this time the chrome is opened ,but blank.

![upgrade_error](https://user-images.githubusercontent.com/62096778/77134437-f3283980-6aa1-11ea-8a07-385fc9bc7293.png)
![flutter_doctor](https://user-images.githubusercontent.com/62096778/77134441-f4f1fd00-6aa1-11ea-94ec-37f7ed60a5bb.png)

**Comment by jonahwilliams** [comment] 2020-03-20 04:01
Duplicate of https://github.com/flutter/flutter/issues/52914

**Closed by jonahwilliams** 2020-03-20 04:01 UTC

**Comment by AttSee** [comment] 2020-03-20 08:42
Launching lib/main.dart on Chrome in debug mode...
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
Exited (sigterm)

1.15.17 beta

**Comment by ajeetv300** [comment] 2020-06-25 09:21
Please guide me for such issue in flutter run -d chrome

GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core

**Comment by rajeshrdev04** [comment] 2020-08-17 21:11
I run this command **flutter update-packages** and its works for me
