### ISSUE TITLE
Flutter Inspector not showing the actual code on my editor

### ISSUE THREAD

**Issue by jishkln** [flutter/devtools#6565] opened 2023-10-20 10:28 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.1.3
Flutter Version: 3.13.7 / stable
Framework / Engine: 2f708eb839 / a794cf2681
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment] 2023-10-20 16:37
Are you using VS code or IntelliJ / Android Studio?

**Comment by jishkln** [comment] 2023-10-20 18:02
I'm using Android studio,
Sir my issue is,
In the old version of flutter inspector i was been navigated to its source
code by touching anywhere in the screen.
But in the new updated version of flutter inspector i am not provided with
this facility and not being directed to the source code
It would be highly appreciated if could guide  me through this dilemma

**Comment by kenzieschmoll** [comment] 2023-10-20 18:36
Closing as a duplicate of the above linked issue. A new version of the Flutter-IntelliJ plugin is expected to be released next week with a fix.

**Closed by kenzieschmoll** 2023-10-20 18:36 UTC
Labels: inspector page

**Comment by jishkln** [comment] 2023-10-21 03:52
Great!
