### ISSUE TITLE
Network is not showing most of the time 

### ISSUE THREAD

**Issue by yasaleo** [flutter/devtools#8520] opened 2024-11-13 06:33 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.3
Flutter Version: 3.24.3 / stable
Framework / Engine: 2663184aa7 / 36335019a8

**Comment by zigapovhe** [comment] 2024-11-15 08:27
Probably duplicate of #8518

**Comment by kenzieschmoll** [comment] 2024-11-19 21:38
closing as a duplicate of https://github.com/flutter/devtools/issues/8380

**Closed by kenzieschmoll** 2024-11-19 21:38 UTC
