### ISSUE TITLE
Indicate that more data needs to be loaded after clearing all performance data 

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#5121] opened 2023-01-26 19:25 UTC
Steps to reproduce:

- Navigate to Timeline Events to get to Perfetto IFRAME page
- Start interacting with embedded Perfetto 
- Click "Clear all data on the performance screen"
- Perfetto is cleared
- Start interacting with app once more

Expected: Events will show up in embedded Perfetto
Actual: No events show up in embedded Perfetto

![Screenshot 2023-01-26 at 11 25 23 AM](https://user-images.githubusercontent.com/21270878/214930815-fddedb8f-8b5a-463a-b414-267cb3cc3c45.png)

**Comment by kenzieschmoll** [comment] 2023-05-26 23:08
closing as duplicate of https://github.com/flutter/devtools/issues/4884

**Closed by kenzieschmoll** 2023-05-26 23:08 UTC
Labels: performance page, P4, performance page > perfetto
