### ISSUE TITLE
Sidebar should not show devtools release notes.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#7031] opened 2024-01-09 02:17 UTC
<img width="483" alt="Screenshot 2024-01-08 at 6 17 05 PM" src="https://github.com/flutter/devtools/assets/12115586/ae4012a3-ad7b-4dd5-b678-39dd1714ccef">

**Comment by kenzieschmoll** [comment] 2024-01-09 21:27
closing as a dupe of https://github.com/flutter/devtools/issues/6958

**Closed by kenzieschmoll** 2024-01-09 21:27 UTC
