### ISSUE TITLE
[DevTools] Easier way to determine which part of the Theme a color comes from

### ISSUE THREAD

**Issue by hanskokx** [flutter/devtools#4441] opened 2022-09-04 00:31 UTC
## Use case

When building out a `ColorScheme` class, I want to be sure to set the correct colors for things like the scaffold background. I _thought_ I had set the correct property, but when I ran my app, I found that I was wrong. I opened DevTools to see if it would tell me which `ColorScheme` property it was using (or if it was overridden manually), but found nothing.

## Proposal

When using DevTools to inspect a widget, I would like to know which part of the `Theme` has set the color and if that color was overridden as a property.

**Comment by kenzieschmoll** [comment] 2022-09-06 22:59
closing as a duplicate of https://github.com/flutter/devtools/issues/483

**Closed by kenzieschmoll** 2022-09-06 22:59 UTC
Labels: inspector page, P4
