### ISSUE TITLE
Flutter theme inspector

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#5688] opened 2023-04-20 08:37 UTC
Moving from https://github.com/Dart-Code/Dart-Code/issues/4465:

---
@leighajarett:

When using themes with Flutter, it's sometimes difficult to know where inherited properties are coming from. Additionally, changing the theme requires a hot restart which means that it can take a while for developers to troubleshoot on their own.

It would be great to have some visual way to see property inheritance. We could do something similar to the chrome devtools approach, or we could explore a more graphical interface.

---

@jacob314:

This should probably be moved to the DevTools issue tracker. Even if the UI is surfaced in VSCode it should definitely be implemented in DevTools.

---

**Comment by kenzieschmoll** [comment] 2023-04-20 18:37
Closing as a duplicate of https://github.com/flutter/devtools/issues/483

**Closed by kenzieschmoll** 2023-04-20 18:37 UTC

**Comment by DanTup** [comment] 2023-04-20 18:44
Whoops, didn't search. Thanks!
