### ISSUE TITLE
cannot open timeline

### ISSUE THREAD

**Issue by melancholyboy** [flutter/devtools#6011] opened 2023-07-11 06:00 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.0.5
Flutter Version: 3.10.5 / stable
Framework / Engine: 796c8ef792 / 45f6e00911
Connected app type: Flutter native (profile build)

RPCError: getVMTimeline: (114) The timeline related request could not be completed due to the current configuration
A recorder of type "Systrace" is currently in use. As a result, timeline events are handled by the OS rather than the VM. See the VM service documentation for more details on where timeline events can be found for this recorder type.

**Comment by kenzieschmoll** [comment] 2023-07-11 16:57
Looks like you are running your app with the systrace. I'm going to close this issue as a duplicate of https://github.com/flutter/devtools/issues/3800. 

But in the meantime, @dnfield are there instructions somewhere for how to load a systrace file from Flutter into ui.perfetto.dev?

**Closed as completed by kenzieschmoll** 2023-07-11 16:57 UTC
