### ISSUE TITLE
Reporting error: Failed to parse package:apeg/view/suchen.dart.

### ISSUE THREAD

**Issue by MeMehralian** [flutter/devtools#8099] opened 2024-07-25 11:47 UTC
Stack trace:
main.dart.js 6395:18    Object.o4
main.dart.js 72602:76   <fn>
main.dart.js 4991:63    bKq.a
main.dart.js 61174:14   bKq.$2
main.dart.js 61168:21   bIb.$1
main.dart.js 5276:19    Object.bK4
main.dart.js 176828:10  amW.<fn>
main.dart.js 62370:12   a1s.th
main.dart.js 61696:11   bud.$0
main.dart.js 5157:40    Object.OW

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.36.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.0-180.3.beta
Flutter Version: 3.23.0-0.1.pre / beta
Framework / Engine: 2feea7a407 / bb10c54666

**Comment by kenzieschmoll** [comment] 2024-07-31 20:44
closing as a duplicate of https://github.com/flutter/devtools/issues/7192

**Closed by kenzieschmoll** 2024-07-31 20:44 UTC
