### ISSUE TITLE
`GA_DEVTOOLS_PROPERTY` is not defined error when running DevTools in VS Code

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#7077] opened 2024-01-22 18:04 UTC
I'm getting an error for a missing analytics property when running a local version of DevTools in VS Code:

![Screenshot 2024-01-22 at 9 41 10 AM](https://github.com/flutter/devtools/assets/21270878/42afe107-3e95-4877-b26c-0980c666c9f7)

I've set my `settings.json` to use my local DevTools:

```
  "dart.customDevTools": {
    "path": "/Users/elliottbrooks/dev/devtools",
    "env": {
        "LOCAL_DART_SDK": "/Users/elliottbrooks/dev/dart-sdk/sdk",
    }
  }
```

Then running:
- `Developer: Reload window`
- `Developer: Toggle Developer Tools`
- Run and debug a Flutter app 

The Flutter sidebar also doesn't load (not sure if this is related to the missing GA property)

![Screenshot 2024-01-22 at 9 49 32 AM](https://github.com/flutter/devtools/assets/21270878/fc9d59ce-beac-4da3-9712-91887f5ee4c6)

Fyi @kenzieschmoll @DanTup

**Comment by DanTup** [comment] 2024-01-22 18:10
Seems like this would be set at https://github.com/flutter/devtools/blob/master/packages/devtools_app/web/index.html#L26

Can you test if you see the same if you run `devtools_app serve`? (that's basically what Dart-Code is doing when you set a custom DevTools config as above)

**Comment by kenzieschmoll** [comment] 2024-01-22 18:14
I don't see anything in the DevTools repo called GA_DEVTOOLS_PROPERTY. We used to have this constant before it was changed to DEVTOOLS_GOOGLE_TAG_ID in https://github.com/flutter/devtools/commit/f3fe666d7270242a55a83106a4562c9af1038204. @DanTup is there some code in the Dart-Code plugin that is trying to read this constant?

**Comment by DanTup** [comment] 2024-01-22 18:21
Oops, I didn't notice the thing I linked had a different name (I fond it via a PR so maybe it was renamed).

There's nothing in Dart-Code that tries to read this (and the stack shows `main.dart.js`). My guess would be some kind of caching issue, although since something about DTD is printed further up, that seems unlikely.

@elliette is it possible you can click on "main.dart.js" and search for both that constant name and the DTD string to see if they're in there? Seems like these two things would never have been in the same version of the DevTools code?

**Comment by elliette** [comment] 2024-07-10 21:01
Assigning back to me to see if I can repro, will close if not

**Comment by kenzieschmoll** [comment] 2024-10-30 21:24
Cannot reproduce. Closing.

**Closed by kenzieschmoll** 2024-10-30 21:24 UTC
Labels: fix it friday, P3, reproduce to verify
