### ISSUE TITLE
Breakpoints are not hit for macos apps after hot restart or hot reload

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#3359] opened 2021-09-10 23:31 UTC
**Repro steps**

1. run flutter hello_world app for macos platform: 
 ```
   cd flutter/flutter/examples/hello_world
   flutter run --debug -d macos
```
2. run devtools
    `pub global run devtools`
3. connect devtools to the app by copying and pasting the app debug uri into devtools connection box
4. when source for `main.dart` is displayed in the debugger screen, put a breakpoint on `runApp` line and hot restart or hot reload.

**Expected** 
Breakpoint is hit when the app re-runs.

**Actual**
Breakpoint is not hit. In addition, breakpoint disappears after hot restart.

**Versions**
Devtools: 2.6.0

**flutter doctor -v**

➜  hello_world git:(annagrin/update_dwds) ✗ flutter doctor -v
[✓] Flutter (Channel annagrin/update_dwds, 2.6.0-1.0.pre.245, on macOS 11.5.1 20G80
    darwin-x64, locale en-US)
    • Flutter version 2.6.0-1.0.pre.245 at /Users/annagrin/source/flutter/flutter
    • Upstream repository git@github.com:annagrin/flutter.git
    • Framework revision 26db5554fd (26 hours ago), 2021-09-09 14:48:19 -0700
    • Engine revision 825c409164
    • Dart version 2.15.0 (build 2.15.0-93.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/annagrin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.

**Comment by jacob314** [comment] 2021-09-20 15:59
Fyi @elliette 
This used to work but some of the lifecycle management in the debugger page of the servicemanager sounds like it is broken.

**Comment by elliette** [comment] 2021-09-20 16:37
Just confirmed that it's not due to https://github.com/flutter/devtools/pull/3309 which I thought was the most likely suspect (reverted https://github.com/flutter/devtools/pull/3309 and was still able to reproduce). Will keep investigating.

**Comment by elliette** [comment] 2021-09-20 17:44
Confirmed that this doesn't seem to be a regression (or at least not a recent one, I was able to reproduce as far back as DevTools v2.2.0):

1. `flutter pub global activate devtools 2.2.0`
2. `flutter pub global run devtools`

Will need to look further to determine what exactly is happening on macos to cause DevTools to lose the breakpoints.

**Comment by elliette** [comment] 2023-06-26 21:42
Closing in favor of https://github.com/flutter/devtools/issues/5265

**Closed by elliette** 2023-06-26 21:42 UTC
Labels: bug, debugger page
