### ISSUE TITLE
Dart Devtools not working after update.

### ISSUE THREAD

**Issue by azad47808** [flutter/devtools#2125] opened 2020-06-25 04:10 UTC
This morning when I run Devtools I got an updating message and after update DevTools opened but shows nothing.
this is my Devtools URL = http://127.0.0.1:9100/#?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A49683%2F7P9jVJjp0SU%3D%2F&page=inspector

My Flutter version is 1.19.0-4.1.pre
My Dart version is  2.9.0 (build 2.9.0-14.1.beta).

**Comment by devoncarew** [comment] 2020-06-25 15:56
How are your starting DevTools - from the command line, VS Code, IntelliJ?

**Comment by bleonard252** [comment] 2020-06-28 17:55
According to the link, VSCode. I'm experiencing the same thing running from the command line.
```
Another exception was thrown: Instance of 'minified:il<void>'
```
is being logged a lot.

**Comment by azad47808** [comment] 2020-06-29 04:06
> How are you starting DevTools - from the command line, VS Code, IntelliJ?

From the VS Code.

**Comment by AlexanderTopchiy** [comment] 2020-06-30 09:31
I have the same problem with the same configurations (Flutter 1.19.0-4.2.pre, Dart 2.9, VS Code 1.46.1) after recent update DevTools.
Also, it doesn't work from Android Studio 4.0 too. Both on Linux Debian 9.11.
What happened?

**Comment by ezbella** [comment] 2020-07-03 18:43
Same problem over here too. Tons of recurring exceptions:
"Another exception was thrown: Instance of 'minified:im<void>'" Could not load content for org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_primitives.dart (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME). 

The app works perfectly fine in vs code on the device.

flutter doctor -v
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 6.1.7601], locale es-AR)
    • Flutter version 1.17.4 at c:\flutter
    • Framework revision 1ad9baa8b9 (2 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\xxx\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
    • Moto E 4 Plus • ZY2248P828 • android-arm • Android 7.1.1 (API 25)

• No issues found!

**Comment by azad47808** [comment] 2020-07-05 09:35
> How are you starting DevTools - from the command line, VS Code, IntelliJ?

Can I downgrade Dart Devtools?

**Comment by kenzieschmoll** [comment] 2020-07-06 17:19
Can you open DevTools from CLI? `flutter pub global activate devtools; devtools`

Trying to narrow this down to determine if the issue is specific to launching from VS code. Thanks.

**Comment by DanTup** [comment] 2020-07-06 18:24
From [this comment above](https://github.com/flutter/devtools/issues/2125#issuecomment-651678773) it sounds like this may occur from Android Studio too.

Could it be caching from the old version? Does pressing Ctrl+R in the browser make any difference for those seeing this?

**Comment by bleonard252** [comment] 2020-07-06 23:40
> Could it be caching from the old version? Does pressing Ctrl+R in the browser make any difference for those seeing this?

No, I haven't used DevTools in Chrome yet. I tried with Firefox and that didn't work (Firefox error).

**Comment by azad47808** [comment] 2020-07-07 04:46
> Can you open DevTools from CLI? `flutter pub global activate devtools; devtools`
> 
> Trying to narrow this down to determine if the issue is specific to launching from VS code. Thanks.

I used these two commands but not worked it's just a white page.

1: flutter pub global activate devtools
2: flutter pub global run devtools

**Comment by AlexanderTopchiy** [comment] 2020-07-07 06:55
> Can you open DevTools from CLI? `flutter pub global activate devtools; devtools`
> 
> Trying to narrow this down to determine if the issue is specific to launching from VS code. Thanks.

I used this command before and now - still white page. (at http://127.0.0.1:9100)
Both from VS Code and Android Studio.
In Android Studio I can use embedded Flutter tabs - Inspector, Outline, Performance. And that's it.

**Comment by kenzieschmoll** [comment] 2020-07-07 15:30
A couple things to try:
- make sure you are using the latest version of Chrome
- clear your browser cache

Are you running from Mac, Linux, or Windows?

**Comment by ezbella** [comment] 2020-07-07 15:35
I have the latest Chrome version, specially downloaded for the occasion.
I've tried everything you suggested with no luck

**Comment by kenzieschmoll** [comment] 2020-07-07 15:46
Try appending '/#/' to the end of the url so that the url looks like `http://127.0.0.1:9100/#/`. The redirect is supposed to happen automatically.

**Comment by ezbella** [comment] 2020-07-07 15:50
Tried it but did not work.
The url:
http://127.0.0.1:9100/#/?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A1485%2FtNRtGiM-E6k%3D%2F#

**Comment by kenzieschmoll** [comment] 2020-07-07 15:56
Try `http://127.0.0.1:9100/#/?uri=http%3A%2F%2F127.0.0.1%3A1485%2FtNRtGiM-E6k%3D%2F`

if that doesn't work try `http://127.0.0.1:9100/#/` without any query parameters, and paste your URI into the connect dialog if it shows up `http://127.0.0.1:1485/tNRtGiM-E6k=/`

**Comment by ezbella** [comment] 2020-07-07 17:01
![image](https://user-images.githubusercontent.com/55261954/86816437-31019b80-c05a-11ea-8d3b-79bfb7917d1e.png)

Not working in any case :(

**Comment by ezbella** [comment] 2020-07-07 17:27
![image](https://user-images.githubusercontent.com/55261954/86819192-ae7adb00-c05d-11ea-8bd7-3ec3cb01aa78.png)

With the last url you provided I could access the observatory, and now I can see at least this info of my app. But still without being able to access devtools...

**Comment by elansys-kc** [comment] 2020-07-09 09:57
I have the same issue on Windows.

**Comment by heroqin** [comment] 2020-07-10 14:13
I have the same problem, nothing output in chrome browser:
![图片](https://user-images.githubusercontent.com/48232744/87163703-5ad8ed80-c2fa-11ea-8ff9-1081dde2ca04.png)

status bar in VSCode is as following:
![图片](https://user-images.githubusercontent.com/48232744/87163811-8360e780-c2fa-11ea-8082-ad8148ee5104.png)

**Comment by DanTup** [comment] 2020-07-13 19:50
I had a go at trying to repro on Windows, and could not. However I definitely saw some weird caching behaviour...

I first activated 0.2.5 and loaded and refreshed that. Then I activated 0.8.0+1, opened my browser and pasted in the URL. It loaded the old version of the app entirely:

![devtools_1](https://user-images.githubusercontent.com/1078012/87346816-15126400-c54a-11ea-8620-3c8ab22be93c.png)

I pressed F5 to refresh, and it still showed the old version:

![devtools_2_after_f5](https://user-images.githubusercontent.com/1078012/87346840-1e9bcc00-c54a-11ea-86f7-d0b6c3490bda.png)

I pressed F5 a second time, and the new version loaded:

![devtools_3_after_f5_again](https://user-images.githubusercontent.com/1078012/87346873-28253400-c54a-11ea-8039-ed2d4ff402ca.png)

I tried a few times but couldn't repro the error above - though I wonder if it's possible for some of the files to come from the cache and not all?

To those that can reproduce this reliably - if you deliberately run on a different port, eg:

```
pub global run devtools --port 9120
```

does this make any difference?

**Comment by heroqin** [comment] 2020-07-14 02:46
When I execute 'pub global run devtools --port 9120', it says:
![图片](https://user-images.githubusercontent.com/48232744/87377679-b3d8a800-c5be-11ea-84df-b9a65fdb4d4a.png)

**Comment by heroqin** [comment] 2020-07-14 02:55
I use the following command instead:
![图片](https://user-images.githubusercontent.com/48232744/87378410-4e85b680-c5c0-11ea-93f6-5546c6e8e5a9.png)
and open chrome: http://127.0.0.1/#/, but it still output blank:
![图片](https://user-images.githubusercontent.com/48232744/87378455-66f5d100-c5c0-11ea-841f-c454b81442c3.png)

**Comment by elansys-kc** [comment] 2020-07-14 10:01
It runs from the commandline, when I follow these instructions but not from vscode or Android studio.
https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md

I often get run -d chrome|edge failures like the following which makes me wonder if a timeout is occurring and if a timeout could be happening on devtools that might affect the GUI tools more without the manual steps?

My machine is older without an SSD, does anyone with this issue have a newer machine, with an SSD?

________________________________________________________________________________________________

PS C:\flutter_proj\review> cd gallery
PS C:\flutter_proj\review\gallery> flutter run -d edge
Running "flutter pub get" in gallery...                            73.1s
Launching lib\main.dart on Edge in debug mode...
Syncing files to device Edge...
119,368ms (!)
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to
a firewall.
PS C:\flutter_proj\review\gallery> flutter run -d edge
Launching lib\main.dart on Edge in debug mode...
Syncing files to device Edge...
83,968ms (!)
Debug service listening on ws://127.0.0.1:51696/sQjV4xXUWZU=

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

**Comment by jacob314** [comment] 2020-07-15 00:59
I've uploaded devtools 0.8.0+2 which should provide a slightly better error message as minification is turned off. Please let me know if you are able to reproduce the error while running 0.8.0+2. The error message may help us debug the issue.

**Comment by heroqin** [comment] 2020-07-15 03:54
@jacob314 I upgraded devtools version to 0.8.0+2, and tried it, but still nothing output. but where can I get the error message?
By the way, I try to telnet 127.0.0.1 9100, it did response.
![图片](https://user-images.githubusercontent.com/48232744/87501473-bce67980-c691-11ea-90c0-269247b238ba.png)

**Comment by DanTup** [comment] 2020-07-15 08:14
@heroqin the error will show in the Chrome developer tools. To open them, press `F12` in the blank Chrome window and then click the `Console` tab and there's probably a red error message. Please post that message here - hopefully it will be more helpful than the minified one.

**Comment by heroqin** [comment] 2020-07-15 08:25
![图片](https://user-images.githubusercontent.com/48232744/87521889-87548700-c6b7-11ea-8354-9d2e3bfdf64c.png)
the number before "Another exception was thrown: Instance of 'ErrorSummary'" is added 1 per second:
![图片](https://user-images.githubusercontent.com/48232744/87522044-b9fe7f80-c6b7-11ea-96f6-1fad297064db.png)
![图片](https://user-images.githubusercontent.com/48232744/87522070-c1258d80-c6b7-11ea-96cd-c3d5255d48ed.png)
![图片](https://user-images.githubusercontent.com/48232744/87522100-c97dc880-c6b7-11ea-879a-2ca41486e166.png)

**Comment by DanTup** [comment] 2020-07-15 09:33
@heroqin could you try clicking on the Sources tab in those developer tools, then on the right side ticking the box that says "Pause on caught exceptions" and see whether that causes the debugger to break? If so, please include a screenshot (including the Call Stack and exception info).

**Comment by ezbella** [comment] 2020-07-15 13:31
Hi @DanTup, I'm attaching the screenshot you requested. Tell me if you need anything else.

![image](https://user-images.githubusercontent.com/55261954/87550879-ee594800-c685-11ea-8f38-7179db8ac087.png)

![image](https://user-images.githubusercontent.com/55261954/87551123-4001d280-c686-11ea-9a90-2c269b819cb2.png)

**Comment by heroqin** [comment] 2020-07-15 13:33
![图片](https://user-images.githubusercontent.com/48232744/87551268-b2a09b80-c6e2-11ea-994b-9057d1c3f791.png)

**Comment by jacob314** [comment] 2020-07-15 19:55
@hterkelsen any advice on what we can do to avoid this crash in CanvasKit. Surprisingly it only reproduces for some users.

**Comment by jacob314** [comment] 2020-07-15 20:14
It appears that creating a webgl context may be failing. Do any WebGL apps work in your browser? For example: can you pleas try a sample from https://webglsamples.org/

**Comment by ezbella** [comment] 2020-07-15 21:45
I've tried 5 random samples. Every one of them worked.

![image](https://user-images.githubusercontent.com/55261954/87601258-20d96400-c6cb-11ea-8441-453eba0f4c20.png)

**Comment by jacob314** [comment] 2020-07-16 18:35
Thanks for all your help debugging this. One more test to try:
https://flutter-dashboard.appspot.com/#/build
is also a canvaskit based flutter web app. Do you get the same exception when you run it or do  you see something like this?
<img width="902" alt="Screen Shot 2020-07-16 at 11 35 15 AM" src="https://user-images.githubusercontent.com/1226812/87709018-77d94a80-c758-11ea-87da-5f20d61b9dbf.png">

**Comment by yjbanov** [comment] 2020-07-16 20:13
@DanTup I think what you are observing is an issue with the service worker caching a little too aggressively. You may need a _hard_ page reload to get the latest version (Cmd + Shift + R, or Ctrl + Shift + R).

**Comment by jacob314** [comment] 2020-07-16 20:40
@yjbanov, Is there a bug filed on the service working caching too aggressively? I'm guessing we want to use the service worker to make sure canvaskit is cached efficiently but we don't care about it for the rest of the appp as we are always running on localhost.

**Comment by ezbella** [comment] 2020-07-16 23:33
@jacob314 A pleasure to help. Thank you guys for these amazing features!
Same error is throwing in the web flutter app.

![image](https://user-images.githubusercontent.com/55261954/87732500-8b5dd300-c7a3-11ea-8b92-7a41b16451a4.png)

**Comment by jacob314** [comment] 2020-07-17 02:59
Thanks @ezbella!
Can you provide some more details about what version of chrome you are using, what operating system you are running, and what video card you are using? 
You might want to try disabling all extensions just in case some extension is interacting badly with CanvasKit but that is unlikely.

fyi @hterkelsen it is confirmed that CanvasKit fails for all Flutter Web applications but strangely other WebGL samples succeed.

The next step on our end is to detect this crash and and fallback to the non-canvaskit renderer which is slower but works on more platforms.

**Comment by heroqin** [comment] 2020-07-17 06:27
Hi @jacob314 I've test https://flutter-dashboard.appspot.com/#/build, in chrome, nothing output and error got:
![图片](https://user-images.githubusercontent.com/48232744/87755168-1806a080-c839-11ea-89c2-58427b9d32f4.png)

but in firefox, it seems normal! :
![图片](https://user-images.githubusercontent.com/48232744/87754721-20aaa700-c838-11ea-8bfd-051356b9f47f.png)

chrome version: 版本 84.0.4147.89（正式版本） （64 位）
OS:
![图片](https://user-images.githubusercontent.com/48232744/87755289-4dab8980-c839-11ea-9a6e-12307ea57620.png)
video card: 
![图片](https://user-images.githubusercontent.com/48232744/87755383-76cc1a00-c839-11ea-85d5-2dbfee15bb11.png)
I think chrome use Intel HD graphic 520

**Comment by heroqin** [comment] 2020-07-17 06:37
Since firefox work well on https://flutter-dashboard.appspot.com/#/build.  I tried to open http://127.0.0.1:9100/#/ using firefox, it works! :
![图片](https://user-images.githubusercontent.com/48232744/87756156-f5758700-c83a-11ea-9394-0c8dc2310b02.png)

**Comment by ezbella** [comment] 2020-07-17 13:54
hi @jacob314! i share the info you requested:
_Chrome_: (btw not using any extension, just a clean installation) 
![image](https://user-images.githubusercontent.com/55261954/87792670-9acc3300-c81a-11ea-9de0-8d729834f474.png)

_Windows Version:_
flutter doctor -v
[√] Flutter (Channel stable, v1.17.4, on **Microsoft Windows [Version 6.1.7601],** locale es-AR)
• Flutter version 1.17.4 at c:\flutter
• Framework revision 1ad9baa8b9 (2 weeks ago), 2020-06-17 14:41:16 -0700
• Engine revision ee76268252
• Dart version 2.8.4

_Video Card:_ (running on a Lenovo T430 series)
![image](https://user-images.githubusercontent.com/55261954/87793207-568d6280-c81b-11ea-8e73-e718ac033e7f.png)

As a side note, i tried what @heroqin suggested and the flutter web app also worked in firefox.

**Comment by jacob314** [comment] 2020-07-17 14:07
Thanks @ezbella and @heroqin. That is great news that it works on FireFox. We'll make devtools detect the error and provide an option to relaunch the app in FireFox if it occurs.

**Comment by ezbella** [comment] 2020-07-17 16:51
@jacob314 You are mosltly welcome! Just ask if you need anything else.

**Comment by ynaiborlang** [comment] 2020-07-19 20:23
hi @jacob314  https://flutter-dashboard.appspot.com/#/build does not work on firefox for me,  got the same console error,

**Comment by azad47808** [comment] 2020-07-20 05:17
I changed my windows, but still not working.

**Comment by jacob314** [comment] 2020-07-20 17:18
@azad47808 sorry to hear that. Can you provide details on your chrome version, operating system, and machine (e.g Lenovo T430)? Can you also provide a screenshot of what errors you see in chrome devtools when Dart DevTools does not work correctly? It could be you are seeing a different issue.

**Comment by elansys-kc** [comment] 2020-07-21 20:52
Mines a T410. I had exactly the same error on Windows as on Linux.

In firefox on Linux I get

Loading failed for the <script> with source “https://unpkg.com/canvaskit-wasm@0.16.2/bin/canvaskit.js”

I now get different console output on Linux with Chrome Version 84.0.4147.89.

The FetchEvent for "https://unpkg.com/canvaskit-wasm@0.16.2/bin/canvaskit.js" resulted in a network error response: the promise was rejected.
Promise.then (async)		
(anonymous)	@	flutter_service_worker.js:389
flutter_service_worker.js:1 

Uncaught (in promise) TypeError: Failed to fetch
dom_renderer.dart:443 

GET https://unpkg.com/canvaskit-wasm@0.16.2/bin/canvaskit.js net::ERR_FAILED
reset$0	@	dom_renderer.dart:443
(anonymous)	@	dom_renderer.dart:14
holder.<computed>	@	main.dart.js:99
initializeEngine	@	engine.dart:184
(anonymous)	@	initialization.dart:29
(anonymous)	@	async_patch.dart:315
call$2	@	async_patch.dart:340
_asyncStartSync	@	async_patch.dart:245
_initializePlatform	@	initialization.dart:25
webOnlyInitializePlatform	@	initialization.dart:12
(anonymous)	@	main.dart:11
(anonymous)	@	async_patch.dart:315
call$2	@	async_patch.dart:340
_asyncStartSync	@	async_patch.dart:245
main0	@	main.dart:8
(anonymous)	@	js_helper.dart:2677
(anonymous)	@	js_helper.dart:2677
dartProgram	@	js_helper.dart:2677
(anonymous)	@	js_helper.dart:2677

**Comment by elansys-kc** [comment] 2020-07-21 20:59
Ignore deleted previous. I had a js filter extension enabled (umatrix)

Mines a T410. I had exactly the same error on Windows as on Linux.

In firefox on Linux I get

Another exception was thrown: Instance of 'ErrorSummary' main.dart.js:5574:17
Error: WebGL warning: <SetDimensions>: Failed to create WebGL context: WebGL creation failed: 
* tryNativeGL
* Exhausted GL driver options. 3 canvaskit.js:187:32
Another exception was thrown: Instance of 'ErrorSummary' main.dart.js:5574:17
Error: WebGL warning: <SetDimensions>: Failed to create WebGL context: WebGL creation failed: 
* tryNativeGL
* Exhausted GL driver options.


I now get different console output on Linux with Chrome Version 84.0.4147.89.

PreferencesController: storage not initialized
logger_html.dart:10 
DevTools version 0.8.0+2.
js_helper.dart:1857 [Violation] 'setTimeout' handler took 437ms
js_primitives.dart:47 ══╡  ╞══════════════════════════════════════════════════════════════════════════════════════════════
js_primitives.dart:47 ════════════════════════════════════════════════════════════════════════════════════════════════════
js_helper.dart:1857 [Violation] 'setTimeout' handler took 153ms
html_dart2js.dart:23739 [Violation] Only request notification permission in response to a user gesture.
Notification__requestPermission @ html_dart2js.dart:23739
Notification_requestPermission @ html_dart2js.dart:23745
_handleMethod$2 @ notifications_web.dart:15
_handleMessage$1 @ server_api_client.dart:116
call$1 @ server_api_client.dart:22
runUnaryGuarded$1$2 @ zone.dart:1384
runUnaryGuarded$2 @ zone.dart:1381
_sendData$1 @ stream_impl.dart:357
perform$1 @ stream_impl.dart:611
handleNext$1 @ stream_impl.dart:730
call$0 @ stream_impl.dart:687
_microtaskLoop @ schedule_microtask.dart:41
_startMicrotaskLoop @ schedule_microtask.dart:50
call$1 @ async_patch.dart:49
invokeClosure @ js_helper.dart:1825
(anonymous) @ js_helper.dart:1857
6js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
250[Violation] 'requestAnimationFrame' handler took <N>ms
8js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
2js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
js_helper.dart:1857 [Violation] 'setTimeout' handler took 150ms
4218js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'

**Comment by azad47808** [comment] 2020-07-22 04:20
I don't know, What happened but now it working right.

**Comment by elansys-kc** [comment] 2020-07-22 08:27
Disabling hw acceleration in Chrome under advanced settings, works around it. Might be the better fix for other possibly broken canvas pages too, not sure?

On a side note, on the same hw flutter development was a little slow waiting for the files to sync to chrome without an SSD. Not sure if Linux being configured to handle smaller files would have helped there or not. This might be a performance metric that goes unnoticed by devs. I think that SSD use may have worsened the HDD case for windows update speed issues, incidentally.

**Comment by RahmatAliMalik5** [comment] 2020-07-22 08:30
I am also getting white screen when try to open the `devtools`. Here are the info you may find usefule:

Chrome Version: 84.0.4147.89 (Official Build) (64-bit)

Console: 
![image](https://user-images.githubusercontent.com/31620469/88153588-0b11f480-cc1f-11ea-9060-2e08440e876a.png)

Error in Source Panel:
![image](https://user-images.githubusercontent.com/31620469/88153901-7bb91100-cc1f-11ea-8dc4-390141a9e9ae.png)

I have disabled all of the extensions in chrome. Let me know if anyone requires more info.

**Comment by RahmatAliMalik5** [comment] 2020-07-22 08:36
As @elansys-kc, suggested. Disabling Hardware Acceleration in Advanced Settings making it work fine.

**Comment by AlexanderTopchiy** [comment] 2020-07-23 09:08
> I have the same problem with the same configurations (Flutter 1.19.0-4.2.pre, Dart 2.9, VS Code 1.46.1) after recent update DevTools.
> Also, it doesn't work from Android Studio 4.0 too. Both on Linux Debian 9.11.
> What happened?

As @elansys-kc mentioned, disabling Hardware acceleration in Advanced settings - is the appropriate workaround.

**Comment by jacob314** [comment] 2020-07-23 16:59
We've published devtools 0.8.0+3 which adds an automatic fallback to a non CanvasKit version of Flutter Web if we detect that Flutter is having problems. You will now see a dialog asking if you are ok with opening the fallback version of DevTools that uses Flutter Web but not CanvasKit. Please let me know if it works for you. When I test locally, the performance of the non-CanvasKit version is worse than the CanvasKit version but significantly better than the performance of the CanvasKit version when hardware acceleration is disabled.
You can also manually open the fallback version by opening
`http://localhost:9100/index_fallback.html#/`

**Comment by elansys-kc** [comment] 2020-07-24 22:57
I can confirm that with hw accel enabled, it asks and then works for me.
Thanks Everyone

**Comment by yjbanov** [comment] 2020-08-07 19:32
I recently discovered that due to some hardware/OS/driver reasons Chrome disables WebGL 2 and falls back to WebGL 1. Due to a bug we'd assume that in this situation WebGL is not supported at all.

Unfortunately I don't have a Windows 7 computer that demonstrates this, but I saw it on a Moto E5 phone. The fix is coming in https://github.com/flutter/flutter/pull/63153. I'd be curious if it fixes the Windows issue as well.

**Comment by yjbanov** [comment] 2020-08-11 00:40
https://github.com/flutter/flutter/pull/63153 has landed. Can you please verify if this is still an issue?

**Comment by ezbella** [comment] 2020-08-11 01:46
It is working for me with the fallback workaround in chrome. Thanks !

**Comment by yjbanov** [comment] 2020-08-13 18:06
@ezbella Do you know if it's falling back to WebGL1 or HTML?

**Comment by ezbella** [comment] 2020-08-13 18:23
If you tell me how to figure it out i will check and tell you.

**Comment by yjbanov** [comment] 2020-08-17 20:41
We should provide a better way to do it, but right now you can get this information using Chrome DevTools.

If the `<flt-scene>` element has one `<canvas>` child and nothing else, then you are using CanvasKit. If there's no warning in the console reading "WARNING: failed to initialize WebGL. Falling back to CPU-only rendering.", then the canvas is hardware-accelerated using WebGL; otherwise, it's rendered using CPU (and probably is visibly slow).

If you see `<flt-scene>` containing many elements, such as `<flt-offset>`, `<flt-transform>`, or `<flt-picture>`, then you are using the HTML renderer.

**Comment by elansys-kc** [comment] 2020-08-19 15:59
I have just a canvas inside <flt-scene>

p.s. Should an issue be filed for devtools now requiring internet access, to download canvaskit from:
"https://unpkg.com/canvaskit-wasm@0.17.2/bin/canvaskit.js"

Or is that intended?

**Comment by yjbanov** [comment] 2020-08-30 18:30
@elansys-kc Thanks for checking! We should provide an option to bundle CanvasKit with your app so you don't have to fetch it from unpkg.com. Can you please file an issue for that?

**Comment by yjbanov** [comment] 2020-09-02 15:43
Should we close this issue?

**Closed** 2020-10-23 17:37 UTC
Labels: bug
