### ISSUE TITLE
URLs do not open in VS Code 

### ISSUE THREAD

**Issue by osaxma** [flutter/devtools#6557] opened 2023-10-19 06:39 UTC
All links circled in the screenshot below are unresponsive:

<img width="963" alt="Screen Shot 2023-10-19 at 9 38 04 AM" src="https://github.com/flutter/devtools/assets/46427323/b13805bd-87f8-4bcb-9af1-99a4413c5e68">

----

devtools version: 2.25.0 (also i couldn't copy this, it'd be nice to support copying or provide a copy button next to it)
VS Code version: 1.83.1
Dart extension: v3.74.0

**Comment by kenzieschmoll** [comment] 2023-10-19 16:18
Thanks for reporting. Closing as a duplicate of two existing issues:
link behavior - https://github.com/flutter/devtools/issues/6105
copy behavior - https://github.com/flutter/devtools/issues/5775

**Closed by kenzieschmoll** 2023-10-19 16:18 UTC
