### ISSUE TITLE
I can not find the dropdown to change platform mechanics in the new devtools

### ISSUE THREAD

**Issue by nmcain** [flutter/devtools#2151] opened 2020-07-03 00:12 UTC
In previous versions there was a menu with the option to choose between Android, MacOS, Fuchsia and Linux platform mechanics, in the new Devtools it seems to have disappeared. Is there a new method to modify the mechanics of an app?

**Comment by kenzieschmoll** [comment] 2022-05-24 23:44
closing as dupe of https://github.com/flutter/devtools/issues/2780

**Closed by kenzieschmoll** 2022-05-24 23:45 UTC
Labels: bug, good first issue, inspector page
