### ISSUE TITLE
CPU Profiler breaks good code by injecting bad characters into large strings when concatenating

### ISSUE THREAD

**Issue by mkorbel1** [flutter/devtools#3201] opened 2021-07-14 18:40 UTC
Dart code that runs correctly without a profiler enabled produces incorrect results when the profiler is enabled.

Here's some relatively small code sample that reproduces the issue:
```
bool isSanitary(String name) {
  return name == sanitize(name);
}

String sanitize(String initialName) {
  var newName = initialName.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
  return newName;
}

void main(List<String> arguments) {
  print('Hello world!');
  for(var i = 0; i < 10000; i++) {
    var str = 'x';
    for(var j = 0; j < i; j++) {
      if(!isSanitary(str)) {
        print(i);
        print(j);
        print(str);
        throw Exception('not sanitary');
      }
      str += 'x';
    }
  }
}
```

When running or debugging this code without a profiler, it runs to completion with no exceptions, and just the `Hello world!` print message.

When the CPU profiler is enabled, however, this does not work.  An example output when the profiler is enabled looks like this:
![image](https://user-images.githubusercontent.com/75506197/125674341-a6a0ed8e-29f2-4384-89b3-84b144133092.png)

When I paste this into GitHub, it seems to remove the whitespace characters, so maybe they are some sort of weird character.
```
Hello world!
493
257
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

The numbers for `i` and `j` seem to be a bit random, it doesn't happen at the same time every time.

I'm running with Dart SDK version: 2.13.4 on WSL1 Ubuntu 18.04.4 LTS with Visual Studio Code.  The issue reproduces whether the CPU Profiler is opened as a tab within vscode or in a Chrome browser.

To reproduce:
- Set a breakpoint at `print('Hello world!');`
- Start debugging and wait until breakpoint is hit
- Start the CPU Profiler, "Enable profiler", and hit record
- Resume debugging
- Exception `not sanitary` will hit

**Comment by kenzieschmoll** [comment] 2021-07-15 18:21
This looks like it needs to be passed along to the SDK repo @bkonyi

**Comment by bkonyi** [comment] 2021-07-15 18:39
I'm not able to reproduce this on `master` on Linux. @mkorbel1, can you provide the exact invocation that you're using to start the program? You said you're running this in the Windows Subsystem for Linux?

**Comment by mkorbel1** [comment] 2021-07-15 19:38
Yes, I'm on Windows Subsystem for Linux (version 1, not version 2).  I'm happy to provide any additional details for my setup that you think might be relevant.

I'm invoking it via Visual Studio Code with the "debug" button that appears over `main`:
![image](https://user-images.githubusercontent.com/75506197/125847061-27943668-b905-4938-9db7-9e375b658410.png)

I found that the iteration count had to be large enough for it to reproduce.  Perhaps if you're on a more capable machine than mine you need to increase the 10000 to something larger?

**Comment by bkonyi** [comment] 2021-07-15 22:15
Are you able to reproduce when running in command prompt or powershell? It'll take me some time to get WSL setup since it's disabled on corp managed Windows machines, so I'll have to try it out on my home desktop.

Also, I'm fairly certain that launching with the `Debug` button in VSCode actually starts the process with the profiler already enabled. Are you actually seeing a message saying it's disabled with a button to enable it? Just want to make sure I have all the details right.

Talking with a couple of members of the VM team, it seems like we're possibly having some memory corruption going on. On Linux we use `SIGPROF` to interrupt threads so we can collect profiling information, but there's no equivalent signaling implementation on Windows so we do something completely different to collect profiling data. There's a chance that WSL doesn't behave exactly the same way as a true Linux kernel would, causing some of our assumptions to be incorrect.

**Comment by mkorbel1** [comment] 2021-07-15 22:49
Ah interesting, no this does not reproduce for me when I run on Windows instead of WSL.

With the steps that I'm following, yes I explicitly see a button to enable the profiler:
![image](https://user-images.githubusercontent.com/75506197/125867379-8fe71dc3-f7bb-434c-9881-00316e841ea5.png)
This button appears for me in both WSL and in Windows.  To my knowledge, I haven't done any special setup that would override default behavior here.

**Comment by bkonyi** [comment] 2021-07-16 16:37
Awesome, thanks for confirming!

Yeah, we don't have any testing on WSL so running in standard Windows terminals is the safest bet for now. I'll close this issue and move discussions over to https://github.com/dart-lang/sdk/issues/46643 in the SDK repo.

**Closed by bkonyi** 2021-07-16 16:37 UTC

**Comment by aam** [comment] 2021-07-22 22:46
@mkorbel1 are you able to reproduce the problem when running `dart --observe --profiler hello.dart` from the command line in WSL(with hello.dart having your sample repro above)? This should start an observatory that you can connect to with your browser and inspect code profiler stats under 'cpu profile'.

> Yes, I'm on Windows Subsystem for Linux (version 1, not version 2). I'm happy to provide any additional details for my setup that you think might be relevant.

How do you use VSCode with WSL? Are you using Remote Development extension pack as outlined here https://code.visualstudio.com/docs/remote/wsl ?

**Comment by mkorbel1** [comment] 2021-07-22 23:20
That's right, I'm using the "Remote Development" extension pack, and "Remote - WSL".

Something bad is happening when I run that command on this code.  I can't tell if I have some sort of unrelated setup issue or if this is a symptom of a similar problem.  Here's a few different outputs of me running that command, below.  I changed the number to lower values than 10000 in the example above and still seem to get these seg faults most of the time.

I double-checked that following the original steps still reproduces the same signature as previously reported.

```
> dart --observe --profiler bin/dart_profiler_string_bug.dart 

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
version=2.13.4 (stable) (Unknown timestamp) on "linux_x64"
pid=9131, thread=9136, isolate_group=dartdev(0x7fffd4337500), isolate=(nil)((nil))
isolate_instructions=7f51e9cc3000, vm_instructions=7f51ef7ab4c0
  pc 0x00007f51efd7e478 fp 0x00007f51e816f0a0 dart::FlowGraph::ComputeDominators(dart::GrowableArray<dart::BitVector*>*)+0x3d8
  pc 0x00007f51efd753cb fp 0x00007f51e816f150 dart::ConstantPropagator::Transform()+0x72b
  pc 0x00007f51efd74b80 fp 0x00007f51e816f250 dart::ConstantPropagator::Optimize(dart::FlowGraph*)+0x70
  pc 0x00007f51efe21050 fp 0x00007f51e816f260 dart+0x2152050
  pc 0x00007f51efe20769 fp 0x00007f51e816f2e0 dart::CompilerPass::Run(dart::CompilerPassState*) const+0xb9
  pc 0x00007f51efe20c53 fp 0x00007f51e816f300 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)+0xe3
  pc 0x00007f51efac6fc5 fp 0x00007f51e816fa00 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x5e5
  pc 0x00007f51efac7a92 fp 0x00007f51e816fbf0 dart+0x1df8a92
  pc 0x00007f51efac89c8 fp 0x00007f51e816fd00 dart::BackgroundCompiler::Run()+0x2d8
  pc 0x00007f51efab3d08 fp 0x00007f51e816fd80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x00007f51efab41dc fp 0x00007f51e816fdb0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
  pc 0x00007f51efa29e9d fp 0x00007f51e816fe70 dart+0x1d5ae9d
-- End of DumpStackTrace
Aborted (core dumped)
```

```
>  dart --observe --profiler bin/dart_profiler_string_bug.dart 
Observatory listening on http://127.0.0.1:8181/yej5NcSa4PU=/
Hello world!
869
466
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
vm-service: isolate (3763108032982335) 'main' has no debugger attached and is paused due to exception.  Connect to Observatory at http://127.0.0.1:8181/yej5NcSa4PU=/ to debug.
```

```
> dart --observe --profiler bin/dart_profiler_string_bug.dart 
Observatory listening on http://127.0.0.1:8181/xbB5E8gQCY8=/

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=(nil)
version=2.13.4 (stable) (Unknown timestamp) on "linux_x64"
pid=9284, thread=9292, isolate_group=kernel-service(0x7ffff2ed0a00), isolate=(nil)((nil))
isolate_instructions=7f3c3f5a6000, vm_instructions=7f3c45c624c0
  pc 0x00007f3c462ae983 fp 0x00007f3c3dd5e010 dart::BaseDirectChainedHashMap<dart::PointerKeyValueTrait<dart::Instruction>, dart::ValueObject, dart::Zone>::Resize(long)+0x223
  pc 0x00007f3c462b25f0 fp 0x00007f3c3dd5e0c0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x170
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e170 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e220 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e2d0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e380 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e430 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e4e0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e590 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e640 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e6f0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e7a0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e850 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e900 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5e9b0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5ea60 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5eb10 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5ebc0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5ec70 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5ed20 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5edd0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5ee80 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5ef30 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5efe0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5f090 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5f140 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b26df fp 0x00007f3c3dd5f1f0 dart::DominatorBasedCSE::OptimizeRecursive(dart::FlowGraph*, dart::BlockEntryInstr*, dart::CSEInstructionMap*)+0x25f
  pc 0x00007f3c462b22d8 fp 0x00007f3c3dd5f260 dart::DominatorBasedCSE::Optimize(dart::FlowGraph*)+0x78
  pc 0x00007f3c462d7769 fp 0x00007f3c3dd5f2e0 dart::CompilerPass::Run(dart::CompilerPassState*) const+0xb9
  pc 0x00007f3c462d7c9b fp 0x00007f3c3dd5f300 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)+0x12b
  pc 0x00007f3c45f7dfc5 fp 0x00007f3c3dd5fa00 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x5e5
  pc 0x00007f3c45f7ea92 fp 0x00007f3c3dd5fbf0 dart+0x1df8a92
  pc 0x00007f3c45f7f9c8 fp 0x00007f3c3dd5fd00 dart::BackgroundCompiler::Run()+0x2d8
  pc 0x00007f3c45f6ad08 fp 0x00007f3c3dd5fd80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x00007f3c45f6b1dc fp 0x00007f3c3dd5fdb0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
  pc 0x00007f3c45ee0e9d fp 0x00007f3c3dd5fe70 dart+0x1d5ae9d
-- End of DumpStackTrace
Aborted (core dumped)
```

**Comment by aam** [comment] 2021-07-22 23:36
Okay, interesting. Thank you for quick reply. What version of dart is this? (what does `dart --version` say?) Is this from flutter git repo from master channel? Have you tried getting (linux version of) dart from https://dart.dev/get-dart and use that in WSL?

**Comment by mkorbel1** [comment] 2021-07-22 23:39
```
> dart --version
Dart SDK version: 2.13.4 (stable) (Unknown timestamp) on "linux_x64"
```

This is not from flutter, I'm just using dart without flutter.  I actually don't even have flutter installed on this machine.

I am using the linux version of Dart in my WSL environment.  I have two separate dart installations on this machine: one on windows and one in Ubuntu WSL.  Unless there's some magic behind the scenes I'm unaware of causing me to use the Windows Dart installation from within Ubuntu WSL...?

**Comment by aam** [comment] 2021-07-23 00:52
Yeah, seems pretty straightforward repro and rather fundamental problem. Do you have everything else working in your WSL environment without obvious issues? Do you have some other Windows box with WSL you can try this on?
Unfortunately I can't reproduce it on my Windows 10 box(version 20H2).

**Comment by mkorbel1** [comment] 2021-07-23 15:37
Everything else seems to be working perfectly fine, and I've been using it for a decently long time.

I wonder if it's WSL 1 vs 2 specific?  You're using WSL 1 on yours?
https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2

I might have another computer I can try on later, will report back if I can.

**Comment by mkorbel1** [comment] 2021-07-23 15:59
I found another machine to test it on and got similar results.  The original described issue reproduces reliably.  When I run the `dart --observe --profiler` command on this other machine, I'm not getting the seg faults, just the same exception hitting.

**Comment by aam** [comment] 2021-07-24 00:19
> Everything else seems to be working perfectly fine, and I've been using it for a decently long time.
> 
> I wonder if it's WSL 1 vs 2 specific? You're using WSL 1 on yours?
> https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2

Yeah, I have WSL 1:
```
> wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         1
```

> I found another machine to test it on and got similar results. The original described issue reproduces reliably. 

Okay, thank you for checking. Let me see if I can find another machine I can reproduce the problemon.

**Comment by aam** [comment] 2021-07-26 15:50
> Okay, thank you for checking. Let me see if I can find another machine I can reproduce the problem on.

I was able to reproduce it on a different machine:
```
$ dart --profiler --observe test.dart
Observatory listening on http://127.0.0.1:8181/rGBrwgcYMYE=/
Hello world!
942
427
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
vm-service: isolate (1856336279427831) 'main' has no debugger attached and is paused due to exception.  Connect to Observatory at http://127.0.0.1:8181/rGBrwgcYMYE=/ to debug.
```

Will see if I can troubleshoot this further.

**Comment by aam** [comment] 2021-07-29 22:39
@mkorbel1 wrote
> I wonder if it's WSL 1 vs 2 specific? You're using WSL 1 on yours?

Pinpointing the problem on wsl1 is proving to be difficult.
One of the very useful memory tracing tools `rr` is not supported on wsl1, only works on wsl2, so I upgraded my Ubuntu instance to wsl2. With this upgrade though the error you reported went away for me.
Are you able to try wsl2? Can you use it instead of wsl1?

**Comment by bkonyi** [comment] 2021-08-02 16:13
Seems like Microsoft typically [recommends use of v2 for most use cases](https://docs.microsoft.com/en-us/windows/wsl/compare-versions).

**Comment by mkorbel1** [comment] 2021-08-02 16:46
I have a few reasons for sticking with WSL1 and hadn't had many good reasons to spend time switching to WSL2.  This might become one more reason that could push me to WSL2.

Without a fix for this, doesn't that leave dart devtools as only partially supporting WSL1?

**Comment by bkonyi** [comment] 2021-08-02 16:53
Unfortunately this wouldn't just be an issue with DevTools on WSL v1, but profiling Dart programs on WSL v1 in general. Maybe @aam will know more, but I'm not sure how easy it would be to fix this for WSL v1.

**Comment by aam** [comment] 2021-08-03 15:26
@mkorbel1 Yeah, profiling on WSL v1 seems to be broken. It's not clear what the root cause of the failure is at this point. Getting to the bottom of that on WSL v1 is difficult(`rr` memory analysis tool is not supported for WSL v1). 
Also if profiling/dartdev tooling works on v2, that might lower the priority of troubleshooting v1.
It would be nice to know if you are able to use v2. Normally it's just one command that migrates your distro `wsl --set-version Ubuntu 2` (Ubuntu is the name of your distro).

**Comment by mkorbel1** [comment] 2021-08-10 16:57
Ok, I'll give WSL2 a try soon when I have a few minutes, thank you for the quick help on this

**Comment by mkorbel1** [comment] 2021-09-16 23:14
I upgraded to WSL2 and it seems to be working now (no crash).
