### ISSUE TITLE
Flutter debugging network view displays only socket request issues

### ISSUE THREAD

**Issue by xhc-code** [flutter/devtools#8518] opened 2024-11-11 10:16 UTC
![image](https://github.com/user-attachments/assets/911d3e74-da6b-4b07-9564-d380bb5516b9)
![image](https://github.com/user-attachments/assets/3b4ee644-ad35-4a90-a2eb-a35224e5edc8)

What is actually requested in the picture https://cdn.pixabay.com/photo/2023/09/25/20/138/lisbon-8275994_1280.jpg Request, but in Flutter's debugging network, it shows a socket request and cannot see the parameters of the request and response. May I ask why this is?
We are using Flutter>version 3.4.1 and the Dio: ^ 5.4.3+1 request library.

The actual requests sent are all HTTP or HTTPS, but all the requests displayed in the socket are socket requests. I don't know where the problem lies because the socket is clearly not used.

Using an Android emulator
---
Image.network("https://cdn.pixabay.com/photo/2023/09/25/20/138/lisbon-8275994_1280.jpg", width: 50, height: 50,),
This is the image component that makes the request, and requests made using the Dio library are also socket requests displayed on the network.

**Comment by xhc-code** [comment] 2024-11-11 10:50
Ask an off topic question，May I ask why there have been no new builds for releases since 2020?

**Comment by xhc-code** [comment] 2024-11-12 08:10
https://github.com/xhc-code/my_flutter_network_problem.git
The code here includes both HTTP and sockets when using Dio to request linked data. Moreover, the number of socket and get requests is not equal.

The request for Image.network network images is not displayed in the network view.

**Comment by zigapovhe** [comment] 2024-11-13 07:40
Having the same issues with using http package on latest Flutter 3.24.4.

**Comment by zigapovhe** [comment] 2024-11-15 08:33
@kenzieschmoll Can you check this please? Looks like it's completely broken for lots of people. Thanks!

**Comment by nicks258** [comment] 2024-11-18 11:58
any solution for this? facing the same issue.

**Comment by kenzieschmoll** [comment] 2024-11-19 21:36
closing as a duplicate of https://github.com/flutter/devtools/issues/8380

**Closed by kenzieschmoll** 2024-11-19 21:36 UTC
Labels: screen: network
