### ISSUE TITLE
Cannot scroll after scrolling to bottom of cpu profiler.

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#4780] opened 2022-11-18 17:45 UTC
https://user-images.githubusercontent.com/1386322/202768481-09f8e9b1-d5af-4244-b891-5cf4e13e9c0d.mov

Cannot scroll in Cpu Profiler after scrolling to the bottom and mousing over the bottom of the list.
For some reason the bottom part of the scrollable area (about the same height as the scrollbar), becomes unscrollable, after scrolling to the bottom

**Comment by CoderDake** [comment] 2022-11-18 17:47
Looking a bit deeper it looks like that bottom part of the view might still be a dead zone even when we aren't scrolled to the bottom.

**Comment by kenzieschmoll** [comment] 2022-11-18 20:42
I cannot reproduce this. Do you have consistent repro?
![scroll-cpu-profiler](https://user-images.githubusercontent.com/43759233/202798690-8b3b881b-c4d4-4e11-b5bf-b0a6d471299b.gif)

**Comment by kenzieschmoll** [comment] 2024-11-26 21:56
Cannot reproduce. Closing.

**Closed by kenzieschmoll** 2024-11-26 21:56 UTC
Labels: cpu profiler, P3, reproduce to verify
