### ISSUE TITLE
Only InternetAddress are displayed on Network Tab

### ISSUE THREAD

**Issue by juliuskopp** [flutter/devtools#7855] opened 2024-05-30 06:19 UTC
Hi 
With the previous versions SDK 3.19.5 - devtool 2.31.1 , I was able to see all the request in the Network Tab. 
![image](https://github.com/flutter/devtools/assets/5365388/9e8231c7-88da-4b17-8c4f-0f84587793b9)

Now with SDK 3.22.1 I can only see "InternetAdress" request.

![image](https://github.com/flutter/devtools/assets/5365388/c5b04b67-71da-49f6-9687-7b1f4b09b0ef)

Is there any configuration to do?
Thank for your answer.
___
**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.1
Flutter Version: 3.22.1 / stable
Framework / Engine: a14f74ff3a / 55eae6864b

**Comment by ahmed3ssem** [comment] 2024-06-09 14:17
same issue

**Comment by hrajwade96** [comment] 2024-06-23 05:11
I was facing same issue, but found that my vanilla app was using a different flutter SDK version.
( I was using this app to test a functionality in devtools forked repo on master branch).

**Comment by laterdayi** [comment] 2024-07-02 02:47
same issue

**Comment by laterdayi** [comment] 2024-07-02 02:48
@kenzieschmoll   @polina-c  help

**Comment by laterdayi** [comment] 2024-07-02 02:49
@CoderDake

**Comment by kenzieschmoll** [comment] 2024-07-17 18:27
This is a duplicate of https://github.com/flutter/devtools/issues/3033, which is now fixed.

**Closed by kenzieschmoll** 2024-07-17 18:27 UTC
Labels: bug, network page, P1
