### ISSUE TITLE
the logging view should show events for breaking on exceptions

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#157] opened 2019-01-23 21:50 UTC
When we receive an event indicating that the app stopped as a result of an exception, we should show that info in the logging view.

**Comment by kenzieschmoll** [comment] 2024-10-24 20:53
Confirmed that we do not show anything in the logging view that indicates we are paused on an exception. We do show that the app is paused, which may be sufficient. The IDEs do not show anything special in the console when an app is paused on exception, the IDE just indicates that the app is paused and that there is an exception. Closing as won't fix since we have parity with the IDE logging / console views.

**Closed by kenzieschmoll** 2024-10-24 20:53 UTC
Labels: screen: logging, P2
