### ISSUE TITLE
[FR] Please add connection throttling (like chrome devtools)

### ISSUE THREAD

**Issue by samuelg123** [flutter/devtools#969] opened 2019-08-24 16:28 UTC
Hi,
I need a feature for debugging connection in flutter apps. My idea is to add some throttling options (Online, Mid-tier mobile, Low-tier mobile, and Offline) like chrome devtools.

Thank you.

**Comment by jacob314** [comment] 2019-08-24 22:36
There are proxy servers that accurately simulate varying network speeds

**Comment by samuelg123** [comment] 2019-08-26 02:14
Okay, I'll try that. Thanks

**Comment by kenzieschmoll** [comment] 2022-05-24 22:51
closing as dupe of https://github.com/flutter/devtools/issues/4139

**Closed by kenzieschmoll** 2022-05-24 22:51 UTC
Labels: enhancement, networking
