### ISSUE TITLE
Improve Copy behaviour for all tables in DevTools

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#5130] opened 2023-01-27 15:21 UTC
https://github.com/flutter/devtools/issues/5031#issuecomment-1404313792
Brought up a good point that we could use better ways to copy data when it is presented in table format.

Perhaps we could add functionality to the table widget that would allow us to copy in the following ways:
- cell
- row
- column
- table

**Comment by kenzieschmoll** [comment] 2023-08-21 20:01
closing as a duplicate of https://github.com/flutter/devtools/issues/4551

**Closed by kenzieschmoll** 2023-08-21 20:01 UTC
Labels: usability, ux, copy behavior, P2
