### ISSUE TITLE
Reporting error: Failed to parse package:vocabugator/main.dart.

### ISSUE THREAD

**Issue by pabluez** [flutter/devtools#7305] opened 2024-03-04 02:00 UTC
Stack trace:
main.dart.js 6212:18    Object.qn
main.dart.js 69298:76   <fn>
main.dart.js 4775:63    bFj.a
main.dart.js 58094:14   bFj.$2
main.dart.js 58088:21   bDc.$1
main.dart.js 5071:19    Object.bEY
main.dart.js 168428:68  al8.<fn>
main.dart.js 59293:12   a_M.rF
main.dart.js 58598:11   bpI.$0
main.dart.js 4940:40    Object.Nj

I get an error everytime I try to reuse an already open but disconnect DevTools for web tab by just copying and pasting the URL I see in my debug output window.
![image](https://github.com/flutter/devtools/assets/777052/b3af97b7-7522-43dc-b2ca-1bdbe9d693e6)

___
**DevTools version**: 2.31.1
**IDE**: VSCode

**Comment by kenzieschmoll** [comment] 2024-03-04 18:10
duplicate of https://github.com/flutter/devtools/issues/7192

**Closed by kenzieschmoll** 2024-03-04 18:10 UTC

**Comment by elliette** [comment] 2024-03-06 00:52
Hi @pabluez!

Thank you for the report! I haven't been able to reproduce this, but I'm not sure I'm trying the same thing you are describing. Could you please give a few more details? Specifically:

- how are you running the app? are you running it from the command line or from an IDE (e.g. VS Code, or?)
- how are you opening DevTools? are you launching it from an IDE, or copy-pasting the URL in your terminal?
- how does DevTools get into a disconnected state? Is the app no longer running, or are you clicking "Connect to a new app" from DevTools?
- which URL are you copy-pasting (what "debug output window" is it in), and where are you pasting it to?
