### ISSUE TITLE
unable to navigate to the debugger page (when launched from VS Code?)

### ISSUE THREAD

**Issue by j787701730** [flutter/devtools#490] opened 2019-04-02 01:34 UTC
![image](https://user-images.githubusercontent.com/23625690/55369688-318fb600-552a-11e9-846e-11dce5120069.png)
![image](https://user-images.githubusercontent.com/23625690/55369699-3b191e00-552a-11e9-81b9-e52ae402f6e7.png)

studio console can't view long data.

**Comment by stevemessick** [comment] 2019-04-02 15:55
@jacob314

**Comment by jacob314** [comment] 2019-04-02 16:38
This is by design but we should make the message more obvious.
I'm curious, do you have a use case where using the debugger in devtools is could be more convenient than the debugger from vscode? Our assumption was VSCode users would prefer the integrated VSCode debugger but we might be missing something.

See the tooltip message: "This screen is disabled because it provides functionality already available in your code editor".
If you would like to try out the debugger after launching from Intellij, you can remove all query parameters from the devtools url other than the one indicating the port.

**Comment by DanTup** [comment] 2019-04-17 14:21
> Our assumption was VSCode users would prefer the integrated VSCode debugger but we might be missing something.

The main reason for disabling it was actually just a current technical limitation. There are lots of assumptions in VS Code (and probably IntelliJ) about it owning the debug session, for example when an app restarts, VS Code send breakpoints and then resume. If there are multiple debuggers, they both need to send their breakpoints *before either of them unpause* to avoid races. There are also assumptions that VS Code has the "true list of breakpoints" and it may overwrite/remove those added by other debuggers during a restart.

It'd be nice to resolve these issues, but some of them (like the "who resumes after a restart" one) aren't as simple as just making changes in VS Code.

**Comment by DanTup** [comment] 2019-04-17 14:22
That said, we could more easily ensure if you "Start without Debugging" from VS Code, that we don't run any code during restarts (etc.) and then not disable the debugger here. That would let people use devtools for the debugging if they wish.

**Comment by kenzieschmoll** [comment] 2020-09-18 15:40
this was an issue for the html app - closing as obsolete

**Closed by kenzieschmoll** 2020-09-18 15:40 UTC
Labels: debugger page
