### ISSUE TITLE
Flutter Widget Inspector Doesn't Connect in VS Code

### ISSUE THREAD

**Issue by arc4randall** [flutter/devtools#7248] opened 2024-02-20 21:53 UTC
<img width="818" alt="image" src="https://github.com/flutter/devtools/assets/7901383/5dea4749-8cd5-4f35-acfe-6d78dfed0be7">

When running Flutter Run in the terminal my app launches to the emulator and I'm given a URL that can be opened in the browser to launch the inspector, however the inspector doesn't attach locally and presents the attached error.
___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.3.0
Flutter Version: 3.19.0 / stable
Framework / Engine: bae5e49bc2 / 04817c99c9

**Comment by kenzieschmoll** [comment] 2024-02-25 16:24
I am unable to reproduce this issue. @DanTup is it possible there could be some caching issue here causing VS Code to pick up an old DevTools version?

**Comment by DanTup** [comment] 2024-02-25 18:02
We've seen some caching issues in the past, but I thought they'd all been solved. @arc4randall can you see the version number in DevTools when embedded (I can't recall if it's in the bottom left or not, but maybe if you click the Cog/Settings icon it'll be listed in there somewhere?).

**Comment by arc4randall** [comment] 2024-02-25 18:06
Devtools version 2.31.1

**Comment by DanTup** [comment] 2024-02-26 10:16
@kenzieschmoll 2.31.1 seems correct if I'm reading correctly. I presume this version comes from the compiled Dart file (so matches the version of the code that would be running everywhere else?).

I was also unable to reproduce this, either using the Windows desktop device, or a physical arm64 device as noted above.

@arc4randall did this issue only occur when embedded? The text above reads like it might also show the error from the terminal, but the screenshot looks like embedded in VS Code.

You can change VS Code to launch the inspector in an external Window to test that too: Opening your VS Code User Settings JSON (`F1` to open the palette, then **Preferences: Open Workspace Settings (JSON)**), and paste in the following:

```
"dart.devToolsLocation": "external",
```

Now the Inspector commands/buttons should open in an external browser. Please let us know if the issue also occurs there or if it's only when embedded. You can revert to the embedded version by removing the above setting afterwards.

**Comment by arc4randall** [comment] 2024-02-26 23:28
This issue only occurs when embedded and not whe nlaunching external by setting "dart.devToolsLocation": "external",

**Comment by DanTup** [comment] 2024-02-29 16:28
@arc4randall can you confirm which OS you're on?

@kenzieschmoll I'm not completely familiar with what might be failing to result in this error. Does this exception come from the server of the web UI? Does this error indicate that there is a DevTools extension attempting to load?

**Comment by arc4randall** [comment] 2024-02-29 16:36
I am on MacOS Sonoma on an M2 MacBook Air running VS Code 1.86.2

**Comment by DanTup** [comment] 2024-02-29 16:57
@arc4randall could you try:

- Open DevTools so it shows the error
- Click **Help** -> **Toggle Developer Tools** in VS Code
- Click on the **Application** tab
- Expand **Cache Storage**
- Click **flutter-app-cache**
- Select one of the cached items shown, then repeatedly click the delete button until they're all gone (I can't see an obvious way to delete them all!)
- Repeat the same for **flutter-app-manifest**
- Restart VS Code
- Try again


https://github.com/flutter/devtools/assets/1078012/609b6e02-37c0-4320-acd1-4953581cafc7

**Comment by kenzieschmoll** [comment] 2024-03-04 18:14
Here is another report from an IntelliJ user: https://github.com/flutter/devtools/issues/7306

**Comment by DanTup** [comment] 2024-03-04 19:37
@arc4randall have you restarted VS Code since you upgraded to the latest Flutter? (I'm wondering if the DevTools server that's running might be an older version than the SDK being used to compile/run your app)?

**Comment by arc4randall** [comment] 2024-03-04 20:31
After restarting my computer and VS Code I have not experienced this issue any more. I restarted both at the same time so not sure which resolved it.

**Comment by DanTup** [comment] 2024-03-04 21:06
@arc4randall thanks for confirming. Do you think it's possible you upgraded Flutter while the editor was opened and hadn't restarted?

We do try to detect when SDKs change (by monitoring the `version` file) and prompt to reload, however VS Code hides notifications after 10-15s, so it's possible to miss this (particularly if your focus is elsewhere like a terminal).

I'll close this on the assumption it was probably this, but if you (or anyone else coming across this issue) sees it again and/or without having upgraded SDK and not restarted, please do let us know.

**Closed by DanTup** 2024-03-04 21:06 UTC

**Comment by arc4randall** [comment] 2024-03-05 15:25
I don't think so but I will let you know if I experience this again. Thanks for looking into this for me.
