### ISSUE TITLE
Reporting error: Error collecting raster stats: _flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame was rendered

### ISSUE THREAD

**Issue by dhairyajain29** [flutter/devtools#7593] opened 2024-04-16 12:57 UTC
Stack trace:
Error
    at Object.qn (http://127.0.0.1:9100/main.dart.js:6212:18)
    at bim.$0 (http://127.0.0.1:9100/main.dart.js:164961:5)
    at iv.cA (http://127.0.0.1:9100/main.dart.js:164830:53)
    at iv.lU (http://127.0.0.1:9100/main.dart.js:164814:13)
    at http://127.0.0.1:9100/main.dart.js:101540:14
    at bFj.a (http://127.0.0.1:9100/main.dart.js:4775:63)
    at bFj.$2 (http://127.0.0.1:9100/main.dart.js:58094:14)
    at bDc.$1 (http://127.0.0.1:9100/main.dart.js:58088:21)
    at Object.bEY (http://127.0.0.1:9100/main.dart.js:5071:19)
    at al8.<anonymous> (http://127.0.0.1:9100/main.dart.js:168428:68)
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Connected app type: Flutter native (profile build)
Dart Version: 3.3.0
Flutter Version: 3.19.2 / stable
Framework / Engine: 7482962148 / 04817c99c9

**Comment by CoderDake** [comment] 2024-05-21 17:48
Duplicate of https://github.com/flutter/devtools/issues/6992

**Closed by CoderDake** 2024-05-21 17:48 UTC
