### ISSUE TITLE
Reporting error: Error collecting raster stats: _flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame was rendered

### ISSUE THREAD

**Issue by TRADEEQS** [flutter/devtools#7482] opened 2024-03-27 20:23 UTC
Stack trace:
Error
    at Object.qb (http://127.0.0.1:9100/main.dart.js:6165:18)
    at http://127.0.0.1:9100/main.dart.js:160301:5
    at bDg.a (http://127.0.0.1:9100/main.dart.js:4774:62)
    at bDg.$2 (http://127.0.0.1:9100/main.dart.js:56680:14)
    at Object.m (http://127.0.0.1:9100/main.dart.js:4760:10)
    at za.aD6 (http://127.0.0.1:9100/main.dart.js:160315:10)
    at za.cb (http://127.0.0.1:9100/main.dart.js:160294:25)
    at za.jD (http://127.0.0.1:9100/main.dart.js:160279:13)
    at il.jD (http://127.0.0.1:9100/main.dart.js:88646:44)
    at http://127.0.0.1:9100/main.dart.js:100401:14
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.5
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.2.6
Flutter Version: 3.16.9 / stable
Framework / Engine: 41456452f2 / f40e976bed

**Comment by corepuncher** [comment] 2024-05-11 02:30
I am suddenly getting this now too. I used to be able to take raster snapshots in devtools but no longer.

**Comment by CoderDake** [comment] 2024-05-21 17:47
Duplicate of https://github.com/flutter/devtools/issues/6992

**Closed** 2024-06-25 19:18 UTC
