### ISSUE TITLE
Horizontal scroll is not discoverable in timeline events

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4781] opened 2022-11-18 17:47 UTC
<img width="1233" alt="Screenshot 2022-11-18 at 9 46 36 AM" src="https://user-images.githubusercontent.com/12115586/202769167-cd3d1826-47f0-4ddc-9393-05b8afdbe451.png">

**Comment by kenzieschmoll** [comment] 2022-11-18 20:37
closing as duplicate of https://github.com/flutter/devtools/issues/2695

**Closed by kenzieschmoll** 2022-11-18 20:37 UTC
