### ISSUE TITLE
Flutter inspector bugging out/freezing in Visual Studio Code

### ISSUE THREAD

**Issue by joshoconnor89** [flutter/devtools#2581] opened 2020-12-30 23:04 UTC
Today was the first day I came across this issue with flutter widget inspector. When you click "Select Widget Mode" then select an element, it will freeze, and this inception-like view will occur: 

<img width="828" alt="Screen Shot 2020-12-30 at 2 19 09 PM" src="https://user-images.githubusercontent.com/9359439/103385685-4bb84880-4ab0-11eb-86f1-2da9caf9ac6b.png">

In addition, if you just resize this window in Visual Studio code, the Widget Inspector view goes blank:

<img width="1162" alt="Screen Shot 2020-12-30 at 2 26 49 PM" src="https://user-images.githubusercontent.com/9359439/103385689-4eb33900-4ab0-11eb-93f8-f730a2ed3aab.png">

I've almost lost an entire day of development because of this stupid bug.  I even tried using a different computer and its still happening.  

I have a feeling something got updated automatically and broke things. Does anyone have any idea why this is occurring? It was working so well then all the sudden today it decided to break.  I tried the simulator (iOS and android) and device, no luck.

**Comment by kenzieschmoll** [comment] 2020-12-30 23:06
Does this happen if you open DevTools outside of VsCode? What about if you connect your app manually by running DevTools directly from pub (`flutter pub global activate devtools; flutter pub global run devtools`)

**Comment by joshoconnor89** [comment] 2020-12-30 23:07
ill check right now

**Comment by kenzieschmoll** [comment] 2020-12-30 23:08
cc @DanTup

**Comment by joshoconnor89** [comment] 2020-12-30 23:19
no it does not

**Comment by joshoconnor89** [comment] 2020-12-30 23:21
it works fine in the browser but it does not jump to the source code when selecting an element from "Select Widget Mode", without that, it's pretty useless

**Comment by kenzieschmoll** [comment] 2020-12-30 23:41
Thanks for checking. Sounds like the bug you are seeing is with the VsCode embedded version of DevTools then. @DanTup can you take a look? thanks.

**Comment by joshoconnor89** [comment] 2020-12-30 23:50
it had to be something that was done today, yesterday this was fine.  is there anyway to revert to earlier version of devtools?  VSC automatically updated devtools today

**Comment by jeiea** [comment] 2020-12-31 02:10
Maybe related to https://github.com/Dart-Code/Dart-Code/issues/3024

**Comment by joshoconnor89** [comment] 2020-12-31 17:02
this is EXACTLY whats going on ^

**Comment by khodenikhil22** [comment] 2021-01-01 05:52
> Today was the first day I came across this issue with flutter widget inspector. When you click "Select Widget Mode" then select an element, it will freeze, and this inception-like view will occur:
> 
> <img alt="Screen Shot 2020-12-30 at 2 19 09 PM" width="828" src="https://user-images.githubusercontent.com/9359439/103385685-4bb84880-4ab0-11eb-86f1-2da9caf9ac6b.png">
> 
> In addition, if you just resize this window in Visual Studio code, the Widget Inspector view goes blank:
> 
> <img alt="Screen Shot 2020-12-30 at 2 26 49 PM" width="1162" src="https://user-images.githubusercontent.com/9359439/103385689-4eb33900-4ab0-11eb-93f8-f730a2ed3aab.png">
> 
> I've almost lost an entire day of development because of this stupid bug. I even tried using a different computer and its still happening.
> 
> I have a feeling something got updated automatically and broke things. Does anyone have any idea why this is occurring? It was working so well then all the sudden today it decided to break. I tried the simulator (iOS and android) and device, no luck.

I am facing the same issue. Anyone got the solution ?



https://user-images.githubusercontent.com/71748188/103434168-7971ce80-4c23-11eb-94b7-b2a3007615da.mp4

**Comment by DanTup** [comment] 2021-01-01 13:22
I can reproduce this, though haven't been able to track it down yet. It does only seem to happen when embedded, but frustratingly VS Code/electron doesn't let us access the Chrome devtools for embedded window.

You can set the `dart.embedDevTools` setting to `false` in your VS Code User Settings for now to have DevTools open in an external browser window while we try to track this down.

**Comment by DanTup** [comment] 2021-01-04 16:18
I did some more debugging in https://github.com/Dart-Code/Dart-Code/issues/3024 and found a Flutter issue that seemed similar (https://github.com/flutter/flutter/issues/65480) and has recently been fixed.

I rebuilt DevTools using Flutter's master branch locally, and I'm unable to reproduce the issues I was seeing when running embedded. So I think this may be fixed and should go away with the next DevTools release (assuming it has the fixes that are in today's master).

**Comment by joshoconnor89** [comment] 2021-01-04 17:08
Thank you!  When will the next release of devtools be out?

**Comment by DanTup** [comment] 2021-01-04 17:18
That's probably a question for @jacob314 / @kenzieschmoll.

(I think the release is usually built from the Flutter dev branch, so it'd also require the involved fixes have made it there - though that should be easy enough to test before the release is made).

**Comment by SDP190** [comment] 2021-01-11 22:05
Have same issue

**Comment by DanTup** [comment] 2021-01-12 11:17
I believe the actual fix for this was https://github.com/flutter/engine/pull/23115. It doesn't look like that fix has made it to Flutter's dev branch yet, but once it does, the subsequent DevTools release should include it.

**Comment by DanTup** [comment] 2021-02-17 18:48
Closing this as I believe there's nothing to do - the issue was fixed in Flutter in https://github.com/flutter/engine/pull/23115 and if the current DevTools build wasn't built on a version with that fix, the next one certainly should be (it's definitely in dev, which is where I believe the DevTools releases are built from).

**Closed by DanTup** 2021-02-17 18:48 UTC
Labels: vs-code

**Comment by WangMiaoGit** [comment] 2021-06-08 09:39
![image](https://user-images.githubusercontent.com/22518556/121162047-21995c80-c880-11eb-8124-bef3a06f5a63.png)
in my vscode，widget Inspector don`t show like this picture. 
It was fine this morning

**Comment by DanTup** [comment] 2021-06-08 09:47
@WangMiaoGit could you post the full output of running the following commands:

```
pub global list
```

```
flutter doctor -v
```

```
code --version
```

And can you also confirm the version of the Dart extension you have installed in VS Code?

Thanks!

**Comment by WangMiaoGit** [comment] 2021-06-08 09:52
@DanTup 
![image](https://user-images.githubusercontent.com/22518556/121164362-1e06d500-c882-11eb-878b-311f4a3b14db.png)
![image](https://user-images.githubusercontent.com/22518556/121164655-4d1d4680-c882-11eb-9ebe-68becb9f7c8d.png)
this?

**Comment by WangMiaoGit** [comment] 2021-06-08 09:53
@DanTup 
![image](https://user-images.githubusercontent.com/22518556/121164812-64f4ca80-c882-11eb-8fc2-f634bdbe175f.png)
![image](https://user-images.githubusercontent.com/22518556/121164866-6d4d0580-c882-11eb-8062-16312eb9a1bc.png)
This?

**Comment by WangMiaoGit** [comment] 2021-06-08 09:54
![image](https://user-images.githubusercontent.com/22518556/121164998-85bd2000-c882-11eb-997f-f01cf19389ea.png)

**Comment by WangMiaoGit** [comment] 2021-06-08 09:55
![image](https://user-images.githubusercontent.com/22518556/121165153-a4bbb200-c882-11eb-8bc2-b62c7d5f287e.png)

**Comment by WangMiaoGit** [comment] 2021-06-08 10:00
![image](https://user-images.githubusercontent.com/22518556/121166148-6672c280-c883-11eb-80e6-bf948a7e8b52.png)

**Comment by DanTup** [comment] 2021-06-08 16:10
@WangMiaoGit thanks - can you also confirm the exact version of DevTools listed with `pub global list`? (note: do not prefix it with `flutter`, just run it as `pub`) and your VS Code version (`code --version`)?

Can you reliably reproduce the issue, or is it intermittent?

**Comment by WangMiaoGit** [comment] 2021-06-09 02:58
pub global list
nothing

code --version
1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64.

today,The question keeps coming up。

**Comment by WangMiaoGit** [comment] 2021-06-09 03:01
@DanTup 
I upgraded vscode yesterday, and it was OK before the upgrade.

**Comment by WangMiaoGit** [comment] 2021-06-09 03:02
@DanTup 
I upgraded vscode yesterday, and it was OK before the upgrade.

**Comment by DanTup** [comment] 2021-06-09 09:33
```
pub global list
nothing
```

That's a little unexpected. Could you try the following:

- **Untick** the "Share Dev Tools with Flutter" setting in your VS Code user settings
  <img width="1047" alt="Screenshot 2021-06-09 at 10 29 55" src="https://user-images.githubusercontent.com/1078012/121330114-ab433b80-c90d-11eb-89fe-ec8e362e32d7.png">
- Restart VS Code
- Open a Flutter project
- Run the **Dart: Capture Extension Logs** command from the VS Code command palette
- Run the **Dart: Open DevTools** command from the VS Code command palette
- Click **Cancel** on the logging notification

This will produce a log that should have some info on the exact DevTools version being selected/spawned. Thanks!

**Comment by WangMiaoGit** [comment] 2021-06-09 10:13
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.23.0
Flutter extension: 3.23.0 (activated)

App: Visual Studio Code
Version: 1.56.2
Platform: win

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: D:\flutter\bin\cache\dart-sdk
    Ver: 2.13.0
Flutter SDK:
    Loc: D:\flutter
    Ver: 2.2.0

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, CommandProcesses, DevTools, FlutterDaemon

Wed Jun 09 2021 [18:11:38 GMT+0800 (中国标准时间)] Log file started
[下午6:11:41] [General] [Info] Using only available debug session
[下午6:11:42] [General] [Info] Exposing URL: http://127.0.0.1:53891/BHyLhHoQpoQ%3D/
[下午6:11:42] [General] [Info] Mapping URL: http://127.0.0.1:53891/BHyLhHoQpoQ%3D/
[下午6:11:42] [General] [Info] Mapped URL: http://127.0.0.1:53891/BHyLhHoQpoQ%3D/
[下午6:11:42] [General] [Info] Final URI: http://127.0.0.1:53891/BHyLhHoQpoQ%3D/
[下午6:11:42] [General] [Info] Final URL: http://127.0.0.1:53891/BHyLhHoQpoQ%3D/
Wed Jun 09 2021 [18:11:50 GMT+0800 (中国标准时间)] Log file ended

**Comment by DanTup** [comment] 2021-06-09 10:27
@WangMiaoGit it looks like DevTools may have already been running when you captured the log. Can you check you _Unticked_ the setting described above, then restart VS Code, then run the **Capture Logs** command (before trying to open DevTools). It should capture some logs showing DevTools being started. Thanks!

**Comment by WangMiaoGit** [comment] 2021-06-09 10:53
@DanTup 

**Is this?**

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.23.0
Flutter extension: 3.23.0 (activated)

App: Visual Studio Code
Version: 1.56.2
Platform: win

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: D:\flutter\bin\cache\dart-sdk
    Ver: 2.13.0
Flutter SDK:
    Loc: D:\flutter
    Ver: 2.2.0

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, CommandProcesses, DevTools, FlutterDaemon

Wed Jun 09 2021 [18:45:28 GMT+0800 (中国标准时间)] Log file started
[下午6:45:31] [General] [Info] Starting debug session...
[下午6:45:31] [General] [Info]     workspace: E:\programSource\target-system
[下午6:45:31] [General] [Info] Using found common entry point: E:\programSource\target-system\lib\main.dart
[下午6:45:31] [General] [Info] Using workspace as cwd: E:\programSource\target-system
[下午6:45:31] [General] [Info] Detected launch project as Flutter
[下午6:45:31] [General] [Info] Using Flutter debug adapter for this session
[下午6:45:31] [FlutterDaemon] [Info] ==> [{"id":"6","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"E:\\programSource\\target-system"}}]
[下午6:45:31] [FlutterDaemon] [Info] <== [{"id":"6","result":{"platforms":["ios","android","web"]}}]
[下午6:45:31] [FlutterDaemon] [Info] ==> [{"id":"7","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"E:\\programSource\\target-system"}}]
[下午6:45:31] [FlutterDaemon] [Info] <== [{"id":"7","result":{"platforms":["ios","android","web"]}}]
[下午6:45:31] [General] [Info] Checking for errors before launching
[下午6:45:31] [General] [Info] Debug session starting...
    {
        "type": "dart",
        "request": "launch",
        "program": "E:\\programSource\\target-system\\lib\\main.dart",
        "cwd": "E:\\programSource\\target-system",
        "name": "Flutter (Chrome)",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "args": [
            "--web-renderer=auto"
        ],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartSdkPath": "D:\\flutter\\bin\\cache\\dart-sdk",
        "maxLogLineLength": 2000,
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "flutterSdkPath": "D:\\flutter",
        "globalFlutterArgs": [],
        "useFlutterStructuredErrors": true,
        "useInspectorNotificationsForWidgetErrors": true,
        "debugExtensionBackendProtocol": "ws",
        "injectedClientProtocol": "ws",
        "forceFlutterVerboseMode": true,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "workspaceConfig": {
            "useLsp": false
        },
        "deviceId": "chrome",
        "deviceName": "Chrome (web-javascript)",
        "showMemoryUsage": false,
        "debuggerType": 2
    }
[下午6:45:31] [General] [Info] Using flutter debugger for Flutter
[下午6:45:31] [General] [Info] Running debugger via node with c:\Users\Administrator\.vscode\extensions\dart-code.dart-code-3.23.0\out\dist\debug.js    flutter
[下午6:45:31] [General] [Warn] Did not find session 31cc3973-e8ac-4eaa-9e73-1589c132595e to handle dart.progressStart. There were 0 sessions:
[下午6:45:31] [General] [Warn] Event will be queued and processed when the session start event fires
[下午6:45:31] [General] [Info] Processing delayed event dart.progressStart for session 31cc3973-e8ac-4eaa-9e73-1589c132595e
[下午6:45:33] [General] [Info] Exposing URL: http://127.0.0.1:62863/%24debug
[下午6:45:33] [General] [Info] Mapping URL: http://127.0.0.1:62863/%24debug
[下午6:45:33] [General] [Info] Mapped URL: http://127.0.0.1:62863/%24debug
[下午6:45:33] [General] [Info] Final URI: http://127.0.0.1:62863/$debug
[下午6:45:33] [General] [Info] Final URL: http://127.0.0.1:62863/$debug
[下午6:46:12] [General] [Info] Exposing URL: ws://127.0.0.1:62937/T4DOyCYKrmg%3D/ws
[下午6:46:12] [General] [Info] Mapping URL: http://127.0.0.1:62937/T4DOyCYKrmg%3D/ws
[下午6:46:12] [General] [Info] Mapped URL: http://127.0.0.1:62937/T4DOyCYKrmg%3D/ws
[下午6:46:12] [General] [Info] Final URI: ws://127.0.0.1:62937/T4DOyCYKrmg%3D/ws
[下午6:46:12] [General] [Info] Final URL: ws://127.0.0.1:62937/T4DOyCYKrmg%3D/ws
[下午6:46:12] [DevTools] [Info] ==> {"id":"2","method":"vm.register","params":{"uri":"http://127.0.0.1:62937/T4DOyCYKrmg=/"}}
[下午6:46:12] [DevTools] [Info] <== {"id":"2","result":{"success":true}}
[下午6:46:27] [General] [Info] Using only available debug session
[下午6:46:31] [General] [Info] Exposing URL: http://127.0.0.1:62937/T4DOyCYKrmg%3D/
[下午6:46:31] [General] [Info] Mapping URL: http://127.0.0.1:62937/T4DOyCYKrmg%3D/
[下午6:46:31] [General] [Info] Mapped URL: http://127.0.0.1:62937/T4DOyCYKrmg%3D/
[下午6:46:31] [General] [Info] Final URI: http://127.0.0.1:62937/T4DOyCYKrmg%3D/
[下午6:46:31] [General] [Info] Final URL: http://127.0.0.1:62937/T4DOyCYKrmg%3D/
Wed Jun 09 2021 [18:46:43 GMT+0800 (中国标准时间)] Log file ended

**Comment by WangMiaoGit** [comment] 2021-06-09 11:06
![image](https://user-images.githubusercontent.com/22518556/121343951-c89bf800-c955-11eb-9003-4979226e670d.png)

**Comment by WangMiaoGit** [comment] 2021-06-09 11:21
@DanTup 

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.23.0
Flutter extension: 3.23.0 (activated)

App: Visual Studio Code
Version: 1.56.2
Platform: win

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: D:\flutter\bin\cache\dart-sdk
    Ver: 2.13.0
Flutter SDK:
    Loc: D:\flutter
    Ver: 2.2.0

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, CommandProcesses, DevTools, FlutterDaemon

Wed Jun 09 2021 [19:13:58 GMT+0800 (中国标准时间)] Log file started
[下午7:14:00] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
[下午7:14:00] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"edge","name":"Edge","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
[下午7:14:00] [General] [Info] Returning cached promise for getSupportedPlatforms()
[下午7:14:00] [General] [Info] Checking 1 projects for supported platforms
[下午7:14:00] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"E:\\programSource\\target-system"}}]
[下午7:14:00] [FlutterDaemon] [Info] <== [{"id":"3","result":{"platforms":["ios","android","web"]}}]
[下午7:14:00] [General] [Info] Supported platforms for the workspace are ios, android, web
[下午7:14:01] [General] [Info] Analyzer:FirstAnalysis timing: 6884ms
[下午7:14:02] [General] [Info] Starting debug session...
[下午7:14:02] [General] [Info]     workspace: E:\programSource\target-system
[下午7:14:02] [General] [Info] Using found common entry point: E:\programSource\target-system\lib\main.dart
[下午7:14:02] [General] [Info] Using workspace as cwd: E:\programSource\target-system
[下午7:14:02] [General] [Info] Detected launch project as Flutter
[下午7:14:02] [General] [Info] Using Flutter debug adapter for this session
[下午7:14:02] [FlutterDaemon] [Info] ==> [{"id":"4","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"E:\\programSource\\target-system"}}]
[下午7:14:02] [FlutterDaemon] [Info] <== [{"id":"4","result":{"platforms":["ios","android","web"]}}]
[下午7:14:02] [FlutterDaemon] [Info] ==> [{"id":"5","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"E:\\programSource\\target-system"}}]
[下午7:14:02] [FlutterDaemon] [Info] <== [{"id":"5","result":{"platforms":["ios","android","web"]}}]
[下午7:14:02] [General] [Info] Checking for errors before launching
[下午7:14:02] [General] [Info] Debug session starting...
    {
        "type": "dart",
        "request": "launch",
        "program": "E:\\programSource\\target-system\\lib\\main.dart",
        "cwd": "E:\\programSource\\target-system",
        "name": "Flutter (Chrome)",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "args": [
            "--web-renderer=auto"
        ],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartSdkPath": "D:\\flutter\\bin\\cache\\dart-sdk",
        "maxLogLineLength": 2000,
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "flutterSdkPath": "D:\\flutter",
        "globalFlutterArgs": [],
        "useFlutterStructuredErrors": true,
        "useInspectorNotificationsForWidgetErrors": true,
        "debugExtensionBackendProtocol": "ws",
        "injectedClientProtocol": "ws",
        "forceFlutterVerboseMode": true,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "workspaceConfig": {
            "useLsp": false
        },
        "deviceId": "chrome",
        "deviceName": "Chrome (web-javascript)",
        "showMemoryUsage": false,
        "debuggerType": 2
    }
[下午7:14:02] [General] [Info] Using flutter debugger for Flutter
[下午7:14:02] [General] [Info] Running debugger via node with c:\Users\Administrator\.vscode\extensions\dart-code.dart-code-3.23.0\out\dist\debug.js    flutter
[下午7:14:03] [General] [Warn] Did not find session beddcce9-af9c-4931-a188-63f875e26b74 to handle dart.progressStart. There were 0 sessions:
[下午7:14:03] [General] [Warn] Event will be queued and processed when the session start event fires
[下午7:14:03] [General] [Info] Processing delayed event dart.progressStart for session beddcce9-af9c-4931-a188-63f875e26b74
[下午7:14:04] [General] [Info] Exposing URL: http://127.0.0.1:56565/%24debug
[下午7:14:04] [General] [Info] Mapping URL: http://127.0.0.1:56565/%24debug
[下午7:14:04] [General] [Info] Mapped URL: http://127.0.0.1:56565/%24debug
[下午7:14:04] [General] [Info] Final URI: http://127.0.0.1:56565/$debug
[下午7:14:04] [General] [Info] Final URL: http://127.0.0.1:56565/$debug
[下午7:14:53] [General] [Info] Exposing URL: ws://127.0.0.1:56842/TJokpmLi9mk%3D/ws
[下午7:14:53] [General] [Info] Mapping URL: http://127.0.0.1:56842/TJokpmLi9mk%3D/ws
[下午7:14:53] [General] [Info] Mapped URL: http://127.0.0.1:56842/TJokpmLi9mk%3D/ws
[下午7:14:53] [General] [Info] Final URI: ws://127.0.0.1:56842/TJokpmLi9mk%3D/ws
[下午7:14:53] [General] [Info] Final URL: ws://127.0.0.1:56842/TJokpmLi9mk%3D/ws
[下午7:15:09] [General] [Info] Using only available debug session
[下午7:15:09] [General] [Info] Spawning D:\flutter\bin\cache\dart-sdk\bin\pub.bat with args ["global","list"]
[下午7:15:09] [CommandProcesses] [Info] (PROC 17344) Logging data for process...
[下午7:15:10] [CommandProcesses] [Info] (PROC 17344) devtools 2.3.2
[下午7:15:10] [CommandProcesses] [Info] (PROC 17344)
[下午7:15:10] [CommandProcesses] [Info] (PROC 17344) exited (0, null)
[下午7:15:10] [CommandProcesses] [Info] (PROC 17344) closed (0, null)
[下午7:15:10] [General] [Info] devtools version 2.3.2 appears to be latest so returning Valid
[下午7:15:10] [DevTools] [Info] Spawning D:\flutter\bin\cache\dart-sdk\bin\pub.bat with args ["global","run","devtools","--machine","--try-ports","10","--allow-embedding"]
[下午7:15:10] [DevTools] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[下午7:15:10] [DevTools] [Info]     PID: 17116
[下午7:15:10] [DevTools] [Info] <== {"event":"server.started","method":"server.started","params":{"host":"127.0.0.1","port":9100,"pid":14108,"protocolVersion":"1.1.0"}}
[下午7:15:10] [DevTools] [Info] ==> {"id":"1","method":"vm.register","params":{"uri":"http://127.0.0.1:56842/TJokpmLi9mk=/"}}
[下午7:15:10] [DevTools] [Info] <== {"id":"1","result":{"success":true}}
[下午7:15:12] [DevTools] [Info] <== {"event":"client.launch","params":{"reused":false,"notified":false,"pid":7732}}
Wed Jun 09 2021 [19:15:49 GMT+0800 (中国标准时间)] Log file ended

**Comment by DanTup** [comment] 2021-06-09 16:41
@WangMiaoGit thanks! That last log worked, it contained this:

```
[下午7:15:09] [General] [Info] Spawning D:\flutter\bin\cache\dart-sdk\bin\pub.bat with args ["global","list"]
[下午7:15:09] [CommandProcesses] [Info] (PROC 17344) Logging data for process...
[下午7:15:10] [CommandProcesses] [Info] (PROC 17344) devtools 2.3.2
[下午7:15:10] [CommandProcesses] [Info] (PROC 17344)
[下午7:15:10] [CommandProcesses] [Info] (PROC 17344) exited (0, null)
[下午7:15:10] [CommandProcesses] [Info] (PROC 17344) closed (0, null)
[下午7:15:10] [General] [Info] devtools version 2.3.2 appears to be latest so returning Valid
```

I'm not sure why you didn't see the same output when running `pub global list` manually, but it confirms you're using a version of DevTools that includes the original fix described above.

If you click on Dart DevTools in the status bar, and then click Open in Browser, do you see the same behaviour in a normal browser, or does it only occur in the embedded VS Code window?

**Comment by WangMiaoGit** [comment] 2021-06-10 02:28
The same thing happens in the browser
![image](https://user-images.githubusercontent.com/22518556/121455118-8666cb00-c9d6-11eb-827e-7f0bc7581954.png)

**Comment by DanTup** [comment] 2021-06-10 09:44
@WangMiaoGit thanks for confirming. It's probably not related to this original issue then, so let's open a new issue.

Can you also include in it whether there are any errors listed in the Chrome developer tools (in the Chrome menu click More Tools -> Developer Tools, and then on the Console tab). Thanks!

**Comment by DanTup** [comment] 2021-06-10 09:47
Actually, I think this is probably the same as https://github.com/Dart-Code/Dart-Code/issues/3400. Let's follow up there.

**Comment by WangMiaoGit** [comment] 2021-06-10 09:58
new issue 
https://github.com/flutter/devtools/issues/3105
