### ISSUE TITLE
CPU Profiler source columns is truncated unnecessarily

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#3516] opened 2021-11-29 18:21 UTC
When CPU profiling, the Source column is truncated even though there's a lot of available space. The heading seems to be the expected width (since the text is centered over the whole column), but the text is being truncated within the cell much sooner than it seems it needs to be:

![Screenshot 2021-11-29 at 18 19 18](https://user-images.githubusercontent.com/1078012/143921732-20ceecb5-615a-4cbb-a07f-fcb10dd71181.png)

Here's an export of the data:

[dart_devtools_2021_11_29-1638209993648000.json.zip](https://github.com/flutter/devtools/files/7620322/dart_devtools_2021_11_29-1638209993648000.json.zip)

The screenshot above shows the size of the window (it's on an external ultra-wide monitor, although the window is not the full width).

**Comment by kenzieschmoll** [comment] 2021-11-30 21:43
Agreed, this is a poor experience. Duplicate of https://github.com/flutter/devtools/issues/2047.

**Closed by kenzieschmoll** 2021-11-30 21:43 UTC
