### ISSUE TITLE
In Flutter inspector, when I click on any widget, it does not navigate to the respective source code, this was working properly previously. Problem happening in VSCode

### ISSUE THREAD

**Issue by muj-i** [flutter/devtools#6883] opened 2023-12-02 20:57 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 3.1.3
Flutter Version: 3.13.7 / stable
Framework / Engine: 2f708eb839 / a794cf2681
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment] 2023-12-04 18:09
closing as a duplicate of https://github.com/flutter/devtools/issues/6876. Please see the discussion there to resolve your issue. Also, please upgrade to the latest flutter stable to get the most up-to-date DevTools features.

**Closed by kenzieschmoll** 2023-12-04 18:09 UTC
