### ISSUE TITLE
Devtools cannot show traffic while using Dio in Isolate

### ISSUE THREAD

**Issue by vuldk94** [flutter/devtools#7019] opened 2024-01-03 04:36 UTC
When I am using Dio to run in Isolate to get data from network. Devtools cannot show request,response.
It will work well it I use Dio to run in main thread in flutter.

// Not use Isolate: Devtool can show request and response
![Screenshot 2024-01-03 at 11 32 33](https://github.com/flutter/devtools/assets/88432897/37b7c3d2-e7c4-494c-98b2-6ba821f23317)

// Use Isolate: Devtool can not show request and response
![Screenshot 2024-01-03 at 11 34 32](https://github.com/flutter/devtools/assets/88432897/5482ba7a-7dc2-4083-858a-f842b0509c31)

// Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.2.1 22D68 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.0.3
Flutter Version: 3.10.4 / stable
Framework / Engine: 682aa387cf / 2a3401c9bb
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment] 2024-07-17 21:26
This may have been fixed if this is a duplicate of #3033 , but we will need to repro to verify.

**Comment by nicks258** [comment] 2024-07-24 08:56
Still facing the same issus is `DevTools version 2.34.3` with `flutter 3.22.3`

**Comment by elliette** [comment] 2024-11-26 22:17
Closing as a duplicate of https://github.com/flutter/devtools/issues/8380

**Closed by elliette** 2024-11-26 22:17 UTC
Labels: screen: network, fix it friday, P2, reproduce to verify
