### ISSUE TITLE
Expanding certain variables does nothing

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2754] opened 2021-03-01 20:20 UTC
DevTools allows expanding `_Closure`s and `_Type`s.  However, after clicking the variable, only the arrow icon is updated and nothing else happens:

<img width="456" alt="Screen Shot 2021-03-01 at 12 19 55 PM" src="https://user-images.githubusercontent.com/1840773/109553938-790d7c80-7a88-11eb-9e92-91298bfafc3b.png">

**Comment by devoncarew** [comment] 2021-03-01 20:26
We might not have further info here to display. For something like a closure, it would be useful to display where it was defined.  Perhaps we should display a synthetic field on the closure w/ the source location (`location: foo.dart:123:10`)? We'd likely want that to be a hyperlink.

**Comment by grouma** [comment] 2021-03-01 20:30
> We might not have further info here to display. 

If that's the case then we shouldn't display the drill down icon. 

> For something like a closure, it would be useful to display where it was defined.

+1 - Note sure how easy that will be done on the web side of things

**Comment by kenzieschmoll** [comment] 2024-09-27 20:14
closing as a duplicate of https://github.com/flutter/devtools/issues/5377

**Closed by kenzieschmoll** 2024-09-27 20:14 UTC
Labels: screen: debugger
