### ISSUE TITLE
Audit which inspector service extensions are used in DevTools

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5369] opened 2023-03-08 20:53 UTC
Widget inspector service extensions are defined here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/service_extensions.dart#L106

and registered here:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/widget_inspector.dart#L986

We should audit which extensions are actually used in DevTools, and remove the rest. This will prevent us from having to do unnecessary work to make unused extensions work for multiwindow support.

**Comment by kenzieschmoll** [comment] 2023-03-08 21:15
`trackRepaintWidgets` is currently unused in DevTools.
**Recommendation**: do not remove, as this may be used in the Performance page to support showing repaints for a frame.

`disposeAllGroups` is currently unused in DevTools.
**Recommendation**: remove, unless this will actually be needed for multiwindow support (if there are many groups or something like that). 

`disposeId` is currently unused in DevTools.
**Recommendation**: remove.

`setPubRootDirectories` is currently unused in DevTools.
**Recommendation**: do not remove. We can remove if the IDEs move away from this API, but this implementation uses the logic for the new add and remove APIs, so it shouldn't be extra work to leave this for now.

`getParentChain` is currently unused in DevTools.
**Recommendation**: remove. This is unused in DevTools. It has been sitting in [commented out code](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/shared/diagnostics/inspector_service.dart#L1175) for a long time.

`screenshot` is currently unused in DevTools.
**Recommendation**: do not remove. This is something we will likely want to use in the future.

@jacob314 can you please comment if you disagree with any of the recommendations here.
@DanTup and @helin24 can you comment if any of the extensions I have tagged with a remove recommendation are used by the IDEs? Thanks.

**Comment by kenzieschmoll** [comment] 2023-03-08 21:15
FYI @goderbauer

**Comment by goderbauer** [comment] 2023-03-08 21:16
For completeness: Does DevTools make use of any of the other more general service extensions?

* https://github.com/flutter/flutter/blob/ac76dabe6744f4636a86da366ed1a2ce6973f689/packages/flutter/lib/src/widgets/service_extensions.dart#L13
* https://github.com/flutter/flutter/blob/ac76dabe6744f4636a86da366ed1a2ce6973f689/packages/flutter/lib/src/rendering/service_extensions.dart#L13
* https://github.com/flutter/flutter/blob/ac76dabe6744f4636a86da366ed1a2ce6973f689/packages/flutter/lib/src/scheduler/service_extensions.dart#L13
* https://github.com/flutter/flutter/blob/ac76dabe6744f4636a86da366ed1a2ce6973f689/packages/flutter/lib/src/services/service_extensions.dart#L13
* https://github.com/flutter/flutter/blob/ac76dabe6744f4636a86da366ed1a2ce6973f689/packages/flutter/lib/src/foundation/service_extensions.dart#L13

**Comment by goderbauer** [comment] 2023-03-08 21:33
Thanks!

Side question: What is "Flutter DAP"?

> so in time these will become unused by VS Code.

What will mark the end here? Do we just have to wait a certain amount of time? Or wait until a certain version is released?

**Comment by DanTup** [comment] 2023-03-08 21:49
> Side question: What is "Flutter DAP"?

DAP is the [Debug Adapter Protocl](https://microsoft.github.io/debug-adapter-protocol/). It's a protocol for an editor (like VS Code) to talk to a debugger (like the Dart VM/VM Service). If lots of editors and lots of languages adopt this, there is less per-editor-per-language work that needs to be done. We have wrappers over the VM Service that translate into this protocol (they're more structly "DAs" - Debug Adapters, but DAPs is shorter to say 😄).

The original implementation of the DAP was inside Dart-Code (written in TypeScript), and was intended only for use by VS Code (so it had a lot of customisations). The new DAP implementations like in the Dart/Flutter SDKs and are written in Dart (and usable by many other DAP-compliant editors):

- https://github.com/dart-lang/sdk/blob/main/pkg/dds/tool/dap/README.md
- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/README.md

> What will mark the end here? Do we just have to wait a certain amount of time? Or wait until a certain version is released?

After Dart 3 ships, I hope to begin migrating VS Code users over to the new ones. How quickly this occurs depends on whether we find any significant bugs in them. We found some blocking bugs with the last stable release so the migration was postponed. Those issues are fixed now and I plan to begin re-enabling the new SDK DAPs for Flutter pre-release versions (with all the fixes) once the next DWDS goes out (to get https://github.com/dart-lang/webdev/pull/2011).

**Comment by goderbauer** [comment] 2023-03-08 22:37
To make it easier to see what is and isn't used I translated the information on this bug into a spreadsheet: https://docs.google.com/spreadsheets/d/1i1RW8Q0pNxBc6vWva9y5Wp_EPNoE6uyJqrIUwGGb_mM/edit#gid=0

 If people could fill in some of the missing information, I'd appreciate it.

I also added `flutter_tools` as a user of these extension.

**Comment by helin24** [comment] 2023-03-08 23:15
@kenzieschmoll among the ones you tagged as 'remove', `getParentChain` is used by IntelliJ.

@goderbauer I noted in the IntelliJ column which service extensions NOT used by DevTools are still used by IntelliJ, but I didn't look for all of the service extensions. If there are other that may be removed based on our usage let me know and I'll check.

**Comment by kenzieschmoll** [comment] 2023-03-13 22:52
Finished updating spreadsheet for DevTools extensions @goderbauer

**Comment by kenzieschmoll** [comment] 2023-03-13 23:20
Closing as this audit is complete from the DevTools perspective.

**Closed** 2023-03-13 23:19 UTC
Labels: inspector page
