### ISSUE TITLE
Network tab - InternetAddress shows without any implementation in Code

### ISSUE THREAD

**Issue by frelei** [flutter/devtools#7878] opened 2024-06-03 04:04 UTC
Hello, 

I am checking the requests in the DevTool and found many InternetAddress, status code 101, and web socket. They are increasing the time of the requests. 

The community I check some people facing the same problem as shown in the [link](https://github.com/flutter/devtools/issues/2860#issuecomment-814564954)

I would like to understand why this happen and if we can block this behaviour. 

Thanks.

**Comment by affansk** [comment] 2024-06-07 16:43
@frelei  this is happening to me as well

**Comment by frelei** [comment] 2024-06-10 20:12
Hello @affansk, 

I didn't find any solution and don't know why this is happening. 
I would like to know if this is something related to devtools or if it works like that.

**Comment by hrajwade96** [comment] 2024-06-19 11:05
I am facing this issue currently while working on some code in master branch 

Flutter 3.21.0-15.0.pre • channel [user-branch] • unknown source
Framework • revision c09c65ff46 (3 months ago) • 2024-03-26 22:41:11 -0400
Engine • revision d872d50e53
Tools • Dart 3.4.0 (build 3.4.0-275.0.dev) • DevTools 2.34.0-dev.12

Output in dev tools (run on dev channel)
<img width="1025" alt="image" src="https://github.com/flutter/devtools/assets/33225260/f24d1570-b830-41ab-a510-f0dccf73eea4">


Output from stable 
<img width="1238" alt="image" src="https://github.com/flutter/devtools/assets/33225260/e1622963-7127-4c09-80d5-0e1c4c13e21a">


Can someone help me to fix this? It's blocking my code testing

**Comment by hrajwade96** [comment] 2024-06-22 08:54
It worked for me now, 
It was due to my vanilla app pointing to an older flutter SDK.

**Comment by mohamedshasho** [comment] 2024-07-04 07:16
the same issue:
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by kenzieschmoll** [comment] 2024-07-17 18:27
This is a duplicate of https://github.com/flutter/devtools/issues/3033, which is now fixed.

**Closed by kenzieschmoll** 2024-07-17 18:27 UTC
Labels: bug, network page, P1
