### ISSUE TITLE
Widget inspector page hang

### ISSUE THREAD

**Issue by jeiea** [flutter/devtools#2726] opened 2021-02-23 02:56 UTC
## What I did
1. vscode dart extension `3.19.2`, flutter `3.19.0`
1. Open widget inspector page. Either embedded or browser is no matter.
2. Select some deep component (No exact condition is found here).
3. Click details tree.

## Expected behavior
No hang occurs.

## Actual behavior
The following is the screenshot of hang. Details tree button is freezed with ripple effect.

<img src="https://user-images.githubusercontent.com/4188984/108796610-73b5bb00-75cc-11eb-9194-ef1a09119cac.png" width=300 />

## Additional context

Source of not exiting loop.
```
// main.dart.js:940
    _findMinimumFontsForCodeunits: function(codeunits, fonts) {
      var language, t2, t3, t4, t5, t6, t7, t8, t9, t10, maxCodeunitsCovered, _box_0, t11, t12, t13, codeunitsCovered, _i,
        unmatchedCodeunits = P.List_List$from(codeunits, true, type$.int),
        minimumFonts = P.LinkedHashSet_LinkedHashSet$_empty(type$._NotoFont),
        bestFonts = H.setRuntimeTypeInfo([], type$.JSArray__NotoFont),
        t1 = window.navigator;
      t1.toString;
      language = t1.language || t1.userLanguage;
      for (t1 = H._instanceType(fonts)._eval$1("_LinkedHashSetIterator<1>"), t2 = language === "ja", t3 = language === "zh-HK", t4 = language !== "zh-Hant", t5 = language !== "zh-Hans", t6 = language !== "zh-CN", t7 = language !== "zh-SG", t8 = language === "zh-MY", t9 = language !== "zh-TW", t10 = language === "zh-MO", maxCodeunitsCovered = 0; unmatchedCodeunits.length !== 0;) {
        _box_0 = {};
        for (t11 = new P._LinkedHashSetIterator(fonts, fonts._collection$_modifications, t1), t11._collection$_cell = fonts._collection$_first; t11.moveNext$0();) {
          t12 = t11._collection$_current;
          for (t13 = unmatchedCodeunits.length, codeunitsCovered = 0, _i = 0; _i < unmatchedCodeunits.length; unmatchedCodeunits.length === t13 || (0, H.throwConcurrentModificationError)(unmatchedCodeunits), ++_i)
            if (t12.matchesCodeunit$1(unmatchedCodeunits[_i]))
              ++codeunitsCovered;
          if (codeunitsCovered > maxCodeunitsCovered) {
            C.JSArray_methods.set$length(bestFonts, 0);
            bestFonts.push(t12);
            maxCodeunitsCovered = codeunitsCovered;
          } else if (codeunitsCovered === maxCodeunitsCovered)
            bestFonts.push(t12);
        }
        _box_0.bestFont = C.JSArray_methods.get$first(bestFonts);
        if (bestFonts.length > 1)
          if (C.JSArray_methods.every$1(bestFonts, new H._findMinimumFontsForCodeunits_closure()))
            if (!t5 || !t6 || !t7 || t8) {
              if (C.JSArray_methods.contains$1(bestFonts, $.$get$_notoSansSC()))
                _box_0.bestFont = $.$get$_notoSansSC();
            } else if (!t4 || !t9 || t10) {
              if (C.JSArray_methods.contains$1(bestFonts, $.$get$_notoSansTC()))
                _box_0.bestFont = $.$get$_notoSansTC();
            } else if (t3) {
              if (C.JSArray_methods.contains$1(bestFonts, $.$get$_notoSansHK()))
                _box_0.bestFont = $.$get$_notoSansHK();
            } else if (t2)
              if (C.JSArray_methods.contains$1(bestFonts, $.$get$_notoSansJP()))
                _box_0.bestFont = $.$get$_notoSansJP();
        if (!!unmatchedCodeunits.fixed$length)
          H.throwExpression(P.UnsupportedError$("removeWhere"));
        C.JSArray_methods._removeWhere$2(unmatchedCodeunits, new H._findMinimumFontsForCodeunits_closure0(_box_0), true);
        minimumFonts.add$1(0, _box_0.bestFont);
      }
      return minimumFonts;
    },
```

Stack trace

```
_findMinimumFontsForCodeunits (main.dart.js:980)
(anonymous) (main.dart.js:776)
(anonymous) (main.dart.js:11460)
call$2 (main.dart.js:78101)
_asyncStartSync (main.dart.js:11424)
_findFontsForMissingCodeunits (main.dart.js:824)
_ensureFontsSupportText$1 (main.dart.js:59427)
addText$1 (main.dart.js:59431)
build$3$dimensions$textScaleFactor (main.dart.js:156959)
build$3$dimensions$textScaleFactor$x (main.dart.js:10811)
build$3$dimensions$textScaleFactor (main.dart.js:156963)
layout$2$maxWidth$minWidth (main.dart.js:156744)
_layoutText$2$maxWidth$minWidth (main.dart.js:163160)
_layoutTextWithConstraints$1 (main.dart.js:163173)
performLayout$0 (main.dart.js:163270)
layout$2$parentUsesSize (main.dart.js:161977)
ChildLayoutHelper_layoutChild (main.dart.js:50452)
_computeSizes$2$constraints$layoutChild (main.dart.js:159877)
performLayout$0 (main.dart.js:159894)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:165807)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163794)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
ChildLayoutHelper_layoutChild (main.dart.js:50452)
_computeSizes$2$constraints$layoutChild (main.dart.js:159877)
performLayout$0 (main.dart.js:159894)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
performLayout$0 (main.dart.js:164131)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:165807)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
performLayout$0 (main.dart.js:158365)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163794)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
insertAndLayoutChild$3$after$parentUsesSize (main.dart.js:166931)
insertAndLayoutChild$2$after (main.dart.js:166938)
performLayout$0 (main.dart.js:166454)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:167274)
performLayout$0 (main.dart.js:167396)
layout$2$parentUsesSize (main.dart.js:161977)
layoutChildSequence$11$advance$cacheOrigin$child$crossAxisExtent$growthDirection$layoutOffset$mainAxisExtent$overlap$remainingCacheExtent$remainingPaintExtent$scrollOffset (main.dart.js:168684)
_attemptLayout$3 (main.dart.js:169150)
performLayout$0 (main.dart.js:169096)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
performLayout$0 (main.dart.js:158365)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163794)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:192708)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
performLayout$0 (main.dart.js:158365)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:163679)
layout$2$parentUsesSize (main.dart.js:161977)
insertAndLayoutChild$3$after$parentUsesSize (main.dart.js:166931)
insertAndLayoutChild$2$after (main.dart.js:166938)
performLayout$0 (main.dart.js:166454)
layout$2$parentUsesSize (main.dart.js:161977)
performLayout$0 (main.dart.js:167274)
performLayout$0 (main.dart.js:193370)
layout$2$parentUsesSize (main.dart.js:161977)
layoutChildSequence$11$advance$cacheOrigin$child$crossAxisExtent$growthDirection$layoutOffset$mainAxisExtent$overlap$remainingCacheExtent$remainingPaintExtent$scrollOffset (main.dart.js:168684)
_attemptLayout$3 (main.dart.js:169150)
performLayout$0 (main.dart.js:169096)
_layoutWithoutResize$0 (main.dart.js:161942)
flushLayout$0 (main.dart.js:161735)
drawFrame$0 (main.dart.js:157555)
drawFrame$0 (main.dart.js:177827)
_handlePersistentFrameCallback$1 (main.dart.js:157542)
(anonymous) (VM1296:3)
_invokeFrameCallback$3 (main.dart.js:170453)
_invokeFrameCallback$2 (main.dart.js:170464)
handleDrawFrame$0 (main.dart.js:170432)
_handleDrawFrame$0 (main.dart.js:170400)
(anonymous) (VM1338:3)
invoke (main.dart.js:2306)
call$1 (main.dart.js:54851)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
_ticker$_tick$1 (main.dart.js:170623)
eval (VM1408:3)
_invokeFrameCallback$3 (main.dart.js:170453)
call$2 (main.dart.js:170537)
forEach$1 (main.dart.js:77061)
forEach$1$ax (main.dart.js:10958)
handleBeginFrame$1 (main.dart.js:170417)
_handleBeginFrame$1 (main.dart.js:170391)
eval (VM1336:3)
invoke1 (main.dart.js:2314)
call$1 (main.dart.js:54847)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
requestAnimationFrame (async)
_requestAnimationFrame$1 (main.dart.js:88283)
requestAnimationFrame$1 (main.dart.js:88280)
call$0 (main.dart.js:54831)
scheduleFrame$0 (main.dart.js:65827)
scheduleFrame$0 (main.dart.js:170353)
scheduleFrameCallback$2$rescheduling (main.dart.js:170294)
start$0 (main.dart.js:170587)
_startSimulation$1 (main.dart.js:131624)
_animateToInternal$3$curve$duration (main.dart.js:131598)
_animateToInternal$1 (main.dart.js:131601)
forward$1$from (main.dart.js:131554)
forward$0 (main.dart.js:131557)
create$11$borderRadius$color$containedInkWell$controller$customBorder$onRemoved$position$radius$rectCallback$referenceBox$textDirection (main.dart.js:141684)
_createInkFeature$1 (main.dart.js:142035)
_startSplash$2$context$details (main.dart.js:142097)
_startSplash$1$details (main.dart.js:142105)
_handleTapDown$1 (main.dart.js:142083)
eval (VM1503:3)
call$0 (main.dart.js:137340)
invokeCallback$1$3$debugReport (main.dart.js:136961)
invokeCallback$2 (main.dart.js:136973)
handleTapDown$1$down (main.dart.js:137291)
_tap$_checkDown$0 (main.dart.js:137235)
acceptGesture$1 (main.dart.js:137212)
_resolveByDefault$2 (main.dart.js:135284)
call$0 (main.dart.js:135305)
_microtaskLoop (main.dart.js:11822)
_startMicrotaskLoop (main.dart.js:11828)
call$1 (main.dart.js:77960)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
childList (async)
call$1 (main.dart.js:77970)
_scheduleAsyncCallback (main.dart.js:11842)
_rootScheduleMicrotask (main.dart.js:12087)
scheduleMicrotask (main.dart.js:11871)
_tryToResolveArena$2 (main.dart.js:135270)
close$1 (main.dart.js:135218)
handleEvent$2 (main.dart.js:135400)
dispatchEvent$2 (main.dart.js:135385)
dispatchEvent$2 (main.dart.js:177778)
_handlePointerEventImmediately$1 (main.dart.js:135358)
handlePointerEvent$1 (main.dart.js:135339)
_flushPointerEventQueue$0 (main.dart.js:135335)
_handlePointerDataPacket$1 (main.dart.js:135325)
eval (VM1270:3)
invoke1 (main.dart.js:2314)
_onPointerData$1 (main.dart.js:65995)
eval (VM780:3)
call$1 (main.dart.js:66294)
call$1 (main.dart.js:66274)
call$1 (main.dart.js:66029)
invokeClosure (main.dart.js:7522)
(anonymous) (main.dart.js:7541)
```

Local variables
```
bestFonts: [_NotoFont, Symbol($ti): Rti]
codeunits: _LinkedHashSet {_collection$_length: 3, _collection$_strings: null, _collection$_nums: {…}, _collection$_rest: null, _collection$_first: _LinkedHashSetCell, …}
codeunitsCovered: 0
fonts: _LinkedHashSet {_collection$_length: 14, _collection$_strings: null, _collection$_nums: null, _collection$_rest: {…}, _collection$_first: _LinkedHashSetCell, …}
language: undefined
maxCodeunitsCovered: 2
minimumFonts: _LinkedHashSet {_collection$_length: 1, _collection$_strings: null, _collection$_nums: null, _collection$_rest: {…}, _collection$_first: _LinkedHashSetCell, …}
t1: Rti {_precomputed1: Rti, _specializedTestResource: null, _cachedRuntimeType: null, _as: ƒ, _is: ƒ, …}
t2: false
t3: false
t4: true
t5: true
t6: true
t7: true
t8: false
t9: true
t10: false
t11: _LinkedHashSetIterator {_set: _LinkedHashSet, _collection$_modifications: 14, _collection$_cell: null, _collection$_current: null, $ti: Rti}
t12: _NotoFont {name: "Noto Sans KR", unicodeRanges: Array(4), _decodingCompleter: null, resolvedFont: null, $identityHash: 1034253062}
t13: 1
this: Object
unmatchedCodeunits: [8205, Symbol($ti): Rti]
_box_0: {bestFont: _NotoFont}
_i: 1
```

**Comment by kenzieschmoll** [comment] 2021-03-06 00:42
@jeiea can you reproduce this when you open the DevTools inspector in the browser, or only inside of VS code?

@jacob314 does any of this stack trace look inspector related? It all looks like it is from the flutter framework to me.
@DanTup FYI

**Comment by jeiea** [comment] 2021-03-06 00:45
It was reproduced on both browser and vscode IIRC.

**Comment by jacob314** [comment] 2021-03-30 17:45
This is a CanvasKit error. It was fixed by https://github.com/flutter/engine/commit/bcd8c7158f6c36699076dc3bf198394954c5326c#diff-e362c1065aa95fcceabf51625fc6f3056bd905003570938f7658c6c75456eae0

**Closed by jacob314** 2021-03-30 17:45 UTC
Labels: bug
