### ISSUE TITLE
Unable to select/copy more than one line in the Inspector's console view (probably console anywhere).

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#3241] opened 2021-08-03 13:58 UTC
Console window should be fully select-able and copy-able. Clicking on the line:

`  > Exception caught by Flutter framework
`
Pressing the copy button only copies the line selected unable to copy its contents or use multiple line selection.

![image](https://user-images.githubusercontent.com/2055873/128027749-28bbad42-04e2-42ec-9e35-9d65c64b9bda.png)

See https://github.com/flutter/devtools/issues/3240

**Comment by kenzieschmoll** [comment] 2024-08-21 21:09
Duplicate of https://github.com/flutter/devtools/issues/5389

**Closed by kenzieschmoll** 2024-08-21 21:09 UTC
Labels: console component, P2, reproduce to verify
