### ISSUE TITLE
Crash on flutter_web when selecting anything in widget select mode.

### ISSUE THREAD

**Issue by Markzipan** [flutter/devtools#562] opened 2019-04-20 00:20 UTC
webdev: webdev 2.0.0-alpha.4
dart: 2.2.1

Clicking anything on the flutter_web gallery emits this error:
```
main.dart.js:2747 DevTools version 0.0.16.
main.dart.js:2747 Unrecognized error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>' (-32603) from evaluate()
main.dart.js:19738 Uncaught TypeError: Cannot read property 'valueAsString' of undefined
    at main.dart.js:35021
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:3480)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:17696)
    at _awaitOnObject_closure.call$1 (main.dart.js:17682)
    at _RootZone.runUnary$2$2 (main.dart.js:19813)
    at _Future__propagateToListeners_handleValueCallback.call$0 (main.dart.js:18520)
    at Object._Future__propagateToListeners (main.dart.js:3680)
    at _Future._complete$1 (main.dart.js:18346)
    at _SyncCompleter.complete$1 (main.dart.js:18180)
    at Object.eval (eval at Closure_forwardInterceptedCallTo (main.dart.js:1556), <anonymous>:3:38)
main.dart.js:2747 Unrecognized error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>' (-32603) from evaluate()
main.dart.js:19738 Uncaught TypeError: Cannot read property 'valueAsString' of undefined
    at main.dart.js:35021
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:3480)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:17696)
    at _awaitOnObject_closure.call$1 (main.dart.js:17682)
    at _RootZone.runUnary$2$2 (main.dart.js:19813)
    at _Future__propagateToListeners_handleValueCallback.call$0 (main.dart.js:18520)
    at Object._Future__propagateToListeners (main.dart.js:3680)
    at _Future._complete$1 (main.dart.js:18346)
    at _SyncCompleter.complete$1 (main.dart.js:18180)
    at Object.eval (eval at Closure_forwardInterceptedCallTo (main.dart.js:1556), <anonymous>:3:38)
```

This could just be an error on my local machine, as Nick couldn't reproduce this on his machine. I ran 'pub upgrade' as well.

**Comment by efortuna** [comment] 2019-04-24 00:00
I am seeing this as well, and this is a blocker for our I/O talk for a certain high profile feature we want to show.

**Comment by efortuna** [comment] 2019-04-24 00:00
cc @jacob314 @jakemac53 @grouma

**Comment by efortuna** [comment] 2019-04-24 00:02
I am running:
webdev: webdev 2.0.0
dart:  2.3.0-dev.0.1 cf4444b803
(Flutter 1.5.4 • channel dev • Framework revision b593f5167b )

**Comment by devoncarew** [comment] 2019-04-24 00:09
I think these are two separate errors:

```
main.dart.js:2747 Unrecognized error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>' (-32603) from evaluate()
```

This looks like it's happening in webdev (possibly in response to an `evaluate` request?).


And this:

```
main.dart.js:19738 Uncaught TypeError: Cannot read property 'valueAsString' of undefined
    at main.dart.js:35021
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:3480)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:17696)
    at _awaitOnObject_closure.call$1 (main.dart.js:17682)
    at _RootZone.runUnary$2$2 (main.dart.js:19813)
    at _Future__propagateToListeners_handleValueCallback.call$0 (main.dart.js:18520)
    at Object._Future__propagateToListeners (main.dart.js:3680)
    at _Future._complete$1 (main.dart.js:18346)
    at _SyncCompleter.complete$1 (main.dart.js:18180)
```

Looks like it's from the devtools inspector code. We may need to try and repo locally, and use ddc to get good line numbers, to figure out what's happening here.

**Comment by efortuna** [comment] 2019-04-24 00:13
cc @jmesserly Jenny was looking into this and can probably give a few more details.

**Comment by jmesserly** [comment] 2019-04-24 01:01
Yeah the two errors seem related. The type error happens in the evaluate call, and after the error is caught on the devtools side, it calls _handleError and returns null. The null leads to the devtools stacktrace.

There's no stack trace from the evaluate call, so I'm not sure where the type error is comping from, but it seemed to be inside WidgetInspectorService.

**Comment by jacob314** [comment] 2019-04-24 03:41
We're getting strange output back when we call eval. Lets sync up in the morning and figure out what fraction of eval calls are expected to work. We can disable all eval calls that won't work when we detect the app is running flutter_web.

**Comment by devoncarew** [comment] 2019-04-24 03:49
I found one or two initial issues, but still see:

```
Uncaught, null, 771, 18, object null
#0      WipRuntime.evaluate (package:webkit_inspection_protocol/src/runtime.dart:23:7)
<asynchronous suspension>
#1      ChromeProxyService.evaluate (package:dwds/src/chrome_proxy_service.dart:254:46)
<asynchronous suspension>
#2      VmServerConnection._delegateRequest (package:vm_service_lib/vm_service_lib.dart:749:51)
<asynchronous suspension>
```

once those are addressed, so I suspect there's more to do here in terms of getting things plumbed end to end.

**Comment by jakemac53** [comment] 2019-04-24 16:33
`'_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>'` This actually sounds like it could be the result of calling a bad service extension? Service extensions have to return a `Map<String, String>` but they aren't written in a way that gives good static errors if I recall.

**Comment by devoncarew** [comment] 2019-04-24 16:53
That should be addressed by the package:vm_service_lib above. The fix has been published as `3.15.1+1` but needs to be rolled into webdev.

**Comment by vsmenon** [comment] 2019-04-24 17:57
@jakemac53 @grouma - looks like we'll need to bump webdev.

**Comment by grouma** [comment] 2019-04-24 18:16
@jakemac53 is gonna take a look at this one.

**Comment by jakemac53** [comment] 2019-04-25 16:56
I have a cl to surface the errors better here now, it looks like the actual attempted eval is this `WidgetInspectorService.instance.setSelection(arg1, 'dummy_4')`. Which is failing because `arg1` is not defined.

**Comment by jakemac53** [comment] 2019-04-25 17:12
Ahh, this is because we don't support `scope` in `eval`.

I can update this to throw a more descriptive error at least for now, and we can work on investigating what that would take to support.

**Comment by efortuna** [comment] 2019-04-25 17:26
I absolutely need some variant of this to work by May 5th. Ideally much earlier. This functionality used to work for me. Is there a way I can downgrade to a previous version with this functionality?

**Comment by jacob314** [comment] 2019-04-25 17:29
We will have this fixed today.

**Comment by jakemac53** [comment] 2019-04-25 17:41
Ok - so while this is an existing issue it doesn't seem like the core problem (selection does generally work through the regular webdev serve command).

Where this is actually breaking down is in the vscode integration, when launching from vscode if you try to inspect any widgets you lose the entire widget tree in devtools.

**Comment by efortuna** [comment] 2019-04-25 17:45
@jakemac53 should I open a separate bug for that?

**Comment by jakemac53** [comment] 2019-04-25 17:46
Sure - probably on the [webdev repo](https://github.com/dart-lang/webdev)

**Comment by jacob314** [comment] 2019-04-25 22:15
@DanTup The problem is VSCode is setting the pubRootDirectory on inspect.
It turns out that the kernel transformer for flutter_web is creating wacky paths so we need to stop setting the pubRootDirectory on inspect from VSCode for flutter_web.

**Comment by DanTup** [comment] 2019-04-30 09:42
I've stopped sending `setPubRootDirectories` requests for web apps (it'll be in the release I hope to do today, if we can release DevTools).

**Comment by kenzieschmoll** [comment] 2019-07-23 18:14
@jacob314 @DanTup Is this issue resolved / obsolete?

**Comment by DanTup** [comment] 2019-07-25 09:31
Yep, we stopped sending `setPubRootDirectories` back in April. We'll need to put it back at some point in a way that won't crash, but there are issues in VS Code tracking that (the ongoing discussions about path formats are somewhat related).

**Closed by DanTup** 2019-07-25 09:31 UTC
