### ISSUE TITLE
mac  Open the network, a monitor traffic, the page becomes gray

### ISSUE THREAD

**Issue by liwangyong** [flutter/devtools#2278] opened 2020-08-17 08:42 UTC

**Comment by liwangyong** [comment] 2020-08-17 08:44
<img width="1660" alt="WechatIMG900" src="https://user-images.githubusercontent.com/50942378/90376325-d7ed4480-e0a8-11ea-812f-7ca10b09a2da.png">

**Comment by jpnaveenkumar** [comment] 2020-08-17 16:13
<img width="1440" alt="Screenshot 2020-08-18 at 12 10 08 AM" src="https://user-images.githubusercontent.com/22998437/90418217-6b456a80-e0e7-11ea-828b-3efa469ea246.png">

Even after switching to the fallback version of the dev tools, the problem persists!!

**Comment by kenzieschmoll** [comment] 2020-08-17 16:21
Are there errors in the Chrome dev console?

**Comment by kenzieschmoll** [comment] 2020-08-17 16:44
Likely a dupe of https://github.com/flutter/devtools/issues/2257. Still interested to see the errors in the chrome console, however. If it is the same issue, a fix has been committed, but not released. This issue seems to be getting hit by a lot of users, so I'll try to get a dev release out with the fix.

**Closed** 2020-08-17 16:49 UTC

**Comment by kenzieschmoll** [comment] 2020-08-17 18:03
I published 0.9.1-dev.3, which includes the fix for this bug. You can use this version of DevTools by running `flutter pub global activate devtools 0.9.1-dev.3`, followed by `flutter pub global run devtools`. This fix will also be included in the next stable release at the end of the month.
