### ISSUE TITLE
Its just opening root folder,

### ISSUE THREAD

**Issue by akagupta9** [flutter/devtools#5309] opened 2023-02-25 15:02 UTC
<-- Please describe your problem here. Be sure to include repro steps. -->

Flutter widget inspector not working properly.
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.18.6
Flutter Version: 3.3.10 / stable
<img width="1440" alt="Screenshot 2023-02-25 at 8 30 43 PM" src="https://user-images.githubusercontent.com/43808980/221364063-0859b4ad-562b-4f89-abe4-7ded937e3162.png">

Framework / Engine: 135454af32 / 3316dd8728
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment] 2023-02-27 14:38
- @akagupta9 Could you please click on the settings button shown in this screen shot:

<img width="1440" alt="221364063-0859b4ad-562b-4f89-abe4-7ded937e3162" src="https://user-images.githubusercontent.com/1386322/221591653-0d81cd63-1633-4b95-8539-24941d5d1ebb.png">

- Then could you please manually add the full path to your project, in the "Package Directories", for example:
![Screenshot 2023-02-27 at 9 35 01 AM](https://user-images.githubusercontent.com/1386322/221592164-c9153584-19ea-43ac-b728-4363c0e319a0.png)

- If that doesn't work could you please try deleting all of your package directories, then closing and re-opening the widget inspector.
After a couple of seconds it should try to guess your package directories and fill them in

**Comment by kenzieschmoll** [comment] 2023-05-26 22:17
Closing due to no response. If you can reproduce this issue on the latest version of Flutter stable, please feel free to reopen.

**Closed by kenzieschmoll** 2023-05-26 22:17 UTC
Labels: waiting for customer response
