### ISSUE TITLE
Starting dev tool in browser results in blank page

### ISSUE THREAD

**Issue by jd-debug** [flutter/devtools#2825] opened 2021-03-22 09:48 UTC
Hello all, 
when trying to run the dev tool, only a blank page is shown.
![b1](https://user-images.githubusercontent.com/70584516/111970429-8fdd4700-8afb-11eb-802a-9aeebbac1d15.PNG)

I tested this for channel stable and beta, in both cases in the browser console I get: 
`Failed to load resource: /assets/packages/codicon/lib/font/codicon.ttf the server responded with a status of 404 (Not Found)`

My flutter doctor looks like this:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.17763.1518], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] Connected device (2 available)
```
I also tried:
```
flutter clean
flutter pub cache repair
flutter pub global activate devtools
flutter pub global run devtools 
```
With the same result. 

Does anyone have a clue what I am missing? Any tips are appreciated. Thanks.

**Comment by kenzieschmoll** [comment] 2021-03-23 16:08
duplicate of https://github.com/flutter/devtools/issues/2759

**Closed by kenzieschmoll** 2021-03-23 16:08 UTC
