### ISSUE TITLE
Got "Installing Devtools" message forever. Flutter Inspector doesn't start 

### ISSUE THREAD

**Issue by AntonFesun** [flutter/devtools#2521] opened 2020-11-27 11:46 UTC
Version of Flutter plugin: 51.0.2
Dart plugin: 201.9245
OS: Windows 10
IDE: Android Studio 4.1.1.

https://prnt.sc/vr6el9

When trying to execute these commands:

flutter.bat pub global deactivate devtools

flutter.bat pub global activate devtools
Resolving dependencies...
+ args 1.6.0
+ async 2.4.2
+ browser_launcher 0.1.7
+ charcode 1.1.3
+ collection 1.14.13
+ convert 2.1.1
+ crypto 2.1.5
+ devtools 0.9.3+4 (0.9.4 available)
+ devtools_server 0.9.3+4 (0.9.4 available)
+ devtools_shared 0.9.3+4 (0.9.4 available)
+ http 0.12.2
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ intl 0.16.1
+ logging 0.11.4
+ meta 1.2.4
+ mime 0.9.7
+ path 1.7.0
+ pedantic 1.9.2
+ shelf 0.7.9
+ shelf_proxy 0.1.0+7
+ shelf_static 0.2.8
+ source_span 1.7.0
+ sse 3.6.0
+ stack_trace 1.9.6
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ usage 3.4.2
+ uuid 2.2.2
+ vm_service 5.5.0
+ webkit_inspection_protocol 0.7.4
Installed executable devtools.
Warning: Executable "devtools" runs "bin\devtools.dart", which was not found in devtools.
Activated devtools 0.9.3+4.

flutter.bat pub global run devtools - throw this error: 
Could not find bin\devtools.dart in package devtools.
pub finished with exit code 66

**Comment by jacob314** [comment] 2020-11-30 15:15
@helin24 we should see if we can reproduce this on our end.
@AntonFesun what version of the Flutter SDK are you using? It appears it may be old enough that we are activating devtools 0.9.3+4 instead of 0.9.4?

**Comment by AntonFesun** [comment] 2020-11-30 15:21
Hi @jacob314
flutter --version: 
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (2 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

Is that you need?

**Comment by AntonFesun** [comment] 2020-12-03 13:33
@jacob314 I have some updates...
I've tried to start devtools with another command: >pub global run devtools.
It shows me, that devtools running at http://127.0.0.1:9100, there i pasted a url (got it from console): 
Successfully connected to service protocol: http://127.0.0.1:64722/k1p6_Si3idU=/ into devtools in browser, and it works, but in Android Studion it still doesn't((

**Comment by helin24** [comment] 2020-12-03 16:27
Thanks for the details! I think this is a duplicate of https://github.com/flutter/flutter-intellij/issues/5032.

**Closed by helin24** 2020-12-03 16:27 UTC
Labels: bug, intellij integration
