### ISSUE TITLE
HTTP Log issue

### ISSUE THREAD

**Issue by zantdev** [flutter/devtools#7974] opened 2024-06-25 04:56 UTC
I can not see http network log. Only showing websocket log
___
**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.3
Flutter Version: 3.22.2 / stable
Framework / Engine: 761747bfc5 / edd8546116

**Comment by kenzieschmoll** [comment] 2024-07-15 22:55
closing as a duplicate of https://github.com/flutter/devtools/issues/3033

**Comment by kenzieschmoll** [comment] 2024-07-17 18:28
This is a duplicate of https://github.com/flutter/devtools/issues/3033, which is now fixed.

**Closed by kenzieschmoll** 2024-07-17 18:28 UTC
Labels: network page, P1
