### ISSUE TITLE
setting breakpoints doesn't work when devtools is launched from IntelliJ

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#695] opened 2019-05-30 20:17 UTC
I'm not able to consistently set breakpoints in the debugger page.

**Comment by devoncarew** [comment] 2019-05-30 20:20
This seems to happen when you've launched devtools from IntelliJ.

**Comment by devoncarew** [comment] 2019-06-08 21:33
I'm having trouble reproing this now.

**Comment by devoncarew** [comment] 2019-06-08 21:50
This may happen after a hot restart is performed; the older breakpoints may not be removed, and may still point to the previous scripts (and, new breakpoints for the new scripts are not set).

**Comment by devoncarew** [comment] 2019-06-10 15:31
Most of the issues do seem to be related to breakpoints (and other debugger features) not working as well after the app has been restarted. I think after a restart we'll need to re-load the list of scripts (and update this in the UI).

I don't believe we get an event when a script is re-loaded (via hot reload). We get a `kPausePostRequest` event which we can use to know we have to reload some data.

It could also be useful for the VM to fire an event after a script is reloaded (not for the ~800 initial scripts, but for deltas after an isolate has started). This could be generally useful for tools. cc @bkonyi

**Comment by jacob314** [comment] 2019-06-17 23:27
Set the milestone for this one aggressively to 0.1.2. The issue is indeed hot restart/reload related. We need to re-initialize breakpoints after a restart/reload and there are some tricky edge cases we need to work through when multiple IDEs are connected.

**Comment by elliette** [comment] 2024-11-19 22:19
This was fixed with https://github.com/flutter/devtools/issues/7231

**Closed by elliette** 2024-11-19 22:19 UTC
Labels: bug, screen: debugger, P2, reproduce to verify
