### ISSUE TITLE
Layout Explorer overflow indicator is not showing correctly

### ISSUE THREAD

**Issue by albertusangga** [flutter/devtools#1495] opened 2019-12-20 22:34 UTC
## Description
On Dart DevTools v0.1.13 alpha version, Layout Explorer is not showing the overflow indicator correctly, it currently shows as black instead of black & yellow striped pattern.

## Dark mode
![image](https://user-images.githubusercontent.com/25892469/71296685-55ec2680-2335-11ea-952e-72c2e65823d3.png)

## Light mode
![image](https://user-images.githubusercontent.com/25892469/71296798-c09d6200-2335-11ea-90aa-0f8dcf2702ff.png)

**Comment by asmaa3107** [comment] 2019-12-24 10:09
Layout Explore tape Not even shown on my dart devtools 
any help , can anyone tell me why this may happen ?

**Comment by jacob314** [comment] 2020-01-07 21:37
Resolving as a duplicate of https://github.com/flutter/devtools/issues/1451

**Closed by jacob314** 2020-01-07 21:37 UTC
Labels: bug
