### ISSUE TITLE
Why does flutter's inspector only display view's structure? Does flutter have some background reasons? Will flutter's inspector change to some tools like chrome devtool(has real app screenshot))

### ISSUE THREAD

**Issue by popoaichuiniu** [flutter/devtools#7003] opened 2023-12-22 04:43 UTC
<img width="1718" alt="image" src="https://github.com/flutter/devtools/assets/15939275/da300c91-3949-4770-9819-34f62dc8dc17">

![image](https://github.com/flutter/devtools/assets/15939275/7f711a59-359d-44b4-8fec-89e25f45dfb7)

**Comment by elliette** [comment] 2024-01-19 18:27
Hi @popoaichuiniu  - when you say "real app snapshot", do you mean:

the app you see on the left? 
![Screenshot 2024-01-19 at 10 26 08 AM](https://github.com/flutter/devtools/assets/21270878/e31d5b4e-6dfd-4bb4-a120-2ed4f1c65b17)


or the HTML code viewer on the right?
![Screenshot 2024-01-19 at 10 25 24 AM](https://github.com/flutter/devtools/assets/21270878/956f9d7f-7226-415b-952e-1585bf8dfd62)

**Comment by popoaichuiniu** [comment] 2024-04-17 05:30
yes, "real app snapshot"   @elliette

**Comment by elliette** [comment] 2024-04-17 16:31
FYI @bkonyi - I think this is a feature request for widget preview

**Comment by bkonyi** [comment] 2024-04-17 17:24
Yep, I think this is a duplicate of https://github.com/flutter/flutter/issues/115704.

**Comment by kenzieschmoll** [comment] 2024-07-17 21:27
closing as a duplicate of https://github.com/flutter/flutter/issues/115704

**Closed by kenzieschmoll** 2024-07-17 21:27 UTC
Labels: inspector page, new feature
