### ISSUE TITLE
Bugs on Copy network response

### ISSUE THREAD

**Issue by Mufkhalif** [flutter/devtools#5832] opened 2023-05-21 12:19 UTC
I am unable to copy the network response using the copy action.

![Screenshot at May 21 19-18-17](https://github.com/flutter/devtools/assets/33028301/13dd690d-a2e0-43a0-a171-580f7968f0c4)

**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 3.0.0
Flutter Version: 3.10.0 / stable
Framework / Engine: 84a1e904f4 / d44b5a94c9
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment] 2023-05-22 16:33
@CoderDake sounds related to https://github.com/flutter/devtools/issues/5775

**Comment by CoderDake** [comment] 2023-05-23 12:09
our working suspicion is that this is a vscode bug, so we have a ticket open with them.
Right now feel free to give this issue a thumbs up for more visibility:
https://github.com/microsoft/vscode/issues/182642

**Comment by kenzieschmoll** [comment] 2023-05-26 22:58
closing as a dupe of https://github.com/flutter/devtools/issues/5775

**Closed by kenzieschmoll** 2023-05-26 22:58 UTC
