### ISSUE TITLE
Flutter devtools not working for web only tried on chrome as device

### ISSUE THREAD

**Issue by mrinmoy247** [flutter/devtools#3150] opened 2021-06-21 15:40 UTC
![image](https://user-images.githubusercontent.com/24210848/122788474-fd07a080-d2d3-11eb-9bf6-234c0610fc0c.png)

facing a weird issue when i am trying to run any web version of flutter the dart dev tools goes on loading but for android it is working

**Comment by mrinmoy247** [comment] 2021-06-21 15:41
http://127.0.0.1:9102/#/inspector?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A61124%2FRc1ghq9swnc%3D%2F

**Comment by kenzieschmoll** [comment] 2021-06-21 16:17
What version of DevTools are you using? This may be a duplicate of https://github.com/flutter/devtools/issues/3105, which was fixed with the DevTools 2.3.3 release

**Comment by mrinmoy247** [comment] 2021-06-22 05:05
the version i am having is 2.3.3 , can you please suggest if it contains the fix
![image](https://user-images.githubusercontent.com/24210848/122866346-68d62180-d345-11eb-97ab-3144709b158e.png)

**Comment by kenzieschmoll** [comment] 2021-06-22 14:44
How are you running your app? Is it a debug or profile build? The fact that the debugger tab is not visible is suspicious to me 

CC@jacob314

**Comment by mrinmoy247** [comment] 2021-06-23 05:08
i used to do start debugging  from my vscode , is there any other file that needs the configurations changed even one of the other guy was also facing the same issue
![image](https://user-images.githubusercontent.com/24210848/123038527-317f7780-d40e-11eb-9eff-8ad0a03e65b2.png)

**Comment by mrinmoy247** [comment] 2021-06-30 15:16
is flutter dev tools working for any of you members for web, because many of our team members are not able to run it cc @kenzieschmoll can you please suggest what can i do to make it run, thanks@!

**Comment by kenzieschmoll** [comment] 2021-07-01 19:52
This issue seems like a duplicate of https://github.com/flutter/devtools/issues/3105, which we thought was already fixed. We'll leave this issue open and the other closed, but it appears to be a similar problem.

**Comment by mrinmoy247** [comment] 2021-09-21 10:38
![image](https://user-images.githubusercontent.com/24210848/134156619-1d180a87-57f8-4efd-bab1-b7d46a4bbe02.png)

**Comment by MahMoos** [comment] 2021-11-29 13:27
I have the same issue on:

DevTools version 2.6.0
```

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/abc/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

```

Flutter plugin for Android Studio has been updated from 61.2.2 → 62.0.1 and the problem still presists.

**Comment by kenzieschmoll** [comment] 2022-02-15 16:56
Have there been any recent discoveries with flutter web debugging that would shed light on this issue? @elliette @annagrin 

@mrinmoy247 @MahMoos are either of you still seeing this issue? Thanks.

**Comment by MahMoos** [comment] 2022-02-20 22:22
> Have there been any recent discoveries with flutter web debugging that would shed light on this issue? @elliette @annagrin
> 
> @mrinmoy247 @MahMoos are either of you still seeing this issue? Thanks.

I'm still experiencing problems running DevTools for profile mode on web. But it works fine on debug mode. My DevTools version is `2.9.2+1 `and flutter version `2.10.1`.

**Comment by naveenbharadwaj19** [comment] 2022-04-09 07:15
Same issue #3967

**Comment by kenzieschmoll** [comment] 2022-04-11 15:09
@elliette can you take a look at this issue?

**Comment by elliette** [comment] 2022-04-11 17:05
Sure, looking!

**Comment by elliette** [comment] 2022-04-11 18:37
Flutter DevTools is not supported for Flutter Web apps running in profile mode. See https://github.com/flutter/devtools/issues/3969#issuecomment-1095412620 for more details, thanks!

**Closed by elliette** 2022-04-11 18:37 UTC
Labels: bug, P1
