### ISSUE TITLE
Flutter DevTools VSCode plugin does not collapse JSON response

### ISSUE THREAD

**Issue by Zfinix** [flutter/devtools#7309] opened 2024-03-04 19:34 UTC
Open Network Page in vscode:

<img width="240" alt="Screenshot 2024-03-04 at 8 30 13 PM" src="https://github.com/flutter/devtools/assets/25801929/bf01986c-12d6-4527-b3be-2a7643a4cb6a">

Inspect any API with a long JSON response:

https://github.com/flutter/devtools/assets/25801929/648eb712-4f19-47df-bf5d-f654afb6fcd6

___
**DevTools version**: 2.28.4
**IDE**: VSCode
**Connected Device**:

CPU / OS: arm64 (64 bit) ios
Connected app type: Flutter native (debug build)
Dart Version: 3.2.3
Flutter Version: 3.16.5 / stable
Framework / Engine: 78666c8dc5 / 3f3e560236

**Comment by kenzieschmoll** [comment] 2024-03-04 19:38
Looks like your Flutter version is a bit out of date. Can you try upgrading to the latest Flutter stable and see if the issue still reproduces? Thanks.

**Comment by Zfinix** [comment] 2024-03-04 20:05
Will do so

Chiziaruhoma O.

**Comment by kenzieschmoll** [comment] 2024-07-17 21:03
@Zfinix are you still experiencing this issue after upgrading your Flutter version?

**Comment by elliette** [comment] 2024-07-19 18:00
Confirmed that this is now fixed:

![network_panel](https://github.com/user-attachments/assets/32825b76-f23e-4bc6-899b-66b1822226ee)

**Closed by elliette** 2024-07-19 18:00 UTC
Labels: bug, waiting for customer response, network page, P2, reproduce to verify
